/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstadoCuenta } from '../../models/estado-cuenta';
import { PaginaCuenta } from '../../models/pagina-cuenta';
import { Rol } from '../../models/rol';

export interface PanelListarCuentas$Params {
  estado?: EstadoCuenta;
  rol?: Rol;

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function panelListarCuentas(http: HttpClient, rootUrl: string, params?: PanelListarCuentas$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaCuenta>> {
  const rb = new RequestBuilder(rootUrl, panelListarCuentas.PATH, 'get');
  if (params) {
    rb.query('estado', params.estado, {});
    rb.query('rol', params.rol, {});
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaCuenta>;
    })
  );
}

panelListarCuentas.PATH = '/api/v1/panel/cuentas';
