/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CuentaConCredencialTemporal } from '../../models/cuenta-con-credencial-temporal';
import { CuentaCreacionEntrada } from '../../models/cuenta-creacion-entrada';

export interface PanelCrearCuenta$Params {

/**
 * UUID opcional (DEC-AUTO-107, CHG-API-001). Ámbito: (cuenta, clave), único en TODAS las operaciones del panel (DB_HANDOFF v1.1, UNIQUE(cuenta_id, clave)); cada petición debe usar una clave nueva. Solo se guardan respuestas 2xx confirmadas, durante 24 h. Repetir la misma clave en la misma operación con la misma huella (operación + parámetros de ruta + cuerpo canónico) devuelve el código y el cuerpo originales sin repetir el efecto (ALT-017). Misma clave con otra operación u otra huella → 422 idempotencia_conflicto. Si hay una petición concurrente con la misma clave aún en curso y la espera supera 3 s → 409 idempotencia_en_curso con Retry-After (reintentable con la misma clave). Respuesta no reproducible (CHG-API-002, DEC-AUTO-219): si la operación se completó pero su respuesta original NO se guardó, repetir la misma clave con la misma huella devuelve 409 idempotencia_respuesta_no_reproducible sin repetir el efecto. Ocurre (a) siempre en panelCrearCuenta, que nunca persiste su respuesta (AC-106, la contraseña temporal nunca se guarda; DEC-AUTO-129), y (b) en CUALQUIER operación idempotente cuyo cuerpo de respuesta original superó 64 KB (65 536 bytes, DEC-AUTO-128). La cabecera Location solo acompaña al caso de panelCrearCuenta (ruta de la cuenta creada); en el resto, el cliente trata la operación como ya realizada y relee el recurso afectado. Si la operación falla (4xx/5xx) no se guarda nada y el reintento con la misma clave la ejecuta de nuevo.
 */
  'Idempotency-Key'?: string;
      body: CuentaCreacionEntrada
}

export function panelCrearCuenta(http: HttpClient, rootUrl: string, params: PanelCrearCuenta$Params, context?: HttpContext): Observable<StrictHttpResponse<CuentaConCredencialTemporal>> {
  const rb = new RequestBuilder(rootUrl, panelCrearCuenta.PATH, 'post');
  if (params) {
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CuentaConCredencialTemporal>;
    })
  );
}

panelCrearCuenta.PATH = '/api/v1/panel/cuentas';
