/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cuenta } from '../../models/cuenta';
import { Id } from '../../models/id';

export interface PanelAnonimizarCuenta$Params {
  id: Id;
}

export function panelAnonimizarCuenta(http: HttpClient, rootUrl: string, params: PanelAnonimizarCuenta$Params, context?: HttpContext): Observable<StrictHttpResponse<Cuenta>> {
  const rb = new RequestBuilder(rootUrl, panelAnonimizarCuenta.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Cuenta>;
    })
  );
}

panelAnonimizarCuenta.PATH = '/api/v1/panel/cuentas/{id}/anonimizar';
