/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cuenta } from '../../models/cuenta';
import { CuentaActualizacionEntrada } from '../../models/cuenta-actualizacion-entrada';
import { Id } from '../../models/id';

export interface PanelActualizarCuenta$Params {
  id: Id;
      body: CuentaActualizacionEntrada
}

export function panelActualizarCuenta(http: HttpClient, rootUrl: string, params: PanelActualizarCuenta$Params, context?: HttpContext): Observable<StrictHttpResponse<Cuenta>> {
  const rb = new RequestBuilder(rootUrl, panelActualizarCuenta.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Cuenta>;
    })
  );
}

panelActualizarCuenta.PATH = '/api/v1/panel/cuentas/{id}';
