/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CodigosRecuperacion } from '../../models/codigos-recuperacion';
import { MfaCodigoEntrada } from '../../models/mfa-codigo-entrada';

export interface PanelConfirmarActivacionMfa$Params {
      body: MfaCodigoEntrada
}

export function panelConfirmarActivacionMfa(http: HttpClient, rootUrl: string, params: PanelConfirmarActivacionMfa$Params, context?: HttpContext): Observable<StrictHttpResponse<CodigosRecuperacion>> {
  const rb = new RequestBuilder(rootUrl, panelConfirmarActivacionMfa.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CodigosRecuperacion>;
    })
  );
}

panelConfirmarActivacionMfa.PATH = '/api/v1/panel/auth/mfa/activacion/confirmar';
