/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AutorizacionVigente } from '../../models/autorizacion-vigente';

export interface PanelObtenerAutorizacion$Params {
}

export function panelObtenerAutorizacion(http: HttpClient, rootUrl: string, params?: PanelObtenerAutorizacion$Params, context?: HttpContext): Observable<StrictHttpResponse<AutorizacionVigente>> {
  const rb = new RequestBuilder(rootUrl, panelObtenerAutorizacion.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AutorizacionVigente>;
    })
  );
}

panelObtenerAutorizacion.PATH = '/api/v1/panel/auth/autorizacion';
