/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoginEntrada } from '../../models/login-entrada';
import { SesionEstado } from '../../models/sesion-estado';

export interface PanelIniciarSesion$Params {
      body: LoginEntrada
}

export function panelIniciarSesion(http: HttpClient, rootUrl: string, params: PanelIniciarSesion$Params, context?: HttpContext): Observable<StrictHttpResponse<SesionEstado>> {
  const rb = new RequestBuilder(rootUrl, panelIniciarSesion.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SesionEstado>;
    })
  );
}

panelIniciarSesion.PATH = '/api/v1/panel/auth/login';
