/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MfaActivacionInicio } from '../../models/mfa-activacion-inicio';
import { MfaActivacionInicioEntrada } from '../../models/mfa-activacion-inicio-entrada';

export interface PanelIniciarActivacionMfa$Params {
      body: MfaActivacionInicioEntrada
}

export function panelIniciarActivacionMfa(http: HttpClient, rootUrl: string, params: PanelIniciarActivacionMfa$Params, context?: HttpContext): Observable<StrictHttpResponse<MfaActivacionInicio>> {
  const rb = new RequestBuilder(rootUrl, panelIniciarActivacionMfa.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MfaActivacionInicio>;
    })
  );
}

panelIniciarActivacionMfa.PATH = '/api/v1/panel/auth/mfa/activacion';
