/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { PaginaUsoMedio } from '../../models/pagina-uso-medio';

export interface PanelListarUsosMedio$Params {
  id: Id;

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function panelListarUsosMedio(http: HttpClient, rootUrl: string, params: PanelListarUsosMedio$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaUsoMedio>> {
  const rb = new RequestBuilder(rootUrl, panelListarUsosMedio.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaUsoMedio>;
    })
  );
}

panelListarUsosMedio.PATH = '/api/v1/panel/medios/{id}/usos';
