/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { MedioPanel } from '../../models/medio-panel';

export interface PanelReactivarMedio$Params {
  id: Id;
}

export function panelReactivarMedio(http: HttpClient, rootUrl: string, params: PanelReactivarMedio$Params, context?: HttpContext): Observable<StrictHttpResponse<MedioPanel>> {
  const rb = new RequestBuilder(rootUrl, panelReactivarMedio.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MedioPanel>;
    })
  );
}

panelReactivarMedio.PATH = '/api/v1/panel/medios/{id}/reactivar';
