/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstadoMedio } from '../../models/estado-medio';
import { PaginaMedioPanel } from '../../models/pagina-medio-panel';

export interface PanelListarMedios$Params {
  estado?: EstadoMedio;

/**
 * Código de licencia.
 */
  licencia?: string;
  en_uso?: boolean;

/**
 * Filtro de texto del panel (título, alt, crédito según el recurso).
 */
  q?: string;

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function panelListarMedios(http: HttpClient, rootUrl: string, params?: PanelListarMedios$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaMedioPanel>> {
  const rb = new RequestBuilder(rootUrl, panelListarMedios.PATH, 'get');
  if (params) {
    rb.query('estado', params.estado, {});
    rb.query('licencia', params.licencia, {});
    rb.query('en_uso', params.en_uso, {});
    rb.query('q', params.q, {});
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaMedioPanel>;
    })
  );
}

panelListarMedios.PATH = '/api/v1/panel/medios';
