/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccionAuditoria } from './accion-auditoria';

/**
 * Each possible value of `AccionAuditoria`
 */
export const ACCION_AUDITORIA: AccionAuditoria[] = [
  'LOGIN_OK',
  'LOGIN_FALLIDO',
  'BLOQUEO',
  'LOGOUT',
  'AUTORIZACION_ACEPTADA',
  'CAMBIO_CREDENCIAL',
  'MFA_ACTIVAR',
  'MFA_DESACTIVAR',
  'CREAR',
  'EDITAR',
  'PUBLICAR',
  'ACTUALIZAR_PUBLICACION',
  'RETIRAR',
  'REACTIVAR',
  'ELIMINAR_BORRADOR',
  'RESTAURAR_REVISION',
  'SUBIR_MEDIO',
  'EDITAR_MEDIO',
  'RETIRAR_MEDIO',
  'CONFIG_INICIO',
  'CONFIG_SITIO',
  'TAXONOMIA',
  'CUENTA_CREAR',
  'CUENTA_ROL',
  'CUENTA_RESTABLECER',
  'CUENTA_DESACTIVAR',
  'CUENTA_REACTIVAR',
  'CUENTA_ANONIMIZAR'
];