/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActorRef {

  /**
   * Usuario o seudónimo si la cuenta está anonimizada; "sistema" para procesos.
   */
  etiqueta: string;
  id: (number | null);
}
