/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BloqueoCascada } from '../models/bloqueo-cascada';
import { ContenidoRefPanel } from '../models/contenido-ref-panel';
import { TipoVersionado } from '../models/tipo-versionado';
import { ValidacionEntidad } from '../models/validacion-entidad';

/**
 * Resultado sin efectos del análisis de "Publicar" / "Actualizar publicación" (CHG-API-005). `confirmable` = `entidad.cumple` y todas las `copublicacion[].cumple` y `bloqueos_cascada` vacío.
 */
export interface AnalisisPublicacion {
  bloqueos_cascada: Array<BloqueoCascada>;
  confirmable: boolean;

  /**
   * Tipos en BORRADOR que se publicarán también ("Se publicarán también"), cada uno con su validación en el estado resultante.
   */
  copublicacion: Array<ValidacionEntidad>;

  /**
   * Lista exacta a enviar como `copublicar_tipos` en la operación de escritura.
   */
  copublicar_tipos: Array<TipoVersionado>;

  /**
   * Validación de la entidad principal (en ACTUALIZAR_PUBLICACION de un destino, solo las reglas de tipos).
   */
  entidad: ValidacionEntidad;
  operacion: 'PUBLICAR' | 'ACTUALIZAR_PUBLICACION';

  /**
   * Solo ACTUALIZAR_PUBLICACION de un destino. Tipos que el cambio deja con 0 destinos publicados y se retirarían en cascada.
   */
  tipos_en_cascada: Array<ContenidoRefPanel>;
}
