/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';

/**
 * Cuerpo de `panelAnalizarPublicacion` (CHG-API-005, DEC-AUTO-267).
 */
export interface AnalisisPublicacionEntrada {

  /**
   * Solo destino PUBLICADO. Debe pertenecer a tipos_ids.
   */
  tipo_principal_id?: (number | null);

  /**
   * Solo destino PUBLICADO. Tipos propuestos en el formulario (sin guardar).
   */
  tipos_ids?: Array<Id>;

  /**
   * Versión que el editor tiene abierta (409 conflicto_version si es obsoleta).
   */
  version: number;
}
