/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AutorizacionEntrada {
  decision: 'AUTORIZO' | 'NO_AUTORIZO';

  /**
   * Debe coincidir con la vigente; si no, 409 conflicto_version.
   */
  version_politica: string;
}
