/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrupoBusqueda } from '../models/grupo-busqueda';

/**
 * No incluye `q` (el cliente ya la conoce y la muestra como texto, THREAT-010).
 */
export interface BusquedaAgrupada {
  grupos: {
'destinos': GrupoBusqueda;
'itinerarios': GrupoBusqueda;
'guias': GrupoBusqueda;
'tipos': GrupoBusqueda;
};
  total: number;
}
