/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadRef } from '../models/entidad-ref';
import { TipoVersionado } from '../models/tipo-versionado';

/**
 * Campos de control de "Actualizar publicación" de un destino (CHG-API-005). No son campos del contenido: no se guardan ni aparecen en `DestinoPanel`. En BORRADOR solo se admiten con su valor por defecto.
 */
export interface CamposOperacionPublicada {

  /**
   * Opcional (recomendado). Entidades en cascada que el editor vio y confirmó; si difiere de la calculada → 409 impacto_modificado.
   */
  cascada_confirmada?: Array<EntidadRef>;

  /**
   * Confirma la retirada en cascada de los tipos que el cambio deja con 0 destinos publicados (RULE-025).
   */
  confirmar_cascada?: boolean;

  /**
   * Tipos en BORRADOR que el cambio añade al destino, con su versión (misma semántica que en PublicacionEntrada).
   */
  copublicar_tipos?: Array<TipoVersionado>;
}
