/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Slug } from '../models/slug';
export interface CategoriaGuiaPublica {
  descripcion: string;
  nombre: string;
  slug: Slug;
}
