/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriaGuiaCampos } from '../models/categoria-guia-campos';
import { Id } from '../models/id';
export type CategoriaGuiaPanel = {
'id': Id;
} & CategoriaGuiaCampos;

