/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Slug } from '../models/slug';
export interface CategoriaGuiaCampos {
  activo?: boolean;
  descripcion?: string;
  nombre?: string;
  orden?: number;
  slug?: Slug;
}
