/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColeccionCampos } from '../models/coleccion-campos';
import { ContenidoComunCampos } from '../models/contenido-comun-campos';
type ColeccionEntrada$ = ContenidoComunCampos & ColeccionCampos;
type RequiredProperties = 'titulo';
export type ColeccionEntrada = ColeccionEntrada$ & Required<Pick<ColeccionEntrada$, RequiredProperties>>;

