/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConfiguracionSitioCampos {
  lema?: (string | null);
  nombre_marca?: string;
  responsable_canal_atencion?: (string | null);
  responsable_domicilio?: (string | null);
  responsable_identificacion?: (string | null);
  responsable_nombre?: (string | null);
  texto_descargo?: string;
}
