/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';
export interface ConfigInicioCampos {
  destinos_ids?: Array<Id>;
  guias_ids?: Array<Id>;
  hero_medio_id?: Id;
  hero_subtitulo?: string;
  hero_titular?: string;
  itinerarios_ids?: Array<Id>;
}
