/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImagenPublicaNula } from '../models/imagen-publica-nula';
import { Slug } from '../models/slug';
import { TipoContenidoPublico } from '../models/tipo-contenido-publico';
export interface ContenidoRelacionado {

  /**
   * Curados primero y en su orden; complemento automático por afinidad (DEC-AUTO-042).
   */
  origen: 'CURADO' | 'AUTOMATICO';
  portada?: ImagenPublicaNula;
  resumen?: (string | null);
  slug: Slug;
  tipo: TipoContenidoPublico;
  titulo: string;
}
