/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActorRef } from '../models/actor-ref';
import { ContenidoRefPanel } from '../models/contenido-ref-panel';
import { EstadoEditorial } from '../models/estado-editorial';
import { Id } from '../models/id';
import { MedioMiniatura } from '../models/medio-miniatura';
import { RequisitosPublicacion } from '../models/requisitos-publicacion';
import { TipoEntidadContenido } from '../models/tipo-entidad-contenido';
export interface ContenidoPanelMeta {
  actualizado_en: string;
  actualizado_por: ActorRef;
  creado_en: string;
  creado_por: ActorRef;
  estado_editorial: EstadoEditorial;
  id: Id;
  motivo_retiro?: (string | null);
  primera_publicacion_en?: (string | null);
  publicado_actualizado_en?: (string | null);

  /**
   * Datos de visualización de los ids referenciados (medios, contenidos, términos, taxonomías).
   */
  referencias: {
'medios'?: Array<MedioMiniatura>;
'contenidos'?: Array<ContenidoRefPanel>;
'terminos'?: Array<{
'id': Id;
'termino': string;
}>;
'taxonomias'?: Array<{
'clase': 'PAIS' | 'TIPO' | 'CATEGORIA';
'id': Id;
'nombre': string;
}>;
};
  requisitos_publicacion: RequisitosPublicacion;
  retirado_en?: (string | null);
  slug_bloqueado: boolean;
  tipo: TipoEntidadContenido;
  url_publica?: (string | null);
  version: number;
}
