/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Slug } from '../models/slug';
import { TipoContenidoPublico } from '../models/tipo-contenido-publico';
export interface ContenidoRefPublico {
  slug: Slug;
  tipo: TipoContenidoPublico;
  titulo: string;
}
