/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Continente } from './continente';

/**
 * Each possible value of `Continente`
 */
export const CONTINENTE: Continente[] = [
  'AMERICA',
  'EUROPA',
  'AFRICA',
  'ASIA',
  'OCEANIA',
  'ANTARTIDA'
];