/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FuenteEntrada } from '../models/fuente-entrada';
import { Id } from '../models/id';
import { RelacionEntrada } from '../models/relacion-entrada';

/**
 * Campos editoriales comunes (ATR-COMUN). Nunca incluye estado, autoría ni version (THREAT-024).
 */
export interface ContenidoComunCampos {

  /**
   * No futura (RULE-009).
   */
  fecha_ultima_revision?: (string | null);
  fuentes?: Array<FuenteEntrada>;

  /**
   * Relacionados curados en orden (FEAT-039). Sin autorrelación ni duplicados.
   */
  relaciones?: Array<RelacionEntrada>;
  seo_descripcion?: (string | null);
  seo_titulo?: (string | null);

  /**
   * Null → se propone desde el título. Inmutable tras la primera publicación (RULE-008).
   */
  slug?: (string | null);
  terminos_ids?: Array<Id>;
  titulo?: string;
}
