/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoRefPublico } from '../models/contenido-ref-publico';
import { ImagenPublica } from '../models/imagen-publica';
export interface CreditoMedio {
  imagen: ImagenPublica;
  usado_en: Array<ContenidoRefPublico>;
}
