/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cuenta } from '../models/cuenta';

/**
 * La contraseña temporal solo aparece en esta respuesta (no-store) y nunca se registra (AC-106).
 */
export interface CuentaConCredencialTemporal {
  contrasena_temporal: string;
  cuenta: Cuenta;
}
