/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Rol } from '../models/rol';
export interface CuentaCreacionEntrada {
  nombre_visible: string;
  rol: Rol;
  usuario: string;
}
