/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FormatoDerivado } from '../models/formato-derivado';
export interface DerivadoImagen {
  alto?: number;
  ancho: number;
  formato: FormatoDerivado;

  /**
   * Ruta estática pública con nombre generado por el sistema (DEC-AUTO-110).
   */
  url: string;
}
