/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { DestinoCampos } from '../models/destino-campos';
import { IdOpcionalCampo } from '../models/id-opcional-campo';
type DestinoVistaPrevia$ = ContenidoComunCampos & DestinoCampos & IdOpcionalCampo;
type RequiredProperties = 'titulo';
export type DestinoVistaPrevia = DestinoVistaPrevia$ & Required<Pick<DestinoVistaPrevia$, RequiredProperties>>;

