/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { ContenidoPanelMeta } from '../models/contenido-panel-meta';
import { DestinoCampos } from '../models/destino-campos';
export type DestinoPanel = ContenidoPanelMeta & ContenidoComunCampos & DestinoCampos;

