/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { DestinoCampos } from '../models/destino-campos';
type DestinoEntrada$ = ContenidoComunCampos & DestinoCampos;
type RequiredProperties = 'titulo';
export type DestinoEntrada = DestinoEntrada$ & Required<Pick<DestinoEntrada$, RequiredProperties>>;

