/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Día de itinerario. `titulo` y `actividades` son obligatorios y no admiten null porque las columnas dia_itinerario.titulo (varchar(150)) y dia_itinerario.actividades (text) son NOT NULL en BD (CHG-API-003 / DEC-AUTO-905). Un día que aún no tiene esos datos no se envía.
 */
export interface DiaEntrada {
  actividades: string;
  alojamiento_orientativo?: (string | null);
  consejos?: (string | null);
  desnivel_negativo_m?: (number | null);
  desnivel_positivo_m?: (number | null);
  distancia_km?: (number | null);
  numero_dia: number;
  titulo: string;
}
