/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DestinoTarjeta } from '../models/destino-tarjeta';
import { ItinerarioTarjeta } from '../models/itinerario-tarjeta';

/**
 * Exactamente uno de `destino` / `itinerario` según `tipo`. Solo elementos publicados (RULE-024).
 */
export interface ElementoColeccion {
  destino?: (DestinoTarjeta | null);
  itinerario?: (ItinerarioTarjeta | null);
  nota_editorial?: (string | null);
  orden: number;
  tipo: 'DESTINO' | 'ITINERARIO';
}
