/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';
export interface ElementoColeccionEntrada {
  contenido_id: Id;
  nota_editorial?: (string | null);
  orden: number;
  tipo_contenido: 'DESTINO' | 'ITINERARIO';
}
