/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';
import { TipoEntidadContenido } from '../models/tipo-entidad-contenido';

/**
 * Referencia a una entidad de contenido del panel (entrada).
 */
export interface EntidadRef {
  id: Id;
  tipo: TipoEntidadContenido;
}
