/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorRegla } from '../models/error-regla';
import { EstadoEditorial } from '../models/estado-editorial';
import { Id } from '../models/id';
import { RolEntidadOperacion } from '../models/rol-entidad-operacion';
import { TipoEntidadContenido } from '../models/tipo-entidad-contenido';

/**
 * Errores de validación de una entidad dentro de una operación multi-entidad (CHG-API-005).
 */
export interface ErroresEntidad {
  errores: Array<ErrorRegla>;
  estado_editorial: EstadoEditorial;
  id: Id;
  rol: RolEntidadOperacion;
  tipo: TipoEntidadContenido;
  titulo: string;
}
