/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoRefPanel } from '../models/contenido-ref-panel';

/**
 * Requisito incumplido de una entidad (CHG-API-005 extrae a este esquema el elemento de `RequisitosPublicacion.pendientes`, sin cambiar sus campos, y añade `referencias` opcional). `campo` usa la notación de `Problem.errors` (`_general` para errores de la entidad completa). Códigos multi-entidad (DEC-AUTO-266): tipo_retirado (RULE-002: "Reactiva primero el tipo {nombre}"; `referencias` = el tipo) · tipo_no_publicado (RULE-002: tipo en BORRADOR no incluido en `copublicar_tipos`; `referencias` = el tipo) · copublicacion_tipo_no_asociado · copublicacion_tipo_no_borrador · tipo_sin_destino_publicado (RULE-025, AC-126: `referencias` = destinos en BORRADOR que tienen asociado el tipo, remite a la co-publicación) · itinerario_tipo_no_publicado (RULE-003, DEC-AUTO-914: `referencias` = los tipos no PUBLICADOS). El resto de códigos son los de requisitos por campo de cada tipo de contenido.
 */
export interface ErrorRegla {
  campo: string;
  code: string;
  mensaje: string;

  /**
   * Entidades enlazables desde el mensaje (editor del panel).
   */
  referencias?: Array<ContenidoRefPanel>;
}
