/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NivelEscalaPanel } from '../models/nivel-escala-panel';
export interface EscalasPanel {
  dificultad: Array<NivelEscalaPanel>;
  presupuesto: Array<NivelEscalaPanel>;
}
