/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NivelEscala } from '../models/nivel-escala';
export interface Escalas {
  dificultad: Array<NivelEscala>;
  presupuesto: Array<NivelEscala>;
}
