/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoMedio } from './estado-medio';

/**
 * Each possible value of `EstadoMedio`
 */
export const ESTADO_MEDIO: EstadoMedio[] = [
  'PENDIENTE_METADATOS',
  'DISPONIBLE',
  'RETIRADO'
];