/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoCuenta } from './estado-cuenta';

/**
 * Each possible value of `EstadoCuenta`
 */
export const ESTADO_CUENTA: EstadoCuenta[] = [
  'PENDIENTE_ACTIVACION',
  'ACTIVA',
  'BLOQUEADA_TEMPORAL',
  'DESACTIVADA',
  'ANONIMIZADA'
];