/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoEditorial } from './estado-editorial';

/**
 * Each possible value of `EstadoEditorial`
 */
export const ESTADO_EDITORIAL: EstadoEditorial[] = [
  'BORRADOR',
  'PUBLICADO',
  'RETIRADO'
];