/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FormatoDerivado } from './formato-derivado';

/**
 * Each possible value of `FormatoDerivado`
 */
export const FORMATO_DERIVADO: FormatoDerivado[] = [
  'AVIF',
  'WEBP',
  'JPEG'
];