/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FuenteEntrada {
  entidad_editora?: (string | null);
  fecha_consulta?: (string | null);
  titulo: string;
  url?: (string | null);
}
