/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ResultadoBusqueda } from '../models/resultado-busqueda';
export interface GrupoBusqueda {
  resultados: Array<ResultadoBusqueda>;
  total: number;
}
