/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { ContenidoPanelMeta } from '../models/contenido-panel-meta';
import { GuiaCampos } from '../models/guia-campos';
export type GuiaPanel = ContenidoPanelMeta & ContenidoComunCampos & GuiaCampos & {
'palabras'?: (number | null);
};

