/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriaGuiaPublica } from '../models/categoria-guia-publica';
import { ContenidoRelacionado } from '../models/contenido-relacionado';
import { DestinoTarjeta } from '../models/destino-tarjeta';
import { FuentePublica } from '../models/fuente-publica';
import { ImagenPublica } from '../models/imagen-publica';
import { MetadatosEditoriales } from '../models/metadatos-editoriales';
import { RefTaxonomia } from '../models/ref-taxonomia';
import { Slug } from '../models/slug';
import { TerminoRef } from '../models/termino-ref';
import { TextoEnriquecido } from '../models/texto-enriquecido';
export interface GuiaDetalle {
  categoria: CategoriaGuiaPublica;
  cuerpo: TextoEnriquecido;
  destinos_relacionados: Array<DestinoTarjeta>;
  fuentes: Array<FuentePublica>;
  metadatos: MetadatosEditoriales;
  minutos_lectura?: (number | null);
  portada: ImagenPublica;
  relacionados: Array<ContenidoRelacionado>;
  remite_a_metodologia: boolean;
  resumen: string;
  slug: Slug;
  terminos: Array<TerminoRef>;
  tipos_relacionados: Array<RefTaxonomia>;
  titulo: string;
}
