/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { GuiaCampos } from '../models/guia-campos';
import { IdOpcionalCampo } from '../models/id-opcional-campo';
type GuiaVistaPrevia$ = ContenidoComunCampos & GuiaCampos & IdOpcionalCampo;
type RequiredProperties = 'titulo';
export type GuiaVistaPrevia = GuiaVistaPrevia$ & Required<Pick<GuiaVistaPrevia$, RequiredProperties>>;

