/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';
export interface GuiaCampos {
  categoria_id?: (number | null);
  cuerpo?: (string | null);
  destinos_ids?: Array<Id>;
  portada_id?: (number | null);
  remite_a_metodologia?: boolean;
  resumen?: (string | null);
  tipos_ids?: Array<Id>;
}
