/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { GuiaCampos } from '../models/guia-campos';
type GuiaEntrada$ = ContenidoComunCampos & GuiaCampos;
type RequiredProperties = 'titulo';
export type GuiaEntrada = GuiaEntrada$ & Required<Pick<GuiaEntrada$, RequiredProperties>>;

