/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IdOpcionalCampo {

  /**
   * Contenido en edición (para excluirlo de sus relacionados).
   */
  id?: (number | null);
}
