/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DerivadoImagen } from '../models/derivado-imagen';
import { LicenciaPublica } from '../models/licencia-publica';

/**
 * Solo medios DISPONIBLES (RULE-005). Sin datos del staff (THREAT-019).
 */
export interface ImagenPublica {
  alto?: number;
  ancho?: number;
  autor_credito: string;
  derivados: Array<DerivadoImagen>;
  fuente_url?: (string | null);
  licencia: LicenciaPublica;
  pie_de_foto?: (string | null);
  texto_alternativo: string;
}
