/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BloqueoCascada } from '../models/bloqueo-cascada';
import { ContenidoRefPanel } from '../models/contenido-ref-panel';
import { ReferenciaUso } from '../models/referencia-uso';
export interface ImpactoRetiro {
  bloqueos: Array<ReferenciaUso>;

  /**
   * Itinerarios PUBLICADOS de otros destinos que bloquean la cascada de un tipo (RULE-003, DEC-AUTO-914).
   */
  bloqueos_cascada: Array<BloqueoCascada>;
  colecciones: Array<ContenidoRefPanel>;
  destacados: Array<'DESTINOS' | 'ITINERARIOS' | 'GUIAS'>;
  enlaces_entrantes: number;
  itinerarios_en_cascada: Array<ContenidoRefPanel>;
  retirable: boolean;

  /**
   * Tipos PUBLICADOS cuyo único destino publicado es el que se retira (RULE-025, CHG-API-005).
   */
  tipos_en_cascada: Array<ContenidoRefPanel>;
}
