/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoRefPanel } from '../models/contenido-ref-panel';
import { ReferenciaUso } from '../models/referencia-uso';
export interface ImpactoRetiro {
  bloqueos: Array<ReferenciaUso>;
  colecciones: Array<ContenidoRefPanel>;
  destacados: Array<'DESTINOS' | 'ITINERARIOS' | 'GUIAS'>;
  enlaces_entrantes: number;
  itinerarios_en_cascada: Array<ContenidoRefPanel>;
  retirable: boolean;
}
