/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BloqueoCascada } from '../models/bloqueo-cascada';
import { ContenidoRefPanel } from '../models/contenido-ref-panel';

/**
 * Entidades que una operación retiraría en cascada y bloqueos de esa cascada (CHG-API-005).
 */
export interface ImpactoCascada {
  bloqueos_cascada: Array<BloqueoCascada>;
  itinerarios_en_cascada: Array<ContenidoRefPanel>;
  tipos_en_cascada: Array<ContenidoRefPanel>;
}
