/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { IdOpcionalCampo } from '../models/id-opcional-campo';
import { ItinerarioCampos } from '../models/itinerario-campos';
type ItinerarioVistaPrevia$ = ContenidoComunCampos & ItinerarioCampos & IdOpcionalCampo;
type RequiredProperties = 'titulo';
export type ItinerarioVistaPrevia = ItinerarioVistaPrevia$ & Required<Pick<ItinerarioVistaPrevia$, RequiredProperties>>;

