/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { ItinerarioCampos } from '../models/itinerario-campos';
type ItinerarioEntrada$ = ContenidoComunCampos & ItinerarioCampos;
type RequiredProperties = 'titulo';
export type ItinerarioEntrada = ItinerarioEntrada$ & Required<Pick<ItinerarioEntrada$, RequiredProperties>>;

