/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { ContenidoPanelMeta } from '../models/contenido-panel-meta';
import { ItinerarioCampos } from '../models/itinerario-campos';
export type ItinerarioPanel = ContenidoPanelMeta & ContenidoComunCampos & ItinerarioCampos;

