/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DiaEntrada } from '../models/dia-entrada';
import { Id } from '../models/id';
export interface ItinerarioCampos {
  desnivel_acumulado_m?: (number | null);
  destino_id?: (number | null);

  /**
   * Número de días = duracion_dias para publicar (RULE-003, AC-118). numero_dia único.
   */
  dias?: Array<DiaEntrada>;
  dificultad?: (number | null);
  distancia_total_km?: (number | null);
  duracion_dias?: (number | null);
  galeria_ids?: Array<Id>;
  portada_id?: (number | null);
  resumen?: (string | null);
  riesgos_seguridad?: (string | null);
  tipos_ids?: Array<Id>;
}
