/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LicenciaPublica {
  codigo: string;
  nombre: string;
  requiere_atribucion: boolean;
  url_texto_legal?: (string | null);
}
