/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginEntrada {
  contrasena: string;

  /**
   * Solo se honra si es ruta relativa bajo /panel/ (AC-115).
   */
  siguiente?: (string | null);
  usuario: string;
}
