/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActorRef } from '../models/actor-ref';
import { DerivadoImagen } from '../models/derivado-imagen';
import { EstadoMedio } from '../models/estado-medio';
import { Id } from '../models/id';
export interface MedioPanel {
  actualizado_en: string;
  alto_px: number;
  ancho_px: number;
  autor_credito?: (string | null);

  /**
   * URLs del endpoint autenticado /api/v1/panel/medios/{id}/archivo.
   */
  derivados: Array<DerivadoImagen>;
  en_uso_publicado: boolean;
  estado: EstadoMedio;
  formato_origen: 'JPEG' | 'PNG' | 'WEBP';
  fuente_url?: (string | null);
  id: Id;
  licencia?: ({
'id': Id;
'codigo': string;
'nombre': string;
'compatible_publicacion': boolean;
} | null);
  numero_usos: number;
  pendientes_catalogacion: Array<'texto_alternativo' | 'autor_credito' | 'licencia' | 'licencia_incompatible'>;
  peso_bytes: number;
  pie_de_foto?: (string | null);
  subido_en: string;
  subido_por: ActorRef;
  texto_alternativo?: (string | null);
  titulo_interno?: (string | null);
}
