/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Autoría como firma de equipo (DEC-AUTO-039); nunca creado_por ni nombres del staff.
 */
export interface MetadatosEditoriales {
  autoria: string;
  fecha_ultima_revision: string;
  primera_publicacion_en?: (string | null);
  publicado_actualizado_en: string;
  seo_descripcion: string;
  seo_titulo: string;
}
