/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Reautenticación para iniciar la activación de MFA (CHG-API-002, DEC-AUTO-215).
 */
export interface MfaActivacionInicioEntrada {
  contrasena: string;
}
