/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NivelEscala {
  descripcion: string;
  escala: 'DIFICULTAD' | 'PRESUPUESTO';
  etiqueta: string;
  nivel: number;
}
