/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';
import { NivelEscala } from '../models/nivel-escala';
export type NivelEscalaPanel = {
'id': Id;
} & NivelEscala;

