/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DestinoMapaItem } from '../models/destino-mapa-item';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaDestinoMapa = PaginaMeta & {
'resultados': Array<DestinoMapaItem>;
};

