/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriaGuiaIndice } from '../models/categoria-guia-indice';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaCategoriaGuiaIndice = PaginaMeta & {
'resultados': Array<CategoriaGuiaIndice>;
};

