/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoPanelMeta } from '../models/contenido-panel-meta';
import { PaginaInstitucionalCampos } from '../models/pagina-institucional-campos';
export type PaginaInstitucionalPanel = ContenidoPanelMeta & PaginaInstitucionalCampos & {
'clave': 'ACERCA_DE' | 'POLITICA_DATOS' | 'POLITICA_COOKIES' | 'AVISO_LEGAL';
'solo_administrador': boolean;
};

