/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginaMeta } from '../models/pagina-meta';
import { Pais } from '../models/pais';
export type PaginaPais = PaginaMeta & {
'resultados': Array<Pais>;
};

