/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventoAuditoria } from '../models/evento-auditoria';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaEventoAuditoria = PaginaMeta & {
'resultados': Array<EventoAuditoria>;
};

