/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DestinoTarjeta } from '../models/destino-tarjeta';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaDestinoTarjeta = PaginaMeta & {
'resultados': Array<DestinoTarjeta>;
};

