/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaginaInstitucionalCampos {
  cuerpo?: string;
  fecha_ultima_revision?: (string | null);
  seo_descripcion?: (string | null);
  seo_titulo?: (string | null);
  titulo?: string;
  version_documento?: string;
  vigente_desde?: string;
}
