/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoResumenPanel } from '../models/contenido-resumen-panel';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaContenidoResumen = PaginaMeta & {
'resultados': Array<ContenidoResumenPanel>;
};

