/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginaInstitucionalCampos } from '../models/pagina-institucional-campos';
import { VersionCampo } from '../models/version-campo';
type PaginaInstitucionalActualizacion$ = PaginaInstitucionalCampos & VersionCampo;
type RequiredProperties = 'titulo' | 'cuerpo' | 'version_documento' | 'vigente_desde' | 'version';
export type PaginaInstitucionalActualizacion = PaginaInstitucionalActualizacion$ & Required<Pick<PaginaInstitucionalActualizacion$, RequiredProperties>>;

