/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntradaIndice } from '../models/entrada-indice';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaEntradaIndice = PaginaMeta & {
'resultados': Array<EntradaIndice>;
};

