/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColeccionTarjeta } from '../models/coleccion-tarjeta';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaColeccionTarjeta = PaginaMeta & {
'resultados': Array<ColeccionTarjeta>;
};

