/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaginaMeta {
  anterior: (string | null);
  pagina: number;
  siguiente: (string | null);
  tamano_pagina: number;
  total: number;
  total_paginas: number;
}
