/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginaMeta } from '../models/pagina-meta';
import { TipoAventuraTarjeta } from '../models/tipo-aventura-tarjeta';
export type PaginaTipoAventuraTarjeta = PaginaMeta & {
'resultados': Array<TipoAventuraTarjeta>;
};

