/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginaMeta } from '../models/pagina-meta';
import { RevisionResumen } from '../models/revision-resumen';
export type PaginaRevisionResumen = PaginaMeta & {
'resultados': Array<RevisionResumen>;
};

