/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginaMeta } from '../models/pagina-meta';
import { ResultadoBusqueda } from '../models/resultado-busqueda';
export type PaginaResultadoBusqueda = PaginaMeta & {
'resultados': Array<ResultadoBusqueda>;
};

