/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MedioPanel } from '../models/medio-panel';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaMedioPanel = PaginaMeta & {
'resultados': Array<MedioPanel>;
};

