/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IdOpcionalCampo } from '../models/id-opcional-campo';
import { PaginaInstitucionalCampos } from '../models/pagina-institucional-campos';
type PaginaInstitucionalVistaPrevia$ = PaginaInstitucionalCampos & IdOpcionalCampo;
type RequiredProperties = 'titulo';
export type PaginaInstitucionalVistaPrevia = PaginaInstitucionalVistaPrevia$ & Required<Pick<PaginaInstitucionalVistaPrevia$, RequiredProperties>>;

