/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginaMeta } from '../models/pagina-meta';
import { Region } from '../models/region';
export type PaginaRegion = PaginaMeta & {
'resultados': Array<Region>;
};

