/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItinerarioTarjeta } from '../models/itinerario-tarjeta';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaItinerarioTarjeta = PaginaMeta & {
'resultados': Array<ItinerarioTarjeta>;
};

