/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cuenta } from '../models/cuenta';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaCuenta = PaginaMeta & {
'resultados': Array<Cuenta>;
};

