/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MetadatosEditoriales } from '../models/metadatos-editoriales';
import { TextoEnriquecido } from '../models/texto-enriquecido';
export interface PaginaInstitucionalPublica {
  cuerpo: TextoEnriquecido;
  metadatos: MetadatosEditoriales;
  slug: 'acerca-de' | 'politica-de-tratamiento-de-datos' | 'politica-de-cookies' | 'aviso-legal';
  titulo: string;
  version_documento: string;
  vigente_desde: string;
}
