/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreditoMedio } from '../models/credito-medio';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaCreditoMedio = PaginaMeta & {
'resultados': Array<CreditoMedio>;
};

