/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriaGuiaPanel } from '../models/categoria-guia-panel';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaCategoriaGuiaPanel = PaginaMeta & {
'resultados': Array<CategoriaGuiaPanel>;
};

