/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GuiaTarjeta } from '../models/guia-tarjeta';
import { PaginaMeta } from '../models/pagina-meta';
export type PaginaGuiaTarjeta = PaginaMeta & {
'resultados': Array<GuiaTarjeta>;
};

