/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginaMeta } from '../models/pagina-meta';
import { UsoMedio } from '../models/uso-medio';
export type PaginaUsoMedio = PaginaMeta & {
'resultados': Array<UsoMedio>;
};

