/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';
import { Slug } from '../models/slug';
export interface PaisCampos {
  activo?: boolean;
  codigo_iso2?: string;
  nombre?: string;
  region_id?: Id;
  slug?: Slug;
}
