/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RegionPublica } from '../models/region-publica';
import { Slug } from '../models/slug';
export interface PaisPublico {
  codigo_iso2: string;
  nombre: string;
  region: RegionPublica;
  slug: Slug;
}
