/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';
import { PaisCampos } from '../models/pais-campos';
export type Pais = {
'id': Id;
} & PaisCampos;

