/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';
export interface PaisCampos {
  activo?: boolean;
  codigo_iso2?: string;
  nombre?: string;
  region_id?: Id;

  /**
   * pais.slug es varchar(80) en BD (CHG-API-003).
   */
  slug?: string;
}
