/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErroresEntidad } from '../models/errores-entidad';
import { ProblemaValidacion } from '../models/problema-validacion';

/**
 * Problema de validación de una publicación multi-entidad (CHG-API-005, DEC-AUTO-266). `errors` se mantiene por compatibilidad: claves `{campo}` para la entidad principal y `copublicar_tipos.{id}.{campo}` para cada tipo co-publicado. `errores_por_entidad` es la fuente estructurada para SCR-038 ("lista de errores agrupada por entidad", FLOW-011 6a'); aparece siempre con code publicacion_invalida y nunca con idempotencia_conflicto.
 */
export type ProblemaPublicacion = ProblemaValidacion & {

/**
 * Solo las entidades con errores; la principal primero y después los tipos por id ascendente.
 */
'errores_por_entidad'?: Array<ErroresEntidad>;
};

