/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Problem Details (RFC 9457). `type` = `{PROBLEM_TYPE_BASE_URL}/errors/{code}` (base configurable,
 * DEC-AUTO-103). `title` y `detail` en español, sin datos técnicos. Catálogo de `code`:
 * 400 validacion, parametro_invalido, campo_no_permitido ·
 * 401 no_autenticado, sesion_expirada, credenciales_invalidas, mfa_requerido, mfa_invalido ·
 * 403 permiso_denegado, csrf_invalido, cambio_credencial_requerido, autorizacion_requerida, configuracion_mfa_requerida ·
 * 404 no_encontrado, pagina_fuera_de_rango · 405 metodo_no_permitido ·
 * 409 conflicto_version, transicion_invalida, slug_inmutable, slug_en_uso, duplicado, dependencia_bloqueante, medio_en_uso, ultimo_administrador, operacion_sobre_si_mismo, mfa_obligatorio, idempotencia_en_curso, idempotencia_respuesta_no_reproducible ·
 * 410 retirado · 413 carga_demasiado_grande · 415 tipo_medio_no_soportado ·
 * 422 publicacion_invalida, regla_negocio, idempotencia_conflicto ·
 * 429 limite_tasa, acceso_bloqueado_temporalmente · 500 error_interno · 503 servicio_no_disponible.
 */
export interface Problem {
  code: string;
  detail?: string;

  /**
   * Mensajes por campo. Campos anidados con notación de puntos (p. ej. `dias.2.titulo`); errores generales en `_general`.
   */
  errors?: {
[key: string]: Array<string>;
};
  instance?: string;
  status: number;
  title: string;
  trace_id: string;
  type: string;
}
