/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Problem } from '../models/problem';
import { ReferenciaUso } from '../models/referencia-uso';
export type ProblemaConUsos = Problem & {
'usos'?: Array<ReferenciaUso>;
'total_usos'?: number;
};

