/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Problem } from '../models/problem';
type ProblemaValidacion$ = Problem & {
};
type RequiredProperties = 'errors';
export type ProblemaValidacion = ProblemaValidacion$ & Required<Pick<ProblemaValidacion$, RequiredProperties>>;

