/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BloqueoCascada } from '../models/bloqueo-cascada';
import { ContenidoRefPanel } from '../models/contenido-ref-panel';
import { ImpactoCascada } from '../models/impacto-cascada';
import { Problem } from '../models/problem';
import { ReferenciaUso } from '../models/referencia-uso';
export type ProblemaConUsos = Problem & {
'usos'?: Array<ReferenciaUso>;
'total_usos'?: number;

/**
 * Solo con code cascada_bloqueada (CHG-API-005). Por cada tipo cuya cascada se bloquea, los itinerarios PUBLICADOS que lo usan.
 */
'bloqueos_cascada'?: Array<BloqueoCascada>;

/**
 * Solo con code cascada_sin_confirmar o impacto_modificado (CHG-API-005). Cascada calculada bajo bloqueo.
 */
'impacto_cascada'?: ImpactoCascada;

/**
 * Solo con code conflicto_version en operaciones multi-entidad (CHG-API-005). Entidades cuya versión enviada está obsoleta.
 */
'entidades_en_conflicto'?: Array<ContenidoRefPanel>;
};

