/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoRelacionado } from '../models/contenido-relacionado';
import { Problem } from '../models/problem';
export type ProblemaRetirado = Problem & {
'alternativas': Array<ContenidoRelacionado>;

/**
 * Ruta pública del listado padre (p. ej. /destinos).
 */
'listado_padre'?: string;
};

