/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoVersionado } from '../models/tipo-versionado';

/**
 * Cuerpo de `panelPublicarContenido` (CHG-API-005, DEC-AUTO-265). Sustituye a `TransicionEntrada` en esa operación y es un superconjunto compatible: `{version}` sigue siendo un cuerpo válido.
 */
export interface PublicacionEntrada {

  /**
   * Solo destinos. Lista EXACTA de los tipos del destino (incluido el principal) en BORRADOR, con su versión. Vacía si todos sus tipos ya están PUBLICADOS. Sin ids repetidos (400 validacion).
   */
  copublicar_tipos?: Array<TipoVersionado>;
  version: number;
}
