/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoEditorial } from '../models/estado-editorial';
import { Id } from '../models/id';
export interface ReferenciaUso {
  estado_editorial?: (EstadoEditorial | null);
  id: Id;
  tipo_entidad: string;
  titulo: string;
}
