/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Continente } from '../models/continente';
import { Slug } from '../models/slug';
export interface RegionPublica {
  continente: Continente;
  nombre: string;
  slug: Slug;
}
