/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Continente } from '../models/continente';
export interface RegionCampos {
  activo?: boolean;
  continente?: Continente;
  nombre?: string;
  orden?: number;

  /**
   * region.slug es varchar(60) en BD (CHG-API-003).
   */
  slug?: string;
}
