/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';
import { TipoContenidoPublico } from '../models/tipo-contenido-publico';
export interface RelacionEntrada {
  id: Id;
  tipo: TipoContenidoPublico;
}
