/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorRegla } from '../models/error-regla';
export interface RequisitosPublicacion {
  cumple: boolean;
  pendientes: Array<ErrorRegla>;
}
