/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RestauracionRevision {

  /**
   * Cuerpo compatible con el `{Tipo}Actualizacion` del tipo, sin `version`.
   */
  datos: {
};
  numero_revision: number;
  version_actual: number;
}
