/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoRefPanel } from '../models/contenido-ref-panel';
import { EstadoEditorial } from '../models/estado-editorial';
import { Id } from '../models/id';
import { TipoEntidadContenido } from '../models/tipo-entidad-contenido';
export interface ResultadoTransicion {

  /**
   * Entidades retiradas en cascada (destino → itinerarios).
   */
  afectados: Array<ContenidoRefPanel>;
  estado_editorial: EstadoEditorial;
  id: Id;
  numero_revision?: (number | null);
  tipo: TipoEntidadContenido;
  url_publica?: (string | null);
  version: number;
}
