/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoRefPanel } from '../models/contenido-ref-panel';
import { EntidadTransitada } from '../models/entidad-transitada';
import { EstadoEditorial } from '../models/estado-editorial';
import { Id } from '../models/id';
import { TipoEntidadContenido } from '../models/tipo-entidad-contenido';
export interface ResultadoTransicion {

  /**
   * Entidades distintas de la principal que cambiaron de estado en la misma operación: tipos co-publicados (publicar) o itinerarios y tipos retirados en cascada (retirar). Vacío en reactivar. Se mantiene por compatibilidad; `entidades` es la lista completa con versiones (CHG-API-005).
   */
  afectados: Array<ContenidoRefPanel>;

  /**
   * TODAS las entidades que cambiaron de estado, la principal primero (`origen: PRINCIPAL`), con su nueva versión y número de revisión (CHG-API-005, AC-125, AC-127).
   */
  entidades: Array<EntidadTransitada>;
  estado_editorial: EstadoEditorial;
  id: Id;
  numero_revision?: (number | null);
  tipo: TipoEntidadContenido;
  url_publica?: (string | null);
  version: number;
}
