/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RetiroEntrada {
  confirmar_cascada?: boolean;

  /**
   * Interno; nunca se publica.
   */
  motivo: string;
  version: number;
}
