/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntidadRef } from '../models/entidad-ref';
export interface RetiroEntrada {

  /**
   * Opcional (recomendado; CHG-API-005, DEC-AUTO-268). Itinerarios y tipos en cascada que el editor vio en `panelObtenerImpactoRetiro` y confirmó. Si difiere del conjunto calculado bajo bloqueo → 409 impacto_modificado y nada cambia. Si se omite, `confirmar_cascada: true` confirma la cascada calculada en el momento (comportamiento anterior).
   */
  cascada_confirmada?: Array<EntidadRef>;
  confirmar_cascada?: boolean;

  /**
   * Interno; nunca se publica.
   */
  motivo: string;
  version: number;
}
