/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActorRef } from '../models/actor-ref';
export interface RevisionResumen {
  creado_en: string;
  creado_por: ActorRef;
  motivo: 'PUBLICACION' | 'ACTUALIZACION' | 'RETIRO' | 'RESTAURACION';
  numero_revision: number;
}
