/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RevisionResumen } from '../models/revision-resumen';
export type RevisionDetalle = RevisionResumen & {

/**
 * Documento estructurado con todos los campos y relaciones del contenido (DATA-026).
 */
'instantanea': {
};
};

