/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Rol } from './rol';

/**
 * Each possible value of `Rol`
 */
export const ROL: Rol[] = [
  'EDITOR',
  'ADMINISTRADOR'
];