/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * PRINCIPAL = la entidad de la ruta; COPUBLICACION = tipo publicado en la misma operación; CASCADA = entidad retirada en cascada.
 */
export type RolEntidadOperacion = 'PRINCIPAL' | 'COPUBLICACION' | 'CASCADA';

