/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RolEntidadOperacion } from './rol-entidad-operacion';

/**
 * Each possible value of `RolEntidadOperacion`
 */
export const ROL_ENTIDAD_OPERACION: RolEntidadOperacion[] = [
  'PRINCIPAL',
  'COPUBLICACION',
  'CASCADA'
];