/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Rol } from '../models/rol';
export interface SesionEstado {
  expira_absoluta_en: string;
  expira_inactividad_en: string;
  mfa_activo: boolean;
  mfa_obligatorio: boolean;
  nombre_visible: string;

  /**
   * Mientras no sea NINGUNO, el resto del panel responde 401 mfa_requerido o 403 cambio_credencial_requerido / configuracion_mfa_requerida / autorizacion_requerida (STATE-004, DEC-AUTO-102/119).
   */
  paso_pendiente: 'NINGUNO' | 'MFA' | 'CAMBIO_CREDENCIAL' | 'CONFIGURAR_MFA' | 'AUTORIZACION';
  redireccion: string;
  rol: Rol;
  usuario: string;
}
