/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoRefPanel } from '../models/contenido-ref-panel';
import { ContenidoResumenPanel } from '../models/contenido-resumen-panel';
import { TipoEntidadContenido } from '../models/tipo-entidad-contenido';
export interface Tablero {
  alertas: Array<{
'code': 'responsable_sin_definir' | 'destacado_retirado' | 'coleccion_bajo_minimo';
'mensaje': string;
'enlace'?: (string | null);
}>;
  conteos: Array<{
'tipo': TipoEntidadContenido;
'borrador': number;
'publicado': number;
'retirado': number;
}>;
  recientes: Array<ContenidoResumenPanel>;

  /**
   * EXP-001 (COULD). Null si no está implementado.
   */
  salud_editorial?: ({
'revisiones_antiguas'?: Array<ContenidoRefPanel>;
'medios_pendientes_metadatos'?: number;
'medios_sin_uso'?: number;
'colecciones_bajo_minimo'?: Array<ContenidoRefPanel>;
'destacados_bajo_minimo'?: Array<'DESTINOS' | 'ITINERARIOS' | 'GUIAS'>;
'contenidos_con_pocos_relacionados'?: Array<ContenidoRefPanel>;
} | null);
}
