/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TerminoGlosarioCampos } from '../models/termino-glosario-campos';
import { VersionCampo } from '../models/version-campo';
type TerminoGlosarioActualizacion$ = TerminoGlosarioCampos & VersionCampo;
type RequiredProperties = 'titulo' | 'version';
export type TerminoGlosarioActualizacion = TerminoGlosarioActualizacion$ & Required<Pick<TerminoGlosarioActualizacion$, RequiredProperties>>;

