/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoPanelMeta } from '../models/contenido-panel-meta';
import { ContenidoRefPanel } from '../models/contenido-ref-panel';
import { TerminoGlosarioCampos } from '../models/termino-glosario-campos';
export type TerminoGlosarioPanel = ContenidoPanelMeta & TerminoGlosarioCampos & {
'vinculado_en': Array<ContenidoRefPanel>;
};

