/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TerminoGlosarioCampos } from '../models/termino-glosario-campos';
type TerminoGlosarioEntrada$ = TerminoGlosarioCampos;
type RequiredProperties = 'titulo';
export type TerminoGlosarioEntrada = TerminoGlosarioEntrada$ & Required<Pick<TerminoGlosarioEntrada$, RequiredProperties>>;

