/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TerminoGlosarioCampos {
  definicion?: (string | null);
  fecha_ultima_revision?: (string | null);
  slug?: (string | null);

  /**
   * El término; único sin distinguir mayúsculas ni tildes (RULE-026).
   */
  titulo?: string;
}
