/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * HTML de lista blanca saneado en el servidor al guardar (RULE-022, DEC-AUTO-043/109): p, h2-h4, ul, ol, li, strong, em, blockquote y a[href] con http, https o ruta interna (RULE-021); términos de glosario como `<a href="/glosario#{slug}" data-glosario="{slug}">`. Todo lo demás se elimina.
 */
export type TextoEnriquecido = string;

