/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChecklistEntrada } from '../models/checklist-entrada';
export interface TipoAventuraCampos {

  /**
   * Si existe, ≥8 elementos para publicar (RULE-025). Texto único por tipo.
   */
  checklist?: Array<ChecklistEntrada>;
  descripcion?: (string | null);
  nivel_exigencia?: (number | null);
  orden?: number;
  portada_id?: (number | null);
  resumen?: (string | null);
}
