/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoEntidadContenido } from './tipo-entidad-contenido';

/**
 * Each possible value of `TipoEntidadContenido`
 */
export const TIPO_ENTIDAD_CONTENIDO: TipoEntidadContenido[] = [
  'DESTINO',
  'ITINERARIO',
  'GUIA',
  'TIPO',
  'COLECCION',
  'TERMINO',
  'PAGINA'
];