/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { IdOpcionalCampo } from '../models/id-opcional-campo';
import { TipoAventuraCampos } from '../models/tipo-aventura-campos';
type TipoAventuraVistaPrevia$ = ContenidoComunCampos & TipoAventuraCampos & IdOpcionalCampo;
type RequiredProperties = 'titulo';
export type TipoAventuraVistaPrevia = TipoAventuraVistaPrevia$ & Required<Pick<TipoAventuraVistaPrevia$, RequiredProperties>>;

