/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { ContenidoPanelMeta } from '../models/contenido-panel-meta';
import { TipoAventuraCampos } from '../models/tipo-aventura-campos';
export type TipoAventuraPanel = ContenidoPanelMeta & ContenidoComunCampos & TipoAventuraCampos;

