/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChecklistItem } from '../models/checklist-item';
import { ContenidoRelacionado } from '../models/contenido-relacionado';
import { DestinoTarjeta } from '../models/destino-tarjeta';
import { Dificultad } from '../models/dificultad';
import { FuentePublica } from '../models/fuente-publica';
import { GuiaTarjeta } from '../models/guia-tarjeta';
import { ImagenPublica } from '../models/imagen-publica';
import { MetadatosEditoriales } from '../models/metadatos-editoriales';
import { Slug } from '../models/slug';
import { TerminoRef } from '../models/termino-ref';
import { TextoEnriquecido } from '../models/texto-enriquecido';
export interface TipoAventuraDetalle {

  /**
   * Vacío si el tipo no tiene checklist (la sección se oculta, FEAT-011).
   */
  checklist: Array<ChecklistItem>;
  descripcion: TextoEnriquecido;
  destinos: Array<DestinoTarjeta>;
  destinos_total: number;
  fuentes: Array<FuentePublica>;
  guias_relacionadas: Array<GuiaTarjeta>;
  metadatos: MetadatosEditoriales;
  nivel_exigencia: Dificultad;
  portada: ImagenPublica;
  relacionados: Array<ContenidoRelacionado>;
  resumen: string;
  slug: Slug;
  terminos: Array<TerminoRef>;
  titulo: string;
}
