/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { TipoAventuraCampos } from '../models/tipo-aventura-campos';
type TipoAventuraEntrada$ = ContenidoComunCampos & TipoAventuraCampos;
type RequiredProperties = 'titulo';
export type TipoAventuraEntrada = TipoAventuraEntrada$ & Required<Pick<TipoAventuraEntrada$, RequiredProperties>>;

