/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoContenidoRuta } from './tipo-contenido-ruta';

/**
 * Each possible value of `TipoContenidoRuta`
 */
export const TIPO_CONTENIDO_RUTA: TipoContenidoRuta[] = [
  'destinos',
  'itinerarios',
  'guias',
  'tipos-aventura',
  'colecciones',
  'glosario',
  'paginas'
];