/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContenidoComunCampos } from '../models/contenido-comun-campos';
import { TipoAventuraCampos } from '../models/tipo-aventura-campos';
import { VersionCampo } from '../models/version-campo';
type TipoAventuraActualizacion$ = ContenidoComunCampos & TipoAventuraCampos & VersionCampo;
type RequiredProperties = 'titulo' | 'version';
export type TipoAventuraActualizacion = TipoAventuraActualizacion$ & Required<Pick<TipoAventuraActualizacion$, RequiredProperties>>;

