/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Id } from '../models/id';

/**
 * Tipo de aventura en BORRADOR a co-publicar, con la versión que vio el editor (bloqueo optimista, ALT-016).
 */
export interface TipoVersionado {
  id: Id;
  version: number;
}
