/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Dificultad } from '../models/dificultad';
import { ImagenPublicaNula } from '../models/imagen-publica-nula';
import { Slug } from '../models/slug';
export interface TipoAventuraTarjeta {
  nivel_exigencia: Dificultad;
  numero_destinos: number;
  portada: ImagenPublicaNula;
  resumen: string;
  slug: Slug;
  titulo: string;
}
