/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TramoDuracion } from './tramo-duracion';

/**
 * Each possible value of `TramoDuracion`
 */
export const TRAMO_DURACION: TramoDuracion[] = [
  '1-3',
  '4-7',
  '8-14',
  '15+'
];