/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstadoEditorial } from '../models/estado-editorial';
import { Id } from '../models/id';
export interface UsoMedio {
  contenido_id: Id;
  estado_editorial?: (EstadoEditorial | null);
  rol: 'PORTADA' | 'GALERIA' | 'HERO';
  tipo_contenido: 'DESTINO' | 'ITINERARIO' | 'GUIA' | 'TIPO' | 'COLECCION' | 'CONFIG_INICIO';
  titulo: string;
}
