/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorRegla } from '../models/error-regla';
import { EstadoEditorial } from '../models/estado-editorial';
import { Id } from '../models/id';
import { RolEntidadOperacion } from '../models/rol-entidad-operacion';
import { TipoEntidadContenido } from '../models/tipo-entidad-contenido';

/**
 * Resultado de la validación de publicación de una entidad en el estado resultante de la operación (CHG-API-005).
 */
export interface ValidacionEntidad {
  cumple: boolean;
  estado_editorial: EstadoEditorial;
  id: Id;
  pendientes: Array<ErrorRegla>;
  rol: RolEntidadOperacion;
  slug?: (string | null);
  tipo: TipoEntidadContenido;
  titulo: string;
  version: number;
}
