# Generated by Django 5.2.17 on 2026-09-26 03:57

import apps.medios.campos
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_inicial'),
        ('cuentas', '0001_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_saneado_ruta', models.CharField(max_length=255, unique=True)),
                ('formato_origen', models.CharField(choices=[('JPEG', 'JPEG'), ('PNG', 'PNG'), ('WEBP', 'WebP')], max_length=4)),
                ('ancho_px', models.IntegerField()),
                ('alto_px', models.IntegerField()),
                ('peso_bytes', models.IntegerField()),
                ('huella_sha256', apps.medios.campos.CampoSha256(unique=True)),
                ('sha256_saneado', apps.medios.campos.CampoSha256()),
                ('titulo_interno', models.CharField(blank=True, max_length=150, null=True)),
                ('texto_alternativo', models.CharField(blank=True, max_length=250, null=True)),
                ('pie_de_foto', models.CharField(blank=True, max_length=300, null=True)),
                ('autor_credito', models.CharField(blank=True, max_length=150, null=True)),
                ('fuente_url', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_METADATOS', 'Pendiente de metadatos'), ('DISPONIBLE', 'Disponible'), ('RETIRADO', 'Retirado')], db_default='PENDIENTE_METADATOS', default='PENDIENTE_METADATOS', max_length=20)),
                ('subido_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('actualizado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medios', to='catalogos.licencia')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.cuentastaff')),
            ],
            options={
                'db_table': 'medio',
            },
        ),
        migrations.CreateModel(
            name='MedioDerivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('AVIF', 'AVIF'), ('WEBP', 'WebP'), ('JPEG', 'JPEG')], max_length=4)),
                ('ancho_px', models.IntegerField()),
                ('alto_px', models.IntegerField()),
                ('ruta', models.CharField(max_length=255, unique=True)),
                ('peso_bytes', models.IntegerField()),
                ('sha256', apps.medios.campos.CampoSha256()),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivados', to='medios.medio')),
            ],
            options={
                'db_table': 'medio_derivado',
            },
        ),
        migrations.AddIndex(
            model_name='medio',
            index=models.Index(models.F('estado'), models.OrderBy(models.F('subido_en'), descending=True), name='ix_medio_estado_subido'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=models.Q(('formato_origen__in', ['JPEG', 'PNG', 'WEBP'])), name='ck_medio_formato_origen'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=models.Q(('ancho_px__gt', 0)), name='ck_medio_ancho'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=models.Q(('alto_px__gt', 0)), name='ck_medio_alto'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=models.Q(('peso_bytes__gte', 1), ('peso_bytes__lte', 10485760)), name='ck_medio_peso'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=models.Q(('huella_sha256__regex', '^[0-9a-f]{64}$')), name='ck_medio_huella'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=models.Q(('sha256_saneado__regex', '^[0-9a-f]{64}$')), name='ck_medio_sha256_saneado'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=models.Q(('fuente_url__isnull', True), ('fuente_url__regex', '^(https?://|/)'), _connector='OR'), name='ck_medio_fuente_url'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE_METADATOS', 'DISPONIBLE', 'RETIRADO'])), name='ck_medio_estado'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast('ancho_px', models.BigIntegerField()), '*', models.F('alto_px')), 40000000), name='ck_medio_megapixeles'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThanOrEqual(django.db.models.functions.comparison.Greatest('ancho_px', 'alto_px'), 1200), name='ck_medio_lado_mayor'),
        ),
        migrations.AddConstraint(
            model_name='medio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'DISPONIBLE'), _negated=True), models.Q(('autor_credito__isnull', False), ('licencia__isnull', False), ('texto_alternativo__isnull', False)), _connector='OR'), name='ck_medio_disponible'),
        ),
        migrations.AddConstraint(
            model_name='medioderivado',
            constraint=models.UniqueConstraint(fields=('medio', 'formato', 'ancho_px'), name='uq_medio_derivado'),
        ),
        migrations.AddConstraint(
            model_name='medioderivado',
            constraint=models.CheckConstraint(condition=models.Q(('formato__in', ['AVIF', 'WEBP', 'JPEG'])), name='ck_medio_derivado_formato'),
        ),
        migrations.AddConstraint(
            model_name='medioderivado',
            constraint=models.CheckConstraint(condition=models.Q(('ancho_px__gt', 0)), name='ck_medio_derivado_ancho'),
        ),
        migrations.AddConstraint(
            model_name='medioderivado',
            constraint=models.CheckConstraint(condition=models.Q(('alto_px__gt', 0)), name='ck_medio_derivado_alto'),
        ),
        migrations.AddConstraint(
            model_name='medioderivado',
            constraint=models.CheckConstraint(condition=models.Q(('peso_bytes__gt', 0)), name='ck_medio_derivado_peso'),
        ),
        migrations.AddConstraint(
            model_name='medioderivado',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='ck_medio_derivado_sha256'),
        ),
    ]
