# Generated by Django 5.2.17 on 2026-09-27 18:10 (makemigrations --empty + RunSQL)

# CHG-DB-002 (DB_HANDOFF v1.2, plan n=16, DEC-AUTO-203): los medios persistidos nunca se borran
# físicamente; se retiran (BLUEPRINT §39.2). Defensa en profundidad:
# (1) trigger BEFORE DELETE que rechaza cualquier borrado (también del propietario);
# (2) app_rw pierde DELETE y TRUNCATE sobre medio (conserva DELETE en medio_derivado).
# Patrón expand, reversible sin pérdida de datos (solo objetos de catálogo).
from django.db import migrations

TRG_MEDIO_SIN_BORRADO = """
CREATE FUNCTION app.fn_medio_sin_borrado() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, app, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION 'Los medios persistidos no se borran físicamente: se retiran (id %)', OLD.id
    USING ERRCODE = 'restrict_violation', CONSTRAINT = 'trg_medio_sin_borrado';
END
$$;
CREATE TRIGGER trg_medio_sin_borrado
  BEFORE DELETE ON app.medio
  FOR EACH ROW EXECUTE FUNCTION app.fn_medio_sin_borrado();
"""

REVERSO_TRG_MEDIO_SIN_BORRADO = """
DROP TRIGGER trg_medio_sin_borrado ON app.medio;
DROP FUNCTION app.fn_medio_sin_borrado();
"""

PRIVILEGIOS = "REVOKE DELETE, TRUNCATE ON app.medio FROM app_rw;"

REVERSO_PRIVILEGIOS = "GRANT DELETE ON app.medio TO app_rw;"


class Migration(migrations.Migration):

    dependencies = [
        ('medios', '0001_inicial'),
    ]

    operations = [
        migrations.RunSQL(TRG_MEDIO_SIN_BORRADO, reverse_sql=REVERSO_TRG_MEDIO_SIN_BORRADO),
        migrations.RunSQL(PRIVILEGIOS, reverse_sql=REVERSO_PRIVILEGIOS),
    ]
