/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ColeccionDetalle } from '../../models/coleccion-detalle';
import { Slug } from '../../models/slug';

export interface PublicoObtenerColeccion$Params {
  slug: Slug;
}

export function publicoObtenerColeccion(http: HttpClient, rootUrl: string, params: PublicoObtenerColeccion$Params, context?: HttpContext): Observable<StrictHttpResponse<ColeccionDetalle>> {
  const rb = new RequestBuilder(rootUrl, publicoObtenerColeccion.PATH, 'get');
  if (params) {
    rb.path('slug', params.slug, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ColeccionDetalle>;
    })
  );
}

publicoObtenerColeccion.PATH = '/api/v1/publico/colecciones/{slug}';
