# Generated by Django 5.2.17 on 2026-09-26 03:57

import apps.medios.campos
import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.lookups
from django.db import migrations, models

# Migración n=12 del plan (DB_HANDOFF v1.1, CHG-DB-001): además de los modelos, RunSQL para
# (1) el constraint trigger diferido de idempotencia, (2) cache_limites UNLOGGED, (3) la vista
# v_medio_uso y (4) los privilegios de readonly (tablas excluidas y columnas) y de
# django_migrations (solo SELECT para app_rw). Patrón expand, reversible.

# DEC-AUTO-124: al confirmar, la fila debe tener la respuesta 2xx. Se relee la fila porque en un
# trigger diferido NEW es la imagen del momento del evento (el INSERT aún sin respuesta).
TRG_IDEMPOTENCIA_COMPLETA = """
CREATE FUNCTION app.fn_idempotencia_completa() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, app
AS $$
DECLARE
  fila record;
BEGIN
  SELECT codigo_http, cuerpo_respuesta, cuerpo_omitido INTO fila
    FROM app.idempotencia_peticion WHERE id = NEW.id;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  IF fila.codigo_http IS NULL OR (fila.cuerpo_respuesta IS NULL AND NOT fila.cuerpo_omitido) THEN
    RAISE EXCEPTION 'La clave de idempotencia % no tiene una respuesta 2xx completa al confirmar',
      NEW.id USING ERRCODE = 'check_violation', CONSTRAINT = 'trg_idempotencia_completa';
  END IF;
  RETURN NULL;
END
$$;
CREATE CONSTRAINT TRIGGER trg_idempotencia_completa
  AFTER INSERT OR UPDATE ON app.idempotencia_peticion
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION app.fn_idempotencia_completa();
"""

REVERSO_TRG_IDEMPOTENCIA_COMPLETA = """
DROP TRIGGER trg_idempotencia_completa ON app.idempotencia_peticion;
DROP FUNCTION app.fn_idempotencia_completa();
"""

# ADR-DB-005 §3: esquema compatible con createcachetable (DatabaseCache "cache_limites"), UNLOGGED:
# excluida de las copias (--no-unlogged-table-data). Claves = HMAC, nunca la IP en claro.
CACHE_LIMITES = """
CREATE UNLOGGED TABLE app.cache_limites (
  cache_key varchar(255) NOT NULL PRIMARY KEY,
  value text NOT NULL,
  expires timestamptz NOT NULL
);
CREATE INDEX cache_limites_expires ON app.cache_limites (expires);
"""

# DEC-AUTO-085: usos de un medio (PORTADA, GALERIA, HERO). `id` es una clave sintética.
VISTA_MEDIO_USO = """
CREATE VIEW app.v_medio_uso AS
  SELECT ('PORTADA:' || c.id)::varchar(40) AS id,
         c.portada_id AS medio_id,
         c.id AS contenido_id,
         c.tipo AS tipo_contenido,
         c.titulo AS titulo,
         c.estado_editorial AS estado_editorial,
         'PORTADA'::varchar(7) AS rol
    FROM app.contenido c
   WHERE c.portada_id IS NOT NULL
  UNION ALL
  SELECT ('GALERIA:' || cm.id)::varchar(40),
         cm.medio_id,
         c.id,
         c.tipo,
         c.titulo,
         c.estado_editorial,
         'GALERIA'::varchar(7)
    FROM app.contenido_medio cm
    JOIN app.contenido c ON c.id = cm.contenido_id
  UNION ALL
  SELECT ('HERO:' || ci.id)::varchar(40),
         ci.hero_medio_id,
         NULL::bigint,
         NULL::varchar(10),
         NULL::varchar(150),
         NULL::varchar(10),
         'HERO'::varchar(7)
    FROM app.config_inicio ci;
"""

# DB_HANDOFF roles: readonly sin sesiones, códigos, caché ni idempotencia (cuerpo_respuesta es
# PII); columnas no PII de cuenta_staff y evento_auditoria. app_rw: django_migrations solo SELECT.
PRIVILEGIOS = """
REVOKE ALL ON app.sesion_panel, app.cuenta_codigo_recuperacion, app.cache_limites,
              app.idempotencia_peticion FROM readonly;
REVOKE ALL ON app.cuenta_staff FROM readonly;
GRANT SELECT (id, rol, estado, mfa_activo, creado_en, desactivado_en, anonimizado_en)
  ON app.cuenta_staff TO readonly;
REVOKE ALL ON app.evento_auditoria FROM readonly;
GRANT SELECT (id, ocurrido_en, actor_id, accion, resultado, tipo_entidad, entidad_id,
              entidad_titulo, campos_cambiados)
  ON app.evento_auditoria TO readonly;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON app.django_migrations FROM app_rw;
REVOKE ALL ON app.v_medio_uso FROM app_rw, readonly;
GRANT SELECT ON app.v_medio_uso TO app_rw, readonly;
"""

REVERSO_PRIVILEGIOS = """
GRANT INSERT, UPDATE, DELETE ON app.v_medio_uso TO app_rw;
GRANT INSERT, UPDATE, DELETE ON app.django_migrations TO app_rw;
REVOKE SELECT (id, ocurrido_en, actor_id, accion, resultado, tipo_entidad, entidad_id,
               entidad_titulo, campos_cambiados)
  ON app.evento_auditoria FROM readonly;
GRANT SELECT ON app.evento_auditoria TO readonly;
REVOKE SELECT (id, rol, estado, mfa_activo, creado_en, desactivado_en, anonimizado_en)
  ON app.cuenta_staff FROM readonly;
GRANT SELECT ON app.cuenta_staff TO readonly;
GRANT SELECT ON app.sesion_panel, app.cuenta_codigo_recuperacion, app.cache_limites,
               app.idempotencia_peticion TO readonly;
"""


class Migration(migrations.Migration):

    initial = True

    # Última migración del plan (n=12): los grants y la vista afectan a tablas de todas las apps.
    dependencies = [
        ('auditoria', '0002_inmutabilidad'),
        ('busqueda', '0002_inicial'),
        ('catalogos', '0002_semilla'),
        ('contenido', '0002_integridad_sql'),
        ('cuentas', '0001_inicial'),
        ('inicio', '0001_inicial'),
        ('medios', '0001_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioUso',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('tipo_contenido', models.CharField(choices=[('DESTINO', 'Destino'), ('ITINERARIO', 'Itinerario'), ('GUIA', 'Guía'), ('TIPO', 'Tipo de aventura'), ('COLECCION', 'Colección'), ('TERMINO', 'Término de glosario'), ('PAGINA', 'Página institucional')], max_length=10, null=True)),
                ('titulo', models.CharField(max_length=150, null=True)),
                ('estado_editorial', models.CharField(max_length=10, null=True)),
                ('rol', models.CharField(choices=[('PORTADA', 'Portada'), ('GALERIA', 'Galeria'), ('HERO', 'Hero')], max_length=7)),
            ],
            options={
                'db_table': 'v_medio_uso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpsEjecucionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(choices=[('PURGA_AUDITORIA', 'Purga Auditoria'), ('ANONIMIZACION_CUENTAS', 'Anonimizacion Cuentas'), ('PURGA_SESIONES', 'Purga Sesiones'), ('PURGA_OPS', 'Purga Ops'), ('REINDEX_BUSQUEDA', 'Reindex Busqueda'), ('VERIFICACION_BUSQUEDA', 'Verificacion Busqueda'), ('REAPLICAR_ANONIMIZACIONES', 'Reaplicar Anonimizaciones')], max_length=40)),
                ('iniciado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('EN_CURSO', 'En Curso'), ('EXITO', 'Exito'), ('FALLO', 'Fallo')], db_default='EN_CURSO', default='EN_CURSO', max_length=8)),
                ('filas_afectadas', models.IntegerField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ops_ejecucion_tarea',
                'indexes': [models.Index(models.F('tarea'), models.OrderBy(models.F('iniciado_en'), descending=True), name='ix_ops_tarea_iniciado')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tarea__in', ['PURGA_AUDITORIA', 'ANONIMIZACION_CUENTAS', 'PURGA_SESIONES', 'PURGA_OPS', 'REINDEX_BUSQUEDA', 'VERIFICACION_BUSQUEDA', 'REAPLICAR_ANONIMIZACIONES'])), name='ck_ops_ejecucion_tarea'), models.CheckConstraint(condition=models.Q(('resultado__in', ['EN_CURSO', 'EXITO', 'FALLO'])), name='ck_ops_ejecucion_resultado')],
            },
        ),
        migrations.CreateModel(
            name='IdempotenciaPeticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.UUIDField()),
                ('operacion', models.CharField(choices=[('panelCrearDestino', 'Crear Destino'), ('panelCrearItinerario', 'Crear Itinerario'), ('panelCrearGuia', 'Crear Guia'), ('panelCrearTipoAventura', 'Crear Tipo Aventura'), ('panelCrearColeccion', 'Crear Coleccion'), ('panelCrearTerminoGlosario', 'Crear Termino Glosario'), ('panelPublicarContenido', 'Publicar Contenido'), ('panelRetirarContenido', 'Retirar Contenido'), ('panelReactivarContenido', 'Reactivar Contenido'), ('panelSubirMedios', 'Subir Medios'), ('panelCrearCuenta', 'Crear Cuenta')], max_length=40)),
                ('huella_peticion', apps.medios.campos.CampoSha256()),
                ('codigo_http', models.SmallIntegerField(blank=True, null=True)),
                ('recurso_id', models.BigIntegerField(blank=True, null=True)),
                ('cuerpo_respuesta', models.JSONField(blank=True, null=True)),
                ('cuerpo_omitido', models.BooleanField(db_default=False, default=False)),
                ('creado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('expira_en', models.DateTimeField(db_default=django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Now(), '+', models.Value(datetime.timedelta(days=1))))),
                ('cuenta', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='claves_idempotencia', to='cuentas.cuentastaff')),
            ],
            options={
                'db_table': 'idempotencia_peticion',
                'constraints': [models.UniqueConstraint(fields=('cuenta', 'clave'), name='uq_idempotencia_cuenta_clave'), models.CheckConstraint(condition=models.Q(('operacion__in', ['panelCrearDestino', 'panelCrearItinerario', 'panelCrearGuia', 'panelCrearTipoAventura', 'panelCrearColeccion', 'panelCrearTerminoGlosario', 'panelPublicarContenido', 'panelRetirarContenido', 'panelReactivarContenido', 'panelSubirMedios', 'panelCrearCuenta'])), name='ck_idempotencia_operacion'), models.CheckConstraint(condition=models.Q(('huella_peticion__regex', '^[0-9a-f]{64}$')), name='ck_idempotencia_huella'), models.CheckConstraint(condition=models.Q(('codigo_http__isnull', True), models.Q(('codigo_http__gte', 200), ('codigo_http__lte', 299)), _connector='OR'), name='ck_idempotencia_codigo_http'), models.CheckConstraint(condition=models.Q(('cuerpo_respuesta__isnull', True), django.db.models.lookups.LessThanOrEqual(models.Func(django.db.models.functions.comparison.Cast('cuerpo_respuesta', models.TextField()), function='octet_length', output_field=models.IntegerField()), 65536), _connector='OR'), name='ck_idempotencia_tamano_respuesta'), models.CheckConstraint(condition=models.Q(('expira_en__gt', models.F('creado_en')), ('expira_en__lte', django.db.models.expressions.CombinedExpression(models.F('creado_en'), '+', models.Value(datetime.timedelta(days=1))))), name='ck_idempotencia_expiracion'), models.CheckConstraint(condition=models.Q(('cuerpo_omitido', True), ('cuerpo_respuesta__isnull', False), _negated=True), name='ck_idempotencia_omitido'), models.CheckConstraint(condition=models.Q(models.Q(('operacion', 'panelCrearCuenta'), _negated=True), models.Q(('cuerpo_omitido', True), ('cuerpo_respuesta__isnull', True)), _connector='OR'), name='ck_idempotencia_crear_cuenta')],
            },
        ),
        migrations.RunSQL(TRG_IDEMPOTENCIA_COMPLETA, reverse_sql=REVERSO_TRG_IDEMPOTENCIA_COMPLETA),
        migrations.RunSQL(CACHE_LIMITES, reverse_sql="DROP TABLE app.cache_limites;"),
        migrations.RunSQL(VISTA_MEDIO_USO, reverse_sql="DROP VIEW app.v_medio_uso;"),
        migrations.RunSQL(PRIVILEGIOS, reverse_sql=REVERSO_PRIVILEGIOS),
    ]
