# Generated by Django 5.2.17 on 2026-09-29 21:23

# TKT-011 (RSK-QA004-02, RSK-OPS-032, DEVOPS_HANDOFF §19.3.6): añade el valor VIGILAR_CACHE_LIMITES
# a TareaProgramada para el nuevo comando del planificador `vigilar_cache_limites`. Solo amplía el
# CHECK y las choices de ops_ejecucion_tarea.tarea (patrón expand, reversible, sin tocar filas
# existentes ni ninguna otra tabla).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_inicial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opsejecuciontarea',
            name='ck_ops_ejecucion_tarea',
        ),
        migrations.AlterField(
            model_name='opsejecuciontarea',
            name='tarea',
            field=models.CharField(choices=[('PURGA_AUDITORIA', 'Purga Auditoria'), ('ANONIMIZACION_CUENTAS', 'Anonimizacion Cuentas'), ('PURGA_SESIONES', 'Purga Sesiones'), ('PURGA_OPS', 'Purga Ops'), ('REINDEX_BUSQUEDA', 'Reindex Busqueda'), ('VERIFICACION_BUSQUEDA', 'Verificacion Busqueda'), ('REAPLICAR_ANONIMIZACIONES', 'Reaplicar Anonimizaciones'), ('VIGILAR_CACHE_LIMITES', 'Vigilar Cache Limites')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='opsejecuciontarea',
            constraint=models.CheckConstraint(condition=models.Q(('tarea__in', ['PURGA_AUDITORIA', 'ANONIMIZACION_CUENTAS', 'PURGA_SESIONES', 'PURGA_OPS', 'REINDEX_BUSQUEDA', 'VERIFICACION_BUSQUEDA', 'REAPLICAR_ANONIMIZACIONES', 'VIGILAR_CACHE_LIMITES'])), name='ck_ops_ejecucion_tarea'),
        ),
    ]
