# Generated by Django 5.2.17 on 2026-09-26 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(max_length=400)),
                ('orden', models.SmallIntegerField(db_default=0, default=0)),
                ('activo', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'db_table': 'categoria_guia',
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='ck_categoria_guia_slug')],
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('url_texto_legal', models.CharField(blank=True, max_length=500, null=True)),
                ('requiere_atribucion', models.BooleanField()),
                ('compatible_publicacion', models.BooleanField()),
                ('activo', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'db_table': 'licencia',
                'constraints': [models.CheckConstraint(condition=models.Q(('codigo__regex', '^[A-Z0-9.-]+$')), name='ck_licencia_codigo'), models.CheckConstraint(condition=models.Q(('url_texto_legal__isnull', True), ('url_texto_legal__regex', '^(https?://|/)'), _connector='OR'), name='ck_licencia_url')],
            },
        ),
        migrations.CreateModel(
            name='NivelEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.CharField(choices=[('DIFICULTAD', 'Dificultad'), ('PRESUPUESTO', 'Presupuesto')], max_length=12)),
                ('nivel', models.SmallIntegerField()),
                ('etiqueta', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'nivel_escala',
                'constraints': [models.UniqueConstraint(fields=('escala', 'nivel'), name='uq_nivel_escala'), models.CheckConstraint(condition=models.Q(('escala__in', ['DIFICULTAD', 'PRESUPUESTO'])), name='ck_nivel_escala_escala'), models.CheckConstraint(condition=models.Q(models.Q(('escala', 'DIFICULTAD'), ('nivel__gte', 1), ('nivel__lte', 5)), models.Q(('escala', 'PRESUPUESTO'), ('nivel__gte', 1), ('nivel__lte', 4)), _connector='OR'), name='ck_nivel_escala_rango')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('continente', models.CharField(choices=[('AMERICA', 'América'), ('EUROPA', 'Europa'), ('AFRICA', 'África'), ('ASIA', 'Asia'), ('OCEANIA', 'Oceanía'), ('ANTARTIDA', 'Antártida')], max_length=10)),
                ('orden', models.SmallIntegerField(db_default=0, default=0)),
                ('activo', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'db_table': 'region',
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='ck_region_slug'), models.CheckConstraint(condition=models.Q(('continente__in', ['AMERICA', 'EUROPA', 'AFRICA', 'ASIA', 'OCEANIA', 'ANTARTIDA'])), name='ck_region_continente')],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('codigo_iso2', models.CharField(max_length=2, unique=True)),
                ('activo', models.BooleanField(db_default=True, default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paises', to='catalogos.region')),
            ],
            options={
                'verbose_name_plural': 'países',
                'db_table': 'pais',
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='ck_pais_slug'), models.CheckConstraint(condition=models.Q(('codigo_iso2__regex', '^[A-Z]{2}$')), name='ck_pais_codigo_iso2')],
            },
        ),
    ]
