# Generated by Django 5.2.17 on 2026-09-27 18:10 (makemigrations --empty + RunSQL)

# CHG-DB-002 (DB_HANDOFF v1.2, plan n=18, DEC-AUTO-204): los catálogos se desactivan
# (activo=false) o se editan, no se borran. Solo REVOKE a app_rw, sin trigger: el reverse_code de
# catalogos.0002_semilla borra por clave natural con app_migrator y migrate zero debe seguir
# funcionando. Patrón expand, reversible sin pérdida de datos.
from django.db import migrations

TABLAS = "app.region, app.pais, app.categoria_guia, app.licencia, app.nivel_escala"


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_semilla'),
    ]

    operations = [
        migrations.RunSQL(
            f"REVOKE DELETE, TRUNCATE ON {TABLAS} FROM app_rw;",
            reverse_sql=f"GRANT DELETE ON {TABLAS} TO app_rw;",
        ),
    ]
