# Generated by Django 5.2.17 on 2026-10-08 (makemigrations --empty catalogos + RunPython)

# TKT-041 (DEC-AUTO-967): las fotografías reales de la carga semilla proceden de Wikimedia Commons,
# donde abundan las versiones 2.0, 2.5 y 3.0 de CC BY y CC BY-SA. El catálogo (0002_semilla) solo
# tenía la 4.0. Se añaden con la URL de su texto legal oficial; todas exigen atribución y son
# compatibles con la publicación (REQ-043, REQ-071). Patrón expand: solo inserta (get_or_create,
# idempotente). El reverse borra por código, igual que 0002_semilla, y falla por PROTECT si algún
# medio ya usa la licencia: retirar una licencia en uso no debe ocurrir en silencio.
from django.db import migrations

LICENCIAS = [
    # (codigo, nombre, url_texto_legal)
    (
        "CC-BY-2.0",
        "Creative Commons Atribución 2.0 Genérica",
        "https://creativecommons.org/licenses/by/2.0/",
    ),
    (
        "CC-BY-2.5",
        "Creative Commons Atribución 2.5 Genérica",
        "https://creativecommons.org/licenses/by/2.5/",
    ),
    (
        "CC-BY-3.0",
        "Creative Commons Atribución 3.0 No adaptada",
        "https://creativecommons.org/licenses/by/3.0/",
    ),
    (
        "CC-BY-SA-2.0",
        "Creative Commons Atribución-CompartirIgual 2.0 Genérica",
        "https://creativecommons.org/licenses/by-sa/2.0/",
    ),
    (
        "CC-BY-SA-2.5",
        "Creative Commons Atribución-CompartirIgual 2.5 Genérica",
        "https://creativecommons.org/licenses/by-sa/2.5/",
    ),
    (
        "CC-BY-SA-3.0",
        "Creative Commons Atribución-CompartirIgual 3.0 No adaptada",
        "https://creativecommons.org/licenses/by-sa/3.0/",
    ),
]


def sembrar(apps, schema_editor):
    Licencia = apps.get_model("catalogos", "Licencia")
    for codigo, nombre, url in LICENCIAS:
        Licencia.objects.get_or_create(
            codigo=codigo,
            defaults={
                "nombre": nombre,
                "url_texto_legal": url,
                "requiere_atribucion": True,
                "compatible_publicacion": True,
            },
        )


def retirar(apps, schema_editor):
    Licencia = apps.get_model("catalogos", "Licencia")
    Licencia.objects.filter(codigo__in=[lic[0] for lic in LICENCIAS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("catalogos", "0003_sin_borrado"),
    ]

    operations = [
        migrations.RunPython(sembrar, reverse_code=retirar),
    ]
