/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { SaludService } from './services/salud.service';
export { PublicoGeneralService } from './services/publico-general.service';
export { PublicoDestinosService } from './services/publico-destinos.service';
export { PublicoItinerariosService } from './services/publico-itinerarios.service';
export { PublicoTiposService } from './services/publico-tipos.service';
export { PublicoGuiasService } from './services/publico-guias.service';
export { PublicoColeccionesService } from './services/publico-colecciones.service';
export { PublicoBusquedaService } from './services/publico-busqueda.service';
export { PublicoGlosarioCreditosService } from './services/publico-glosario-creditos.service';
export { PanelAuthService } from './services/panel-auth.service';
export { PanelTableroService } from './services/panel-tablero.service';
export { PanelContenidosService } from './services/panel-contenidos.service';
export { PanelCicloEditorialService } from './services/panel-ciclo-editorial.service';
export { PanelMediosService } from './services/panel-medios.service';
export { PanelConfiguracionService } from './services/panel-configuracion.service';
export { PanelCuentasService } from './services/panel-cuentas.service';
export { PanelAuditoriaService } from './services/panel-auditoria.service';
