/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CategoriaGuiaPanel } from '../models/categoria-guia-panel';
import { ConfigInicioPanel } from '../models/config-inicio-panel';
import { ConfiguracionSitio } from '../models/configuracion-sitio';
import { EscalasPanel } from '../models/escalas-panel';
import { Licencia } from '../models/licencia';
import { NivelEscalaPanel } from '../models/nivel-escala-panel';
import { PaginaCategoriaGuiaPanel } from '../models/pagina-categoria-guia-panel';
import { PaginaLicencia } from '../models/pagina-licencia';
import { PaginaPais } from '../models/pagina-pais';
import { PaginaRegion } from '../models/pagina-region';
import { Pais } from '../models/pais';
import { panelActualizarCategoriaGuia } from '../fn/panel-configuracion/panel-actualizar-categoria-guia';
import { PanelActualizarCategoriaGuia$Params } from '../fn/panel-configuracion/panel-actualizar-categoria-guia';
import { panelActualizarConfigInicio } from '../fn/panel-configuracion/panel-actualizar-config-inicio';
import { PanelActualizarConfigInicio$Params } from '../fn/panel-configuracion/panel-actualizar-config-inicio';
import { panelActualizarConfiguracionSitio } from '../fn/panel-configuracion/panel-actualizar-configuracion-sitio';
import { PanelActualizarConfiguracionSitio$Params } from '../fn/panel-configuracion/panel-actualizar-configuracion-sitio';
import { panelActualizarLicencia } from '../fn/panel-configuracion/panel-actualizar-licencia';
import { PanelActualizarLicencia$Params } from '../fn/panel-configuracion/panel-actualizar-licencia';
import { panelActualizarNivelEscala } from '../fn/panel-configuracion/panel-actualizar-nivel-escala';
import { PanelActualizarNivelEscala$Params } from '../fn/panel-configuracion/panel-actualizar-nivel-escala';
import { panelActualizarPais } from '../fn/panel-configuracion/panel-actualizar-pais';
import { PanelActualizarPais$Params } from '../fn/panel-configuracion/panel-actualizar-pais';
import { panelActualizarRegion } from '../fn/panel-configuracion/panel-actualizar-region';
import { PanelActualizarRegion$Params } from '../fn/panel-configuracion/panel-actualizar-region';
import { panelCrearCategoriaGuia } from '../fn/panel-configuracion/panel-crear-categoria-guia';
import { PanelCrearCategoriaGuia$Params } from '../fn/panel-configuracion/panel-crear-categoria-guia';
import { panelCrearLicencia } from '../fn/panel-configuracion/panel-crear-licencia';
import { PanelCrearLicencia$Params } from '../fn/panel-configuracion/panel-crear-licencia';
import { panelCrearPais } from '../fn/panel-configuracion/panel-crear-pais';
import { PanelCrearPais$Params } from '../fn/panel-configuracion/panel-crear-pais';
import { panelCrearRegion } from '../fn/panel-configuracion/panel-crear-region';
import { PanelCrearRegion$Params } from '../fn/panel-configuracion/panel-crear-region';
import { panelListarCategoriasGuia } from '../fn/panel-configuracion/panel-listar-categorias-guia';
import { PanelListarCategoriasGuia$Params } from '../fn/panel-configuracion/panel-listar-categorias-guia';
import { panelListarLicencias } from '../fn/panel-configuracion/panel-listar-licencias';
import { PanelListarLicencias$Params } from '../fn/panel-configuracion/panel-listar-licencias';
import { panelListarPaises } from '../fn/panel-configuracion/panel-listar-paises';
import { PanelListarPaises$Params } from '../fn/panel-configuracion/panel-listar-paises';
import { panelListarRegiones } from '../fn/panel-configuracion/panel-listar-regiones';
import { PanelListarRegiones$Params } from '../fn/panel-configuracion/panel-listar-regiones';
import { panelObtenerCategoriaGuia } from '../fn/panel-configuracion/panel-obtener-categoria-guia';
import { PanelObtenerCategoriaGuia$Params } from '../fn/panel-configuracion/panel-obtener-categoria-guia';
import { panelObtenerConfigInicio } from '../fn/panel-configuracion/panel-obtener-config-inicio';
import { PanelObtenerConfigInicio$Params } from '../fn/panel-configuracion/panel-obtener-config-inicio';
import { panelObtenerConfiguracionSitio } from '../fn/panel-configuracion/panel-obtener-configuracion-sitio';
import { PanelObtenerConfiguracionSitio$Params } from '../fn/panel-configuracion/panel-obtener-configuracion-sitio';
import { panelObtenerEscalas } from '../fn/panel-configuracion/panel-obtener-escalas';
import { PanelObtenerEscalas$Params } from '../fn/panel-configuracion/panel-obtener-escalas';
import { panelObtenerLicencia } from '../fn/panel-configuracion/panel-obtener-licencia';
import { PanelObtenerLicencia$Params } from '../fn/panel-configuracion/panel-obtener-licencia';
import { panelObtenerPais } from '../fn/panel-configuracion/panel-obtener-pais';
import { PanelObtenerPais$Params } from '../fn/panel-configuracion/panel-obtener-pais';
import { panelObtenerRegion } from '../fn/panel-configuracion/panel-obtener-region';
import { PanelObtenerRegion$Params } from '../fn/panel-configuracion/panel-obtener-region';
import { Region } from '../models/region';


/**
 * Destacados de inicio, taxonomías, catálogos y configuración del sitio (MOD-012).
 */
@Injectable({ providedIn: 'root' })
export class PanelConfiguracionService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `panelObtenerConfigInicio()` */
  static readonly PanelObtenerConfigInicioPath = '/api/v1/panel/inicio';

  /**
   * Destacados de inicio.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerConfigInicio()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerConfigInicio$Response(params?: PanelObtenerConfigInicio$Params, context?: HttpContext): Promise<StrictHttpResponse<ConfigInicioPanel>> {
    const obs = panelObtenerConfigInicio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Destacados de inicio.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerConfigInicio$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerConfigInicio(params?: PanelObtenerConfigInicio$Params, context?: HttpContext): Promise<ConfigInicioPanel> {
    const resp = this.panelObtenerConfigInicio$Response(params, context);
    return resp.then((r: StrictHttpResponse<ConfigInicioPanel>): ConfigInicioPanel => r.body);
  }

  /** Path part for operation `panelActualizarConfigInicio()` */
  static readonly PanelActualizarConfigInicioPath = '/api/v1/panel/inicio';

  /**
   * Guardar destacados (mínimos 6/3/3; solo contenido PUBLICADO; aplica al instante).
   *
   * Un elemento no publicado o de otro tipo → 422 regla_negocio. Audita CONFIG_INICIO.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelActualizarConfigInicio()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarConfigInicio$Response(params: PanelActualizarConfigInicio$Params, context?: HttpContext): Promise<StrictHttpResponse<ConfigInicioPanel>> {
    const obs = panelActualizarConfigInicio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Guardar destacados (mínimos 6/3/3; solo contenido PUBLICADO; aplica al instante).
   *
   * Un elemento no publicado o de otro tipo → 422 regla_negocio. Audita CONFIG_INICIO.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelActualizarConfigInicio$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarConfigInicio(params: PanelActualizarConfigInicio$Params, context?: HttpContext): Promise<ConfigInicioPanel> {
    const resp = this.panelActualizarConfigInicio$Response(params, context);
    return resp.then((r: StrictHttpResponse<ConfigInicioPanel>): ConfigInicioPanel => r.body);
  }

  /** Path part for operation `panelObtenerConfiguracionSitio()` */
  static readonly PanelObtenerConfiguracionSitioPath = '/api/v1/panel/configuracion';

  /**
   * Configuración del sitio (solo Administrador).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerConfiguracionSitio()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerConfiguracionSitio$Response(params?: PanelObtenerConfiguracionSitio$Params, context?: HttpContext): Promise<StrictHttpResponse<ConfiguracionSitio>> {
    const obs = panelObtenerConfiguracionSitio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Configuración del sitio (solo Administrador).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerConfiguracionSitio$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerConfiguracionSitio(params?: PanelObtenerConfiguracionSitio$Params, context?: HttpContext): Promise<ConfiguracionSitio> {
    const resp = this.panelObtenerConfiguracionSitio$Response(params, context);
    return resp.then((r: StrictHttpResponse<ConfiguracionSitio>): ConfiguracionSitio => r.body);
  }

  /** Path part for operation `panelActualizarConfiguracionSitio()` */
  static readonly PanelActualizarConfiguracionSitioPath = '/api/v1/panel/configuracion';

  /**
   * Guardar configuración del sitio (audita CONFIG_SITIO).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelActualizarConfiguracionSitio()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarConfiguracionSitio$Response(params: PanelActualizarConfiguracionSitio$Params, context?: HttpContext): Promise<StrictHttpResponse<ConfiguracionSitio>> {
    const obs = panelActualizarConfiguracionSitio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Guardar configuración del sitio (audita CONFIG_SITIO).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelActualizarConfiguracionSitio$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarConfiguracionSitio(params: PanelActualizarConfiguracionSitio$Params, context?: HttpContext): Promise<ConfiguracionSitio> {
    const resp = this.panelActualizarConfiguracionSitio$Response(params, context);
    return resp.then((r: StrictHttpResponse<ConfiguracionSitio>): ConfiguracionSitio => r.body);
  }

  /** Path part for operation `panelListarRegiones()` */
  static readonly PanelListarRegionesPath = '/api/v1/panel/taxonomias/regiones';

  /**
   * Regiones.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelListarRegiones()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarRegiones$Response(params?: PanelListarRegiones$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaRegion>> {
    const obs = panelListarRegiones(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Regiones.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelListarRegiones$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarRegiones(params?: PanelListarRegiones$Params, context?: HttpContext): Promise<PaginaRegion> {
    const resp = this.panelListarRegiones$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaRegion>): PaginaRegion => r.body);
  }

  /** Path part for operation `panelCrearRegion()` */
  static readonly PanelCrearRegionPath = '/api/v1/panel/taxonomias/regiones';

  /**
   * Crear región.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelCrearRegion()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCrearRegion$Response(params: PanelCrearRegion$Params, context?: HttpContext): Promise<StrictHttpResponse<Region>> {
    const obs = panelCrearRegion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear región.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelCrearRegion$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCrearRegion(params: PanelCrearRegion$Params, context?: HttpContext): Promise<Region> {
    const resp = this.panelCrearRegion$Response(params, context);
    return resp.then((r: StrictHttpResponse<Region>): Region => r.body);
  }

  /** Path part for operation `panelObtenerRegion()` */
  static readonly PanelObtenerRegionPath = '/api/v1/panel/taxonomias/regiones/{id}';

  /**
   * Obtener región.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerRegion()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerRegion$Response(params: PanelObtenerRegion$Params, context?: HttpContext): Promise<StrictHttpResponse<Region>> {
    const obs = panelObtenerRegion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener región.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerRegion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerRegion(params: PanelObtenerRegion$Params, context?: HttpContext): Promise<Region> {
    const resp = this.panelObtenerRegion$Response(params, context);
    return resp.then((r: StrictHttpResponse<Region>): Region => r.body);
  }

  /** Path part for operation `panelActualizarRegion()` */
  static readonly PanelActualizarRegionPath = '/api/v1/panel/taxonomias/regiones/{id}';

  /**
   * Editar o desactivar región.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelActualizarRegion()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarRegion$Response(params: PanelActualizarRegion$Params, context?: HttpContext): Promise<StrictHttpResponse<Region>> {
    const obs = panelActualizarRegion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Editar o desactivar región.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelActualizarRegion$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarRegion(params: PanelActualizarRegion$Params, context?: HttpContext): Promise<Region> {
    const resp = this.panelActualizarRegion$Response(params, context);
    return resp.then((r: StrictHttpResponse<Region>): Region => r.body);
  }

  /** Path part for operation `panelListarPaises()` */
  static readonly PanelListarPaisesPath = '/api/v1/panel/taxonomias/paises';

  /**
   * Países.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelListarPaises()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarPaises$Response(params?: PanelListarPaises$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaPais>> {
    const obs = panelListarPaises(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Países.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelListarPaises$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarPaises(params?: PanelListarPaises$Params, context?: HttpContext): Promise<PaginaPais> {
    const resp = this.panelListarPaises$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaPais>): PaginaPais => r.body);
  }

  /** Path part for operation `panelCrearPais()` */
  static readonly PanelCrearPaisPath = '/api/v1/panel/taxonomias/paises';

  /**
   * Crear país.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelCrearPais()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCrearPais$Response(params: PanelCrearPais$Params, context?: HttpContext): Promise<StrictHttpResponse<Pais>> {
    const obs = panelCrearPais(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear país.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelCrearPais$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCrearPais(params: PanelCrearPais$Params, context?: HttpContext): Promise<Pais> {
    const resp = this.panelCrearPais$Response(params, context);
    return resp.then((r: StrictHttpResponse<Pais>): Pais => r.body);
  }

  /** Path part for operation `panelObtenerPais()` */
  static readonly PanelObtenerPaisPath = '/api/v1/panel/taxonomias/paises/{id}';

  /**
   * Obtener país.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerPais()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerPais$Response(params: PanelObtenerPais$Params, context?: HttpContext): Promise<StrictHttpResponse<Pais>> {
    const obs = panelObtenerPais(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener país.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerPais$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerPais(params: PanelObtenerPais$Params, context?: HttpContext): Promise<Pais> {
    const resp = this.panelObtenerPais$Response(params, context);
    return resp.then((r: StrictHttpResponse<Pais>): Pais => r.body);
  }

  /** Path part for operation `panelActualizarPais()` */
  static readonly PanelActualizarPaisPath = '/api/v1/panel/taxonomias/paises/{id}';

  /**
   * Editar o desactivar país.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelActualizarPais()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarPais$Response(params: PanelActualizarPais$Params, context?: HttpContext): Promise<StrictHttpResponse<Pais>> {
    const obs = panelActualizarPais(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Editar o desactivar país.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelActualizarPais$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarPais(params: PanelActualizarPais$Params, context?: HttpContext): Promise<Pais> {
    const resp = this.panelActualizarPais$Response(params, context);
    return resp.then((r: StrictHttpResponse<Pais>): Pais => r.body);
  }

  /** Path part for operation `panelListarCategoriasGuia()` */
  static readonly PanelListarCategoriasGuiaPath = '/api/v1/panel/taxonomias/categorias-guia';

  /**
   * Categorías de guía.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelListarCategoriasGuia()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarCategoriasGuia$Response(params?: PanelListarCategoriasGuia$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaCategoriaGuiaPanel>> {
    const obs = panelListarCategoriasGuia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Categorías de guía.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelListarCategoriasGuia$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarCategoriasGuia(params?: PanelListarCategoriasGuia$Params, context?: HttpContext): Promise<PaginaCategoriaGuiaPanel> {
    const resp = this.panelListarCategoriasGuia$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaCategoriaGuiaPanel>): PaginaCategoriaGuiaPanel => r.body);
  }

  /** Path part for operation `panelCrearCategoriaGuia()` */
  static readonly PanelCrearCategoriaGuiaPath = '/api/v1/panel/taxonomias/categorias-guia';

  /**
   * Crear categoría de guía.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelCrearCategoriaGuia()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCrearCategoriaGuia$Response(params: PanelCrearCategoriaGuia$Params, context?: HttpContext): Promise<StrictHttpResponse<CategoriaGuiaPanel>> {
    const obs = panelCrearCategoriaGuia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear categoría de guía.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelCrearCategoriaGuia$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCrearCategoriaGuia(params: PanelCrearCategoriaGuia$Params, context?: HttpContext): Promise<CategoriaGuiaPanel> {
    const resp = this.panelCrearCategoriaGuia$Response(params, context);
    return resp.then((r: StrictHttpResponse<CategoriaGuiaPanel>): CategoriaGuiaPanel => r.body);
  }

  /** Path part for operation `panelObtenerCategoriaGuia()` */
  static readonly PanelObtenerCategoriaGuiaPath = '/api/v1/panel/taxonomias/categorias-guia/{id}';

  /**
   * Obtener categoría de guía.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerCategoriaGuia()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerCategoriaGuia$Response(params: PanelObtenerCategoriaGuia$Params, context?: HttpContext): Promise<StrictHttpResponse<CategoriaGuiaPanel>> {
    const obs = panelObtenerCategoriaGuia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener categoría de guía.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerCategoriaGuia$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerCategoriaGuia(params: PanelObtenerCategoriaGuia$Params, context?: HttpContext): Promise<CategoriaGuiaPanel> {
    const resp = this.panelObtenerCategoriaGuia$Response(params, context);
    return resp.then((r: StrictHttpResponse<CategoriaGuiaPanel>): CategoriaGuiaPanel => r.body);
  }

  /** Path part for operation `panelActualizarCategoriaGuia()` */
  static readonly PanelActualizarCategoriaGuiaPath = '/api/v1/panel/taxonomias/categorias-guia/{id}';

  /**
   * Editar o desactivar categoría de guía.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelActualizarCategoriaGuia()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarCategoriaGuia$Response(params: PanelActualizarCategoriaGuia$Params, context?: HttpContext): Promise<StrictHttpResponse<CategoriaGuiaPanel>> {
    const obs = panelActualizarCategoriaGuia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Editar o desactivar categoría de guía.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelActualizarCategoriaGuia$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarCategoriaGuia(params: PanelActualizarCategoriaGuia$Params, context?: HttpContext): Promise<CategoriaGuiaPanel> {
    const resp = this.panelActualizarCategoriaGuia$Response(params, context);
    return resp.then((r: StrictHttpResponse<CategoriaGuiaPanel>): CategoriaGuiaPanel => r.body);
  }

  /** Path part for operation `panelListarLicencias()` */
  static readonly PanelListarLicenciasPath = '/api/v1/panel/taxonomias/licencias';

  /**
   * Licencias (Editor en solo lectura).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelListarLicencias()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarLicencias$Response(params?: PanelListarLicencias$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaLicencia>> {
    const obs = panelListarLicencias(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Licencias (Editor en solo lectura).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelListarLicencias$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarLicencias(params?: PanelListarLicencias$Params, context?: HttpContext): Promise<PaginaLicencia> {
    const resp = this.panelListarLicencias$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaLicencia>): PaginaLicencia => r.body);
  }

  /** Path part for operation `panelCrearLicencia()` */
  static readonly PanelCrearLicenciaPath = '/api/v1/panel/taxonomias/licencias';

  /**
   * Crear licencia (solo Administrador).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelCrearLicencia()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCrearLicencia$Response(params: PanelCrearLicencia$Params, context?: HttpContext): Promise<StrictHttpResponse<Licencia>> {
    const obs = panelCrearLicencia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Crear licencia (solo Administrador).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelCrearLicencia$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCrearLicencia(params: PanelCrearLicencia$Params, context?: HttpContext): Promise<Licencia> {
    const resp = this.panelCrearLicencia$Response(params, context);
    return resp.then((r: StrictHttpResponse<Licencia>): Licencia => r.body);
  }

  /** Path part for operation `panelObtenerLicencia()` */
  static readonly PanelObtenerLicenciaPath = '/api/v1/panel/taxonomias/licencias/{id}';

  /**
   * Obtener licencia.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerLicencia()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerLicencia$Response(params: PanelObtenerLicencia$Params, context?: HttpContext): Promise<StrictHttpResponse<Licencia>> {
    const obs = panelObtenerLicencia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener licencia.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerLicencia$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerLicencia(params: PanelObtenerLicencia$Params, context?: HttpContext): Promise<Licencia> {
    const resp = this.panelObtenerLicencia$Response(params, context);
    return resp.then((r: StrictHttpResponse<Licencia>): Licencia => r.body);
  }

  /** Path part for operation `panelActualizarLicencia()` */
  static readonly PanelActualizarLicenciaPath = '/api/v1/panel/taxonomias/licencias/{id}';

  /**
   * Editar o desactivar licencia (solo Administrador).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelActualizarLicencia()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarLicencia$Response(params: PanelActualizarLicencia$Params, context?: HttpContext): Promise<StrictHttpResponse<Licencia>> {
    const obs = panelActualizarLicencia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Editar o desactivar licencia (solo Administrador).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelActualizarLicencia$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarLicencia(params: PanelActualizarLicencia$Params, context?: HttpContext): Promise<Licencia> {
    const resp = this.panelActualizarLicencia$Response(params, context);
    return resp.then((r: StrictHttpResponse<Licencia>): Licencia => r.body);
  }

  /** Path part for operation `panelObtenerEscalas()` */
  static readonly PanelObtenerEscalasPath = '/api/v1/panel/taxonomias/escalas';

  /**
   * Niveles de las escalas (Editor en solo lectura; colección fija de 9).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerEscalas()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerEscalas$Response(params?: PanelObtenerEscalas$Params, context?: HttpContext): Promise<StrictHttpResponse<EscalasPanel>> {
    const obs = panelObtenerEscalas(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Niveles de las escalas (Editor en solo lectura; colección fija de 9).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerEscalas$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerEscalas(params?: PanelObtenerEscalas$Params, context?: HttpContext): Promise<EscalasPanel> {
    const resp = this.panelObtenerEscalas$Response(params, context);
    return resp.then((r: StrictHttpResponse<EscalasPanel>): EscalasPanel => r.body);
  }

  /** Path part for operation `panelActualizarNivelEscala()` */
  static readonly PanelActualizarNivelEscalaPath = '/api/v1/panel/taxonomias/escalas/{id}';

  /**
   * Editar etiqueta y descripción de un nivel (solo Administrador; los niveles son fijos).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelActualizarNivelEscala()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarNivelEscala$Response(params: PanelActualizarNivelEscala$Params, context?: HttpContext): Promise<StrictHttpResponse<NivelEscalaPanel>> {
    const obs = panelActualizarNivelEscala(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Editar etiqueta y descripción de un nivel (solo Administrador; los niveles son fijos).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelActualizarNivelEscala$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarNivelEscala(params: PanelActualizarNivelEscala$Params, context?: HttpContext): Promise<NivelEscalaPanel> {
    const resp = this.panelActualizarNivelEscala$Response(params, context);
    return resp.then((r: StrictHttpResponse<NivelEscalaPanel>): NivelEscalaPanel => r.body);
  }

}
