/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaginaEventoAuditoria } from '../models/pagina-evento-auditoria';
import { panelListarAuditoria } from '../fn/panel-auditoria/panel-listar-auditoria';
import { PanelListarAuditoria$Params } from '../fn/panel-auditoria/panel-listar-auditoria';


/**
 * Consulta de auditoría (solo Administrador, solo lectura).
 */
@Injectable({ providedIn: 'root' })
export class PanelAuditoriaService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `panelListarAuditoria()` */
  static readonly PanelListarAuditoriaPath = '/api/v1/panel/auditoria';

  /**
   * Registro de auditoría filtrado (ocurrido_en descendente, 50 por página).
   *
   * No existe ninguna operación de modificación o borrado (cualquier otro método → 405). Solo la purga automática a los 365 días (THREAT-013).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelListarAuditoria()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarAuditoria$Response(params?: PanelListarAuditoria$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaEventoAuditoria>> {
    const obs = panelListarAuditoria(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Registro de auditoría filtrado (ocurrido_en descendente, 50 por página).
   *
   * No existe ninguna operación de modificación o borrado (cualquier otro método → 405). Solo la purga automática a los 365 días (THREAT-013).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelListarAuditoria$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarAuditoria(params?: PanelListarAuditoria$Params, context?: HttpContext): Promise<PaginaEventoAuditoria> {
    const resp = this.panelListarAuditoria$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaEventoAuditoria>): PaginaEventoAuditoria => r.body);
  }

}
