/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { MedioPanel } from '../models/medio-panel';
import { PaginaMedioPanel } from '../models/pagina-medio-panel';
import { PaginaUsoMedio } from '../models/pagina-uso-medio';
import { panelCatalogarMedio } from '../fn/panel-medios/panel-catalogar-medio';
import { PanelCatalogarMedio$Params } from '../fn/panel-medios/panel-catalogar-medio';
import { panelListarMedios } from '../fn/panel-medios/panel-listar-medios';
import { PanelListarMedios$Params } from '../fn/panel-medios/panel-listar-medios';
import { panelListarUsosMedio } from '../fn/panel-medios/panel-listar-usos-medio';
import { PanelListarUsosMedio$Params } from '../fn/panel-medios/panel-listar-usos-medio';
import { panelObtenerArchivoMedio$Avif } from '../fn/panel-medios/panel-obtener-archivo-medio-avif';
import { PanelObtenerArchivoMedio$Avif$Params } from '../fn/panel-medios/panel-obtener-archivo-medio-avif';
import { panelObtenerArchivoMedio$Jpeg } from '../fn/panel-medios/panel-obtener-archivo-medio-jpeg';
import { PanelObtenerArchivoMedio$Jpeg$Params } from '../fn/panel-medios/panel-obtener-archivo-medio-jpeg';
import { panelObtenerArchivoMedio$Webp } from '../fn/panel-medios/panel-obtener-archivo-medio-webp';
import { PanelObtenerArchivoMedio$Webp$Params } from '../fn/panel-medios/panel-obtener-archivo-medio-webp';
import { panelObtenerMedio } from '../fn/panel-medios/panel-obtener-medio';
import { PanelObtenerMedio$Params } from '../fn/panel-medios/panel-obtener-medio';
import { panelReactivarMedio } from '../fn/panel-medios/panel-reactivar-medio';
import { PanelReactivarMedio$Params } from '../fn/panel-medios/panel-reactivar-medio';
import { panelRetirarMedio } from '../fn/panel-medios/panel-retirar-medio';
import { PanelRetirarMedio$Params } from '../fn/panel-medios/panel-retirar-medio';
import { panelSubirMedios } from '../fn/panel-medios/panel-subir-medios';
import { PanelSubirMedios$Params } from '../fn/panel-medios/panel-subir-medios';
import { ResultadoSubida } from '../models/resultado-subida';


/**
 * Subida y catalogación de medios (MOD-011, DEC-AUTO-044).
 */
@Injectable({ providedIn: 'root' })
export class PanelMediosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `panelListarMedios()` */
  static readonly PanelListarMediosPath = '/api/v1/panel/medios';

  /**
   * Biblioteca de medios (48 por página).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelListarMedios()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarMedios$Response(params?: PanelListarMedios$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaMedioPanel>> {
    const obs = panelListarMedios(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Biblioteca de medios (48 por página).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelListarMedios$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarMedios(params?: PanelListarMedios$Params, context?: HttpContext): Promise<PaginaMedioPanel> {
    const resp = this.panelListarMedios$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaMedioPanel>): PaginaMedioPanel => r.body);
  }

  /** Path part for operation `panelSubirMedios()` */
  static readonly PanelSubirMediosPath = '/api/v1/panel/medios';

  /**
   * Subir 1..10 imágenes (resultado por archivo).
   *
   * Procesamiento síncrono (sin broker, ADR-DB-005). Por archivo: verificación del tipo por contenido (JPEG, PNG o WebP; nunca SVG), ≤10 MB, lado mayor ≥1200 px, ≤40 MP comprobados antes de decodificar por completo, re-codificación que elimina EXIF/XMP/IPTC, derivados responsivos (AVIF, WebP, JPEG), huella SHA-256 para duplicados y nombres de archivo generados por el sistema, almacenados fuera de rutas ejecutables. Un archivo rechazado no se almacena. Respuesta 200 aunque todos se rechacen (el detalle va en cada `resultado`). Petición con 0 o más de 10 archivos: 400. Petición >105 MB: 413. Audita SUBIR_MEDIO por archivo aceptado.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelSubirMedios()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  panelSubirMedios$Response(params: PanelSubirMedios$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoSubida>> {
    const obs = panelSubirMedios(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Subir 1..10 imágenes (resultado por archivo).
   *
   * Procesamiento síncrono (sin broker, ADR-DB-005). Por archivo: verificación del tipo por contenido (JPEG, PNG o WebP; nunca SVG), ≤10 MB, lado mayor ≥1200 px, ≤40 MP comprobados antes de decodificar por completo, re-codificación que elimina EXIF/XMP/IPTC, derivados responsivos (AVIF, WebP, JPEG), huella SHA-256 para duplicados y nombres de archivo generados por el sistema, almacenados fuera de rutas ejecutables. Un archivo rechazado no se almacena. Respuesta 200 aunque todos se rechacen (el detalle va en cada `resultado`). Petición con 0 o más de 10 archivos: 400. Petición >105 MB: 413. Audita SUBIR_MEDIO por archivo aceptado.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelSubirMedios$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  panelSubirMedios(params: PanelSubirMedios$Params, context?: HttpContext): Promise<ResultadoSubida> {
    const resp = this.panelSubirMedios$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoSubida>): ResultadoSubida => r.body);
  }

  /** Path part for operation `panelObtenerMedio()` */
  static readonly PanelObtenerMedioPath = '/api/v1/panel/medios/{id}';

  /**
   * Detalle de medio.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerMedio()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerMedio$Response(params: PanelObtenerMedio$Params, context?: HttpContext): Promise<StrictHttpResponse<MedioPanel>> {
    const obs = panelObtenerMedio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Detalle de medio.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerMedio$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerMedio(params: PanelObtenerMedio$Params, context?: HttpContext): Promise<MedioPanel> {
    const resp = this.panelObtenerMedio$Response(params, context);
    return resp.then((r: StrictHttpResponse<MedioPanel>): MedioPanel => r.body);
  }

  /** Path part for operation `panelCatalogarMedio()` */
  static readonly PanelCatalogarMedioPath = '/api/v1/panel/medios/{id}';

  /**
   * Catalogar medio (alt, pie, crédito, fuente, licencia).
   *
   * Con alt, crédito y una licencia compatible, PENDIENTE_METADATOS pasa a DISPONIBLE (RULE-005). Con licencia incompatible sigue pendiente y `pendientes_catalogacion` lo indica. Asignar una licencia incompatible a un medio en uso por contenido publicado: 422 regla_negocio. `fuente_url` es solo texto: nunca se descarga (THREAT-022). Audita EDITAR_MEDIO.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelCatalogarMedio()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCatalogarMedio$Response(params: PanelCatalogarMedio$Params, context?: HttpContext): Promise<StrictHttpResponse<MedioPanel>> {
    const obs = panelCatalogarMedio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Catalogar medio (alt, pie, crédito, fuente, licencia).
   *
   * Con alt, crédito y una licencia compatible, PENDIENTE_METADATOS pasa a DISPONIBLE (RULE-005). Con licencia incompatible sigue pendiente y `pendientes_catalogacion` lo indica. Asignar una licencia incompatible a un medio en uso por contenido publicado: 422 regla_negocio. `fuente_url` es solo texto: nunca se descarga (THREAT-022). Audita EDITAR_MEDIO.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelCatalogarMedio$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCatalogarMedio(params: PanelCatalogarMedio$Params, context?: HttpContext): Promise<MedioPanel> {
    const resp = this.panelCatalogarMedio$Response(params, context);
    return resp.then((r: StrictHttpResponse<MedioPanel>): MedioPanel => r.body);
  }

  /** Path part for operation `panelObtenerArchivoMedio()` */
  static readonly PanelObtenerArchivoMedioPath = '/api/v1/panel/medios/{id}/archivo';

  /**
   * Derivado de un medio para el panel (también no DISPONIBLES).
   *
   * Único canal para ver medios no públicos. Tipo explícito y `nosniff`. Los derivados de medios DISPONIBLES se sirven al público como estáticos (DEC-AUTO-110).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerArchivoMedio$Avif()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerArchivoMedio$Avif$Response(params: PanelObtenerArchivoMedio$Avif$Params, context?: HttpContext): Promise<StrictHttpResponse<Blob>> {
    const obs = panelObtenerArchivoMedio$Avif(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Derivado de un medio para el panel (también no DISPONIBLES).
   *
   * Único canal para ver medios no públicos. Tipo explícito y `nosniff`. Los derivados de medios DISPONIBLES se sirven al público como estáticos (DEC-AUTO-110).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerArchivoMedio$Avif$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerArchivoMedio$Avif(params: PanelObtenerArchivoMedio$Avif$Params, context?: HttpContext): Promise<Blob> {
    const resp = this.panelObtenerArchivoMedio$Avif$Response(params, context);
    return resp.then((r: StrictHttpResponse<Blob>): Blob => r.body);
  }

  /**
   * Derivado de un medio para el panel (también no DISPONIBLES).
   *
   * Único canal para ver medios no públicos. Tipo explícito y `nosniff`. Los derivados de medios DISPONIBLES se sirven al público como estáticos (DEC-AUTO-110).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerArchivoMedio$Webp()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerArchivoMedio$Webp$Response(params: PanelObtenerArchivoMedio$Webp$Params, context?: HttpContext): Promise<StrictHttpResponse<Blob>> {
    const obs = panelObtenerArchivoMedio$Webp(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Derivado de un medio para el panel (también no DISPONIBLES).
   *
   * Único canal para ver medios no públicos. Tipo explícito y `nosniff`. Los derivados de medios DISPONIBLES se sirven al público como estáticos (DEC-AUTO-110).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerArchivoMedio$Webp$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerArchivoMedio$Webp(params: PanelObtenerArchivoMedio$Webp$Params, context?: HttpContext): Promise<Blob> {
    const resp = this.panelObtenerArchivoMedio$Webp$Response(params, context);
    return resp.then((r: StrictHttpResponse<Blob>): Blob => r.body);
  }

  /**
   * Derivado de un medio para el panel (también no DISPONIBLES).
   *
   * Único canal para ver medios no públicos. Tipo explícito y `nosniff`. Los derivados de medios DISPONIBLES se sirven al público como estáticos (DEC-AUTO-110).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerArchivoMedio$Jpeg()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerArchivoMedio$Jpeg$Response(params: PanelObtenerArchivoMedio$Jpeg$Params, context?: HttpContext): Promise<StrictHttpResponse<Blob>> {
    const obs = panelObtenerArchivoMedio$Jpeg(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Derivado de un medio para el panel (también no DISPONIBLES).
   *
   * Único canal para ver medios no públicos. Tipo explícito y `nosniff`. Los derivados de medios DISPONIBLES se sirven al público como estáticos (DEC-AUTO-110).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerArchivoMedio$Jpeg$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerArchivoMedio$Jpeg(params: PanelObtenerArchivoMedio$Jpeg$Params, context?: HttpContext): Promise<Blob> {
    const resp = this.panelObtenerArchivoMedio$Jpeg$Response(params, context);
    return resp.then((r: StrictHttpResponse<Blob>): Blob => r.body);
  }

  /** Path part for operation `panelListarUsosMedio()` */
  static readonly PanelListarUsosMedioPath = '/api/v1/panel/medios/{id}/usos';

  /**
   * Contenidos donde se usa el medio.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelListarUsosMedio()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarUsosMedio$Response(params: PanelListarUsosMedio$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaUsoMedio>> {
    const obs = panelListarUsosMedio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Contenidos donde se usa el medio.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelListarUsosMedio$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarUsosMedio(params: PanelListarUsosMedio$Params, context?: HttpContext): Promise<PaginaUsoMedio> {
    const resp = this.panelListarUsosMedio$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaUsoMedio>): PaginaUsoMedio => r.body);
  }

  /** Path part for operation `panelRetirarMedio()` */
  static readonly PanelRetirarMedioPath = '/api/v1/panel/medios/{id}/retirar';

  /**
   * Retirar medio (409 medio_en_uso con la lista de usos si lo usa contenido publicado).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelRetirarMedio()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelRetirarMedio$Response(params: PanelRetirarMedio$Params, context?: HttpContext): Promise<StrictHttpResponse<MedioPanel>> {
    const obs = panelRetirarMedio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Retirar medio (409 medio_en_uso con la lista de usos si lo usa contenido publicado).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelRetirarMedio$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelRetirarMedio(params: PanelRetirarMedio$Params, context?: HttpContext): Promise<MedioPanel> {
    const resp = this.panelRetirarMedio$Response(params, context);
    return resp.then((r: StrictHttpResponse<MedioPanel>): MedioPanel => r.body);
  }

  /** Path part for operation `panelReactivarMedio()` */
  static readonly PanelReactivarMedioPath = '/api/v1/panel/medios/{id}/reactivar';

  /**
   * RETIRADO → PENDIENTE_METADATOS.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelReactivarMedio()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelReactivarMedio$Response(params: PanelReactivarMedio$Params, context?: HttpContext): Promise<StrictHttpResponse<MedioPanel>> {
    const obs = panelReactivarMedio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * RETIRADO → PENDIENTE_METADATOS.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelReactivarMedio$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelReactivarMedio(params: PanelReactivarMedio$Params, context?: HttpContext): Promise<MedioPanel> {
    const resp = this.panelReactivarMedio$Response(params, context);
    return resp.then((r: StrictHttpResponse<MedioPanel>): MedioPanel => r.body);
  }

}
