/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Cuenta } from '../models/cuenta';
import { CuentaConCredencialTemporal } from '../models/cuenta-con-credencial-temporal';
import { PaginaCuenta } from '../models/pagina-cuenta';
import { panelActualizarCuenta } from '../fn/panel-cuentas/panel-actualizar-cuenta';
import { PanelActualizarCuenta$Params } from '../fn/panel-cuentas/panel-actualizar-cuenta';
import { panelAnonimizarCuenta } from '../fn/panel-cuentas/panel-anonimizar-cuenta';
import { PanelAnonimizarCuenta$Params } from '../fn/panel-cuentas/panel-anonimizar-cuenta';
import { panelCrearCuenta } from '../fn/panel-cuentas/panel-crear-cuenta';
import { PanelCrearCuenta$Params } from '../fn/panel-cuentas/panel-crear-cuenta';
import { panelDesactivarCuenta } from '../fn/panel-cuentas/panel-desactivar-cuenta';
import { PanelDesactivarCuenta$Params } from '../fn/panel-cuentas/panel-desactivar-cuenta';
import { panelListarCuentas } from '../fn/panel-cuentas/panel-listar-cuentas';
import { PanelListarCuentas$Params } from '../fn/panel-cuentas/panel-listar-cuentas';
import { panelObtenerCuenta } from '../fn/panel-cuentas/panel-obtener-cuenta';
import { PanelObtenerCuenta$Params } from '../fn/panel-cuentas/panel-obtener-cuenta';
import { panelReactivarCuenta } from '../fn/panel-cuentas/panel-reactivar-cuenta';
import { PanelReactivarCuenta$Params } from '../fn/panel-cuentas/panel-reactivar-cuenta';
import { panelRestablecerContrasenaCuenta } from '../fn/panel-cuentas/panel-restablecer-contrasena-cuenta';
import { PanelRestablecerContrasenaCuenta$Params } from '../fn/panel-cuentas/panel-restablecer-contrasena-cuenta';
import { panelRestablecerMfaCuenta } from '../fn/panel-cuentas/panel-restablecer-mfa-cuenta';
import { PanelRestablecerMfaCuenta$Params } from '../fn/panel-cuentas/panel-restablecer-mfa-cuenta';


/**
 * Cuentas del staff (solo Administrador, MOD-013).
 */
@Injectable({ providedIn: 'root' })
export class PanelCuentasService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `panelListarCuentas()` */
  static readonly PanelListarCuentasPath = '/api/v1/panel/cuentas';

  /**
   * Cuentas del equipo.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelListarCuentas()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarCuentas$Response(params?: PanelListarCuentas$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaCuenta>> {
    const obs = panelListarCuentas(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Cuentas del equipo.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelListarCuentas$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarCuentas(params?: PanelListarCuentas$Params, context?: HttpContext): Promise<PaginaCuenta> {
    const resp = this.panelListarCuentas$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaCuenta>): PaginaCuenta => r.body);
  }

  /** Path part for operation `panelCrearCuenta()` */
  static readonly PanelCrearCuentaPath = '/api/v1/panel/cuentas';

  /**
   * Alta de cuenta con contraseña temporal (se devuelve una sola vez).
   *
   * Estado inicial PENDIENTE_ACTIVACION. Usuario duplicado → 409 duplicado. Audita CUENTA_CREAR (sin valores secretos). Idempotencia (DEC-AUTO-129; caso general en el parámetro IdempotencyKey, CHG-API-002): la respuesta no se persiste nunca (AC-106). Repetir con una Idempotency-Key ya completada y la misma huella → 409 idempotencia_respuesta_no_reproducible con cabecera Location de la cuenta creada; el Administrador emite otra contraseña con POST /api/v1/panel/cuentas/{id}/restablecer-contrasena.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelCrearCuenta()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCrearCuenta$Response(params: PanelCrearCuenta$Params, context?: HttpContext): Promise<StrictHttpResponse<CuentaConCredencialTemporal>> {
    const obs = panelCrearCuenta(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Alta de cuenta con contraseña temporal (se devuelve una sola vez).
   *
   * Estado inicial PENDIENTE_ACTIVACION. Usuario duplicado → 409 duplicado. Audita CUENTA_CREAR (sin valores secretos). Idempotencia (DEC-AUTO-129; caso general en el parámetro IdempotencyKey, CHG-API-002): la respuesta no se persiste nunca (AC-106). Repetir con una Idempotency-Key ya completada y la misma huella → 409 idempotencia_respuesta_no_reproducible con cabecera Location de la cuenta creada; el Administrador emite otra contraseña con POST /api/v1/panel/cuentas/{id}/restablecer-contrasena.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelCrearCuenta$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCrearCuenta(params: PanelCrearCuenta$Params, context?: HttpContext): Promise<CuentaConCredencialTemporal> {
    const resp = this.panelCrearCuenta$Response(params, context);
    return resp.then((r: StrictHttpResponse<CuentaConCredencialTemporal>): CuentaConCredencialTemporal => r.body);
  }

  /** Path part for operation `panelObtenerCuenta()` */
  static readonly PanelObtenerCuentaPath = '/api/v1/panel/cuentas/{id}';

  /**
   * Obtener cuenta.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerCuenta()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerCuenta$Response(params: PanelObtenerCuenta$Params, context?: HttpContext): Promise<StrictHttpResponse<Cuenta>> {
    const obs = panelObtenerCuenta(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Obtener cuenta.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerCuenta$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerCuenta(params: PanelObtenerCuenta$Params, context?: HttpContext): Promise<Cuenta> {
    const resp = this.panelObtenerCuenta$Response(params, context);
    return resp.then((r: StrictHttpResponse<Cuenta>): Cuenta => r.body);
  }

  /** Path part for operation `panelActualizarCuenta()` */
  static readonly PanelActualizarCuentaPath = '/api/v1/panel/cuentas/{id}';

  /**
   * Cambiar nombre visible o rol.
   *
   * Degradar al último Administrador activo o a uno mismo: 409 ultimo_administrador / operacion_sobre_si_mismo (RULE-015, AC-108). Un cambio de rol invalida las sesiones de la cuenta afectada (THREAT-002). Audita CUENTA_ROL.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelActualizarCuenta()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarCuenta$Response(params: PanelActualizarCuenta$Params, context?: HttpContext): Promise<StrictHttpResponse<Cuenta>> {
    const obs = panelActualizarCuenta(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Cambiar nombre visible o rol.
   *
   * Degradar al último Administrador activo o a uno mismo: 409 ultimo_administrador / operacion_sobre_si_mismo (RULE-015, AC-108). Un cambio de rol invalida las sesiones de la cuenta afectada (THREAT-002). Audita CUENTA_ROL.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelActualizarCuenta$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelActualizarCuenta(params: PanelActualizarCuenta$Params, context?: HttpContext): Promise<Cuenta> {
    const resp = this.panelActualizarCuenta$Response(params, context);
    return resp.then((r: StrictHttpResponse<Cuenta>): Cuenta => r.body);
  }

  /** Path part for operation `panelRestablecerContrasenaCuenta()` */
  static readonly PanelRestablecerContrasenaCuentaPath = '/api/v1/panel/cuentas/{id}/restablecer-contrasena';

  /**
   * Nueva contraseña temporal; invalida sesiones; PENDIENTE_ACTIVACION.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelRestablecerContrasenaCuenta()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelRestablecerContrasenaCuenta$Response(params: PanelRestablecerContrasenaCuenta$Params, context?: HttpContext): Promise<StrictHttpResponse<CuentaConCredencialTemporal>> {
    const obs = panelRestablecerContrasenaCuenta(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Nueva contraseña temporal; invalida sesiones; PENDIENTE_ACTIVACION.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelRestablecerContrasenaCuenta$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelRestablecerContrasenaCuenta(params: PanelRestablecerContrasenaCuenta$Params, context?: HttpContext): Promise<CuentaConCredencialTemporal> {
    const resp = this.panelRestablecerContrasenaCuenta$Response(params, context);
    return resp.then((r: StrictHttpResponse<CuentaConCredencialTemporal>): CuentaConCredencialTemporal => r.body);
  }

  /** Path part for operation `panelRestablecerMfaCuenta()` */
  static readonly PanelRestablecerMfaCuentaPath = '/api/v1/panel/cuentas/{id}/restablecer-mfa';

  /**
   * Elimina el MFA y emite contraseña temporal; invalida sesiones; PENDIENTE_ACTIVACION.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelRestablecerMfaCuenta()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelRestablecerMfaCuenta$Response(params: PanelRestablecerMfaCuenta$Params, context?: HttpContext): Promise<StrictHttpResponse<CuentaConCredencialTemporal>> {
    const obs = panelRestablecerMfaCuenta(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Elimina el MFA y emite contraseña temporal; invalida sesiones; PENDIENTE_ACTIVACION.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelRestablecerMfaCuenta$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelRestablecerMfaCuenta(params: PanelRestablecerMfaCuenta$Params, context?: HttpContext): Promise<CuentaConCredencialTemporal> {
    const resp = this.panelRestablecerMfaCuenta$Response(params, context);
    return resp.then((r: StrictHttpResponse<CuentaConCredencialTemporal>): CuentaConCredencialTemporal => r.body);
  }

  /** Path part for operation `panelDesactivarCuenta()` */
  static readonly PanelDesactivarCuentaPath = '/api/v1/panel/cuentas/{id}/desactivar';

  /**
   * Desactivar (invalida sesiones y credenciales de inmediato).
   *
   * Último Administrador activo o la propia cuenta → 409 (RULE-015, AC-108). Audita CUENTA_DESACTIVAR.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelDesactivarCuenta()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelDesactivarCuenta$Response(params: PanelDesactivarCuenta$Params, context?: HttpContext): Promise<StrictHttpResponse<Cuenta>> {
    const obs = panelDesactivarCuenta(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Desactivar (invalida sesiones y credenciales de inmediato).
   *
   * Último Administrador activo o la propia cuenta → 409 (RULE-015, AC-108). Audita CUENTA_DESACTIVAR.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelDesactivarCuenta$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelDesactivarCuenta(params: PanelDesactivarCuenta$Params, context?: HttpContext): Promise<Cuenta> {
    const resp = this.panelDesactivarCuenta$Response(params, context);
    return resp.then((r: StrictHttpResponse<Cuenta>): Cuenta => r.body);
  }

  /** Path part for operation `panelReactivarCuenta()` */
  static readonly PanelReactivarCuentaPath = '/api/v1/panel/cuentas/{id}/reactivar';

  /**
   * DESACTIVADA → PENDIENTE_ACTIVACION con contraseña temporal.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelReactivarCuenta()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelReactivarCuenta$Response(params: PanelReactivarCuenta$Params, context?: HttpContext): Promise<StrictHttpResponse<CuentaConCredencialTemporal>> {
    const obs = panelReactivarCuenta(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * DESACTIVADA → PENDIENTE_ACTIVACION con contraseña temporal.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelReactivarCuenta$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelReactivarCuenta(params: PanelReactivarCuenta$Params, context?: HttpContext): Promise<CuentaConCredencialTemporal> {
    const resp = this.panelReactivarCuenta$Response(params, context);
    return resp.then((r: StrictHttpResponse<CuentaConCredencialTemporal>): CuentaConCredencialTemporal => r.body);
  }

  /** Path part for operation `panelAnonimizarCuenta()` */
  static readonly PanelAnonimizarCuentaPath = '/api/v1/panel/cuentas/{id}/anonimizar';

  /**
   * Anonimizar ahora (solo DESACTIVADA; irreversible).
   *
   * Elimina usuario, nombre, credenciales y MFA; la auditoría pasa a mostrar un seudónimo (AC-107). Estado distinto de DESACTIVADA → 409 transicion_invalida. Audita CUENTA_ANONIMIZAR.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelAnonimizarCuenta()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelAnonimizarCuenta$Response(params: PanelAnonimizarCuenta$Params, context?: HttpContext): Promise<StrictHttpResponse<Cuenta>> {
    const obs = panelAnonimizarCuenta(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Anonimizar ahora (solo DESACTIVADA; irreversible).
   *
   * Elimina usuario, nombre, credenciales y MFA; la auditoría pasa a mostrar un seudónimo (AC-107). Estado distinto de DESACTIVADA → 409 transicion_invalida. Audita CUENTA_ANONIMIZAR.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelAnonimizarCuenta$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelAnonimizarCuenta(params: PanelAnonimizarCuenta$Params, context?: HttpContext): Promise<Cuenta> {
    const resp = this.panelAnonimizarCuenta$Response(params, context);
    return resp.then((r: StrictHttpResponse<Cuenta>): Cuenta => r.body);
  }

}
