/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ImpactoRetiro } from '../models/impacto-retiro';
import { PaginaRevisionResumen } from '../models/pagina-revision-resumen';
import { panelListarRevisiones } from '../fn/panel-ciclo-editorial/panel-listar-revisiones';
import { PanelListarRevisiones$Params } from '../fn/panel-ciclo-editorial/panel-listar-revisiones';
import { panelObtenerImpactoRetiro } from '../fn/panel-ciclo-editorial/panel-obtener-impacto-retiro';
import { PanelObtenerImpactoRetiro$Params } from '../fn/panel-ciclo-editorial/panel-obtener-impacto-retiro';
import { panelObtenerRevision } from '../fn/panel-ciclo-editorial/panel-obtener-revision';
import { PanelObtenerRevision$Params } from '../fn/panel-ciclo-editorial/panel-obtener-revision';
import { panelPublicarContenido } from '../fn/panel-ciclo-editorial/panel-publicar-contenido';
import { PanelPublicarContenido$Params } from '../fn/panel-ciclo-editorial/panel-publicar-contenido';
import { panelReactivarContenido } from '../fn/panel-ciclo-editorial/panel-reactivar-contenido';
import { PanelReactivarContenido$Params } from '../fn/panel-ciclo-editorial/panel-reactivar-contenido';
import { panelRestaurarRevision } from '../fn/panel-ciclo-editorial/panel-restaurar-revision';
import { PanelRestaurarRevision$Params } from '../fn/panel-ciclo-editorial/panel-restaurar-revision';
import { panelRetirarContenido } from '../fn/panel-ciclo-editorial/panel-retirar-contenido';
import { PanelRetirarContenido$Params } from '../fn/panel-ciclo-editorial/panel-retirar-contenido';
import { RestauracionRevision } from '../models/restauracion-revision';
import { ResultadoTransicion } from '../models/resultado-transicion';
import { RevisionDetalle } from '../models/revision-detalle';


/**
 * Publicar, retirar, reactivar y revisiones (STATE-001).
 */
@Injectable({ providedIn: 'root' })
export class PanelCicloEditorialService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `panelPublicarContenido()` */
  static readonly PanelPublicarContenidoPath = '/api/v1/panel/contenidos/{tipo}/{id}/publicar';

  /**
   * BORRADOR → PUBLICADO con validación completa.
   *
   * Valida RULE-002..006, 009, 023..027 según el tipo; si falla, 422 publicacion_invalida con `errors` por campo (lista enlazable a los campos, ALT-018). Si pasa: fija el slug, crea la instantánea (DATA-026) en la misma transacción y audita PUBLICAR. Estado distinto de BORRADOR: 409 transicion_invalida. Páginas legales: solo Administrador.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelPublicarContenido()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelPublicarContenido$Response(params: PanelPublicarContenido$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoTransicion>> {
    const obs = panelPublicarContenido(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * BORRADOR → PUBLICADO con validación completa.
   *
   * Valida RULE-002..006, 009, 023..027 según el tipo; si falla, 422 publicacion_invalida con `errors` por campo (lista enlazable a los campos, ALT-018). Si pasa: fija el slug, crea la instantánea (DATA-026) en la misma transacción y audita PUBLICAR. Estado distinto de BORRADOR: 409 transicion_invalida. Páginas legales: solo Administrador.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelPublicarContenido$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelPublicarContenido(params: PanelPublicarContenido$Params, context?: HttpContext): Promise<ResultadoTransicion> {
    const resp = this.panelPublicarContenido$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoTransicion>): ResultadoTransicion => r.body);
  }

  /** Path part for operation `panelObtenerImpactoRetiro()` */
  static readonly PanelObtenerImpactoRetiroPath = '/api/v1/panel/contenidos/{tipo}/{id}/impacto-retiro';

  /**
   * Análisis de impacto antes de retirar (cascada, colecciones, destacados, enlaces entrantes).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerImpactoRetiro()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerImpactoRetiro$Response(params: PanelObtenerImpactoRetiro$Params, context?: HttpContext): Promise<StrictHttpResponse<ImpactoRetiro>> {
    const obs = panelObtenerImpactoRetiro(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Análisis de impacto antes de retirar (cascada, colecciones, destacados, enlaces entrantes).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerImpactoRetiro$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerImpactoRetiro(params: PanelObtenerImpactoRetiro$Params, context?: HttpContext): Promise<ImpactoRetiro> {
    const resp = this.panelObtenerImpactoRetiro$Response(params, context);
    return resp.then((r: StrictHttpResponse<ImpactoRetiro>): ImpactoRetiro => r.body);
  }

  /** Path part for operation `panelRetirarContenido()` */
  static readonly PanelRetirarContenidoPath = '/api/v1/panel/contenidos/{tipo}/{id}/retirar';

  /**
   * PUBLICADO → RETIRADO (motivo obligatorio; cascada destino → itinerarios).
   *
   * Si el destino tiene itinerarios publicados y `confirmar_cascada` es false: 409 dependencia_bloqueante con `usos`. Con confirmación, retira en cascada con una instantánea y una entrada de auditoría RETIRAR por entidad (AC-112). Páginas institucionales: 409 transicion_invalida.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelRetirarContenido()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelRetirarContenido$Response(params: PanelRetirarContenido$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoTransicion>> {
    const obs = panelRetirarContenido(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * PUBLICADO → RETIRADO (motivo obligatorio; cascada destino → itinerarios).
   *
   * Si el destino tiene itinerarios publicados y `confirmar_cascada` es false: 409 dependencia_bloqueante con `usos`. Con confirmación, retira en cascada con una instantánea y una entrada de auditoría RETIRAR por entidad (AC-112). Páginas institucionales: 409 transicion_invalida.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelRetirarContenido$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelRetirarContenido(params: PanelRetirarContenido$Params, context?: HttpContext): Promise<ResultadoTransicion> {
    const resp = this.panelRetirarContenido$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoTransicion>): ResultadoTransicion => r.body);
  }

  /** Path part for operation `panelReactivarContenido()` */
  static readonly PanelReactivarContenidoPath = '/api/v1/panel/contenidos/{tipo}/{id}/reactivar';

  /**
   * RETIRADO → BORRADOR (conserva el slug).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelReactivarContenido()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelReactivarContenido$Response(params: PanelReactivarContenido$Params, context?: HttpContext): Promise<StrictHttpResponse<ResultadoTransicion>> {
    const obs = panelReactivarContenido(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * RETIRADO → BORRADOR (conserva el slug).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelReactivarContenido$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelReactivarContenido(params: PanelReactivarContenido$Params, context?: HttpContext): Promise<ResultadoTransicion> {
    const resp = this.panelReactivarContenido$Response(params, context);
    return resp.then((r: StrictHttpResponse<ResultadoTransicion>): ResultadoTransicion => r.body);
  }

  /** Path part for operation `panelListarRevisiones()` */
  static readonly PanelListarRevisionesPath = '/api/v1/panel/contenidos/{tipo}/{id}/revisiones';

  /**
   * Historial de revisiones (número descendente).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelListarRevisiones()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarRevisiones$Response(params: PanelListarRevisiones$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaRevisionResumen>> {
    const obs = panelListarRevisiones(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Historial de revisiones (número descendente).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelListarRevisiones$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelListarRevisiones(params: PanelListarRevisiones$Params, context?: HttpContext): Promise<PaginaRevisionResumen> {
    const resp = this.panelListarRevisiones$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaRevisionResumen>): PaginaRevisionResumen => r.body);
  }

  /** Path part for operation `panelObtenerRevision()` */
  static readonly PanelObtenerRevisionPath = '/api/v1/panel/contenidos/{tipo}/{id}/revisiones/{numero}';

  /**
   * Instantánea de una revisión.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerRevision()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerRevision$Response(params: PanelObtenerRevision$Params, context?: HttpContext): Promise<StrictHttpResponse<RevisionDetalle>> {
    const obs = panelObtenerRevision(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Instantánea de una revisión.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerRevision$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerRevision(params: PanelObtenerRevision$Params, context?: HttpContext): Promise<RevisionDetalle> {
    const resp = this.panelObtenerRevision$Response(params, context);
    return resp.then((r: StrictHttpResponse<RevisionDetalle>): RevisionDetalle => r.body);
  }

  /** Path part for operation `panelRestaurarRevision()` */
  static readonly PanelRestaurarRevisionPath = '/api/v1/panel/contenidos/{tipo}/{id}/revisiones/{numero}/restaurar';

  /**
   * Cargar una revisión en el formulario (no persiste contenido; audita RESTAURAR_REVISION).
   *
   * Devuelve los datos de la instantánea con la forma del cuerpo `{Tipo}Actualizacion` (sin `version`) y la versión vigente. Nada cambia en el sitio hasta guardar y publicar o actualizar (AC-121).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelRestaurarRevision()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelRestaurarRevision$Response(params: PanelRestaurarRevision$Params, context?: HttpContext): Promise<StrictHttpResponse<RestauracionRevision>> {
    const obs = panelRestaurarRevision(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Cargar una revisión en el formulario (no persiste contenido; audita RESTAURAR_REVISION).
   *
   * Devuelve los datos de la instantánea con la forma del cuerpo `{Tipo}Actualizacion` (sin `version`) y la versión vigente. Nada cambia en el sitio hasta guardar y publicar o actualizar (AC-121).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelRestaurarRevision$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelRestaurarRevision(params: PanelRestaurarRevision$Params, context?: HttpContext): Promise<RestauracionRevision> {
    const resp = this.panelRestaurarRevision$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestauracionRevision>): RestauracionRevision => r.body);
  }

}
