/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AutorizacionVigente } from '../models/autorizacion-vigente';
import { CodigosRecuperacion } from '../models/codigos-recuperacion';
import { MfaActivacionInicio } from '../models/mfa-activacion-inicio';
import { panelCambiarContrasena } from '../fn/panel-auth/panel-cambiar-contrasena';
import { PanelCambiarContrasena$Params } from '../fn/panel-auth/panel-cambiar-contrasena';
import { panelCerrarSesion } from '../fn/panel-auth/panel-cerrar-sesion';
import { PanelCerrarSesion$Params } from '../fn/panel-auth/panel-cerrar-sesion';
import { panelConfirmarActivacionMfa } from '../fn/panel-auth/panel-confirmar-activacion-mfa';
import { PanelConfirmarActivacionMfa$Params } from '../fn/panel-auth/panel-confirmar-activacion-mfa';
import { panelDesactivarMfa } from '../fn/panel-auth/panel-desactivar-mfa';
import { PanelDesactivarMfa$Params } from '../fn/panel-auth/panel-desactivar-mfa';
import { panelIniciarActivacionMfa } from '../fn/panel-auth/panel-iniciar-activacion-mfa';
import { PanelIniciarActivacionMfa$Params } from '../fn/panel-auth/panel-iniciar-activacion-mfa';
import { panelIniciarSesion } from '../fn/panel-auth/panel-iniciar-sesion';
import { PanelIniciarSesion$Params } from '../fn/panel-auth/panel-iniciar-sesion';
import { panelObtenerAutorizacion } from '../fn/panel-auth/panel-obtener-autorizacion';
import { PanelObtenerAutorizacion$Params } from '../fn/panel-auth/panel-obtener-autorizacion';
import { panelObtenerCsrf } from '../fn/panel-auth/panel-obtener-csrf';
import { PanelObtenerCsrf$Params } from '../fn/panel-auth/panel-obtener-csrf';
import { panelObtenerSesion } from '../fn/panel-auth/panel-obtener-sesion';
import { PanelObtenerSesion$Params } from '../fn/panel-auth/panel-obtener-sesion';
import { panelRegenerarCodigosRecuperacion } from '../fn/panel-auth/panel-regenerar-codigos-recuperacion';
import { PanelRegenerarCodigosRecuperacion$Params } from '../fn/panel-auth/panel-regenerar-codigos-recuperacion';
import { panelRegistrarAutorizacion } from '../fn/panel-auth/panel-registrar-autorizacion';
import { PanelRegistrarAutorizacion$Params } from '../fn/panel-auth/panel-registrar-autorizacion';
import { panelRenovarSesion } from '../fn/panel-auth/panel-renovar-sesion';
import { PanelRenovarSesion$Params } from '../fn/panel-auth/panel-renovar-sesion';
import { panelVerificarMfa } from '../fn/panel-auth/panel-verificar-mfa';
import { PanelVerificarMfa$Params } from '../fn/panel-auth/panel-verificar-mfa';
import { SesionEstado } from '../models/sesion-estado';


/**
 * Sesión, MFA, credenciales propias y autorización de tratamiento (MOD-009).
 */
@Injectable({ providedIn: 'root' })
export class PanelAuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `panelObtenerCsrf()` */
  static readonly PanelObtenerCsrfPath = '/api/v1/panel/auth/csrf';

  /**
   * Emite la cookie csrftoken antes del login.
   *
   * Única operación sin sesión que fija cookie; solo la invoca el SPA del panel (RULE-029).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerCsrf()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerCsrf$Response(params?: PanelObtenerCsrf$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = panelObtenerCsrf(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Emite la cookie csrftoken antes del login.
   *
   * Única operación sin sesión que fija cookie; solo la invoca el SPA del panel (RULE-029).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerCsrf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerCsrf(params?: PanelObtenerCsrf$Params, context?: HttpContext): Promise<void> {
    const resp = this.panelObtenerCsrf$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `panelIniciarSesion()` */
  static readonly PanelIniciarSesionPath = '/api/v1/panel/auth/login';

  /**
   * Iniciar sesión (usuario y contraseña).
   *
   * Mensaje y tiempo de respuesta equivalentes para usuario inexistente o contraseña errónea (THREAT-018). El contador de fallos se lleva por usuario normalizado exista o no la cuenta (DEC-AUTO-102): 5 fallos, bloqueo de 15 min progresivo, respuesta 429 `acceso_bloqueado_temporalmente` con Retry-After. En éxito rota el identificador de sesión (THREAT-002) y devuelve el paso pendiente (MFA, CONFIGURAR_MFA, CAMBIO_CREDENCIAL, AUTORIZACION o NINGUNO). `siguiente` solo se acepta si es una ruta relativa bajo `/panel/`; si no, `redireccion` = `/panel` (AC-115). Audita LOGIN_OK, LOGIN_FALLIDO, BLOQUEO. El cuerpo de la petición nunca se registra (THREAT-020).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelIniciarSesion()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelIniciarSesion$Response(params: PanelIniciarSesion$Params, context?: HttpContext): Promise<StrictHttpResponse<SesionEstado>> {
    const obs = panelIniciarSesion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Iniciar sesión (usuario y contraseña).
   *
   * Mensaje y tiempo de respuesta equivalentes para usuario inexistente o contraseña errónea (THREAT-018). El contador de fallos se lleva por usuario normalizado exista o no la cuenta (DEC-AUTO-102): 5 fallos, bloqueo de 15 min progresivo, respuesta 429 `acceso_bloqueado_temporalmente` con Retry-After. En éxito rota el identificador de sesión (THREAT-002) y devuelve el paso pendiente (MFA, CONFIGURAR_MFA, CAMBIO_CREDENCIAL, AUTORIZACION o NINGUNO). `siguiente` solo se acepta si es una ruta relativa bajo `/panel/`; si no, `redireccion` = `/panel` (AC-115). Audita LOGIN_OK, LOGIN_FALLIDO, BLOQUEO. El cuerpo de la petición nunca se registra (THREAT-020).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelIniciarSesion$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelIniciarSesion(params: PanelIniciarSesion$Params, context?: HttpContext): Promise<SesionEstado> {
    const resp = this.panelIniciarSesion$Response(params, context);
    return resp.then((r: StrictHttpResponse<SesionEstado>): SesionEstado => r.body);
  }

  /** Path part for operation `panelVerificarMfa()` */
  static readonly PanelVerificarMfaPath = '/api/v1/panel/auth/mfa/verificar';

  /**
   * Segundo factor (TOTP o código de recuperación).
   *
   * Solo en sesión parcial (paso MFA). Un código inválido cuenta como intento fallido (FEAT-030). En éxito rota la sesión.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelVerificarMfa()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelVerificarMfa$Response(params: PanelVerificarMfa$Params, context?: HttpContext): Promise<StrictHttpResponse<SesionEstado>> {
    const obs = panelVerificarMfa(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Segundo factor (TOTP o código de recuperación).
   *
   * Solo en sesión parcial (paso MFA). Un código inválido cuenta como intento fallido (FEAT-030). En éxito rota la sesión.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelVerificarMfa$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelVerificarMfa(params: PanelVerificarMfa$Params, context?: HttpContext): Promise<SesionEstado> {
    const resp = this.panelVerificarMfa$Response(params, context);
    return resp.then((r: StrictHttpResponse<SesionEstado>): SesionEstado => r.body);
  }

  /** Path part for operation `panelCerrarSesion()` */
  static readonly PanelCerrarSesionPath = '/api/v1/panel/auth/logout';

  /**
   * Cerrar sesión (invalida en el servidor).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelCerrarSesion()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelCerrarSesion$Response(params?: PanelCerrarSesion$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = panelCerrarSesion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Cerrar sesión (invalida en el servidor).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelCerrarSesion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelCerrarSesion(params?: PanelCerrarSesion$Params, context?: HttpContext): Promise<void> {
    const resp = this.panelCerrarSesion$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `panelObtenerSesion()` */
  static readonly PanelObtenerSesionPath = '/api/v1/panel/auth/sesion';

  /**
   * Estado de la sesión actual.
   *
   * Consultarla NO renueva la inactividad (para que el aviso de expiración sea fiable).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerSesion()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerSesion$Response(params?: PanelObtenerSesion$Params, context?: HttpContext): Promise<StrictHttpResponse<SesionEstado>> {
    const obs = panelObtenerSesion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Estado de la sesión actual.
   *
   * Consultarla NO renueva la inactividad (para que el aviso de expiración sea fiable).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerSesion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerSesion(params?: PanelObtenerSesion$Params, context?: HttpContext): Promise<SesionEstado> {
    const resp = this.panelObtenerSesion$Response(params, context);
    return resp.then((r: StrictHttpResponse<SesionEstado>): SesionEstado => r.body);
  }

  /** Path part for operation `panelRenovarSesion()` */
  static readonly PanelRenovarSesionPath = '/api/v1/panel/auth/sesion/renovar';

  /**
   * Seguir conectado (renueva la inactividad; nunca supera el máximo absoluto de 12 h).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelRenovarSesion()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelRenovarSesion$Response(params?: PanelRenovarSesion$Params, context?: HttpContext): Promise<StrictHttpResponse<SesionEstado>> {
    const obs = panelRenovarSesion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Seguir conectado (renueva la inactividad; nunca supera el máximo absoluto de 12 h).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelRenovarSesion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelRenovarSesion(params?: PanelRenovarSesion$Params, context?: HttpContext): Promise<SesionEstado> {
    const resp = this.panelRenovarSesion$Response(params, context);
    return resp.then((r: StrictHttpResponse<SesionEstado>): SesionEstado => r.body);
  }

  /** Path part for operation `panelCambiarContrasena()` */
  static readonly PanelCambiarContrasenaPath = '/api/v1/panel/auth/contrasena';

  /**
   * Cambiar la contraseña propia (obligatorio tras alta o restablecimiento).
   *
   * Política RULE-017 (≥12 caracteres, lista local de comprometidas, distinta del usuario, sin reglas de composición). Rota la sesión e invalida las demás sesiones de la cuenta. Audita CAMBIO_CREDENCIAL. Permitida también con paso pendiente CAMBIO_CREDENCIAL.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelCambiarContrasena()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCambiarContrasena$Response(params: PanelCambiarContrasena$Params, context?: HttpContext): Promise<StrictHttpResponse<SesionEstado>> {
    const obs = panelCambiarContrasena(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Cambiar la contraseña propia (obligatorio tras alta o restablecimiento).
   *
   * Política RULE-017 (≥12 caracteres, lista local de comprometidas, distinta del usuario, sin reglas de composición). Rota la sesión e invalida las demás sesiones de la cuenta. Audita CAMBIO_CREDENCIAL. Permitida también con paso pendiente CAMBIO_CREDENCIAL.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelCambiarContrasena$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelCambiarContrasena(params: PanelCambiarContrasena$Params, context?: HttpContext): Promise<SesionEstado> {
    const resp = this.panelCambiarContrasena$Response(params, context);
    return resp.then((r: StrictHttpResponse<SesionEstado>): SesionEstado => r.body);
  }

  /** Path part for operation `panelObtenerAutorizacion()` */
  static readonly PanelObtenerAutorizacionPath = '/api/v1/panel/auth/autorizacion';

  /**
   * Política de tratamiento vigente y autorización otorgada.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelObtenerAutorizacion()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerAutorizacion$Response(params?: PanelObtenerAutorizacion$Params, context?: HttpContext): Promise<StrictHttpResponse<AutorizacionVigente>> {
    const obs = panelObtenerAutorizacion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Política de tratamiento vigente y autorización otorgada.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelObtenerAutorizacion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  panelObtenerAutorizacion(params?: PanelObtenerAutorizacion$Params, context?: HttpContext): Promise<AutorizacionVigente> {
    const resp = this.panelObtenerAutorizacion$Response(params, context);
    return resp.then((r: StrictHttpResponse<AutorizacionVigente>): AutorizacionVigente => r.body);
  }

  /** Path part for operation `panelRegistrarAutorizacion()` */
  static readonly PanelRegistrarAutorizacionPath = '/api/v1/panel/auth/autorizacion';

  /**
   * Autorizar o no autorizar el tratamiento de datos.
   *
   * AUTORIZO registra fecha y versión (audita AUTORIZACION_ACEPTADA). NO_AUTORIZO cierra la sesión (204).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelRegistrarAutorizacion()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelRegistrarAutorizacion$Response(params: PanelRegistrarAutorizacion$Params, context?: HttpContext): Promise<StrictHttpResponse<SesionEstado>> {
    const obs = panelRegistrarAutorizacion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Autorizar o no autorizar el tratamiento de datos.
   *
   * AUTORIZO registra fecha y versión (audita AUTORIZACION_ACEPTADA). NO_AUTORIZO cierra la sesión (204).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelRegistrarAutorizacion$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelRegistrarAutorizacion(params: PanelRegistrarAutorizacion$Params, context?: HttpContext): Promise<SesionEstado> {
    const resp = this.panelRegistrarAutorizacion$Response(params, context);
    return resp.then((r: StrictHttpResponse<SesionEstado>): SesionEstado => r.body);
  }

  /** Path part for operation `panelIniciarActivacionMfa()` */
  static readonly PanelIniciarActivacionMfaPath = '/api/v1/panel/auth/mfa/activacion';

  /**
   * Iniciar activación TOTP con reautenticación (devuelve URI otpauth; el QR se genera en el cliente, sin terceros).
   *
   * Exige reautenticación con la contraseña actual de la cuenta (CHG-API-002, DEC-AUTO-215/218), también con paso pendiente CONFIGURAR_MFA: una sesión robada no puede vincular un segundo factor del atacante. Contraseña ausente, vacía o con formato inválido → 400 validacion con `errors.contrasena`. Contraseña incorrecta → 401 credenciales_invalidas (misma semántica y tiempo equivalente que el login, THREAT-018); NO cierra la sesión y el cliente NO debe tratar este 401 como sesión expirada (distinguir por `code`). Cada fallo cuenta en el contador por usuario normalizado de RULE-017 (5 fallos → 429 acceso_bloqueado_temporalmente con Retry-After) y se audita como LOGIN_FALLIDO. Solo con contraseña correcta se genera el secreto provisional; cualquier secreto provisional previo de la sesión se descarta. MFA ya activo → 409 transicion_invalida. El cuerpo nunca se registra (THREAT-020).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelIniciarActivacionMfa()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelIniciarActivacionMfa$Response(params: PanelIniciarActivacionMfa$Params, context?: HttpContext): Promise<StrictHttpResponse<MfaActivacionInicio>> {
    const obs = panelIniciarActivacionMfa(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Iniciar activación TOTP con reautenticación (devuelve URI otpauth; el QR se genera en el cliente, sin terceros).
   *
   * Exige reautenticación con la contraseña actual de la cuenta (CHG-API-002, DEC-AUTO-215/218), también con paso pendiente CONFIGURAR_MFA: una sesión robada no puede vincular un segundo factor del atacante. Contraseña ausente, vacía o con formato inválido → 400 validacion con `errors.contrasena`. Contraseña incorrecta → 401 credenciales_invalidas (misma semántica y tiempo equivalente que el login, THREAT-018); NO cierra la sesión y el cliente NO debe tratar este 401 como sesión expirada (distinguir por `code`). Cada fallo cuenta en el contador por usuario normalizado de RULE-017 (5 fallos → 429 acceso_bloqueado_temporalmente con Retry-After) y se audita como LOGIN_FALLIDO. Solo con contraseña correcta se genera el secreto provisional; cualquier secreto provisional previo de la sesión se descarta. MFA ya activo → 409 transicion_invalida. El cuerpo nunca se registra (THREAT-020).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelIniciarActivacionMfa$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelIniciarActivacionMfa(params: PanelIniciarActivacionMfa$Params, context?: HttpContext): Promise<MfaActivacionInicio> {
    const resp = this.panelIniciarActivacionMfa$Response(params, context);
    return resp.then((r: StrictHttpResponse<MfaActivacionInicio>): MfaActivacionInicio => r.body);
  }

  /** Path part for operation `panelConfirmarActivacionMfa()` */
  static readonly PanelConfirmarActivacionMfaPath = '/api/v1/panel/auth/mfa/activacion/confirmar';

  /**
   * Confirmar activación TOTP con un código; devuelve los códigos de recuperación una sola vez.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelConfirmarActivacionMfa()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelConfirmarActivacionMfa$Response(params: PanelConfirmarActivacionMfa$Params, context?: HttpContext): Promise<StrictHttpResponse<CodigosRecuperacion>> {
    const obs = panelConfirmarActivacionMfa(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Confirmar activación TOTP con un código; devuelve los códigos de recuperación una sola vez.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelConfirmarActivacionMfa$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelConfirmarActivacionMfa(params: PanelConfirmarActivacionMfa$Params, context?: HttpContext): Promise<CodigosRecuperacion> {
    const resp = this.panelConfirmarActivacionMfa$Response(params, context);
    return resp.then((r: StrictHttpResponse<CodigosRecuperacion>): CodigosRecuperacion => r.body);
  }

  /** Path part for operation `panelDesactivarMfa()` */
  static readonly PanelDesactivarMfaPath = '/api/v1/panel/auth/mfa/desactivar';

  /**
   * Desactivar MFA propio (rechazado para Administrador, 409 mfa_obligatorio).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelDesactivarMfa()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelDesactivarMfa$Response(params: PanelDesactivarMfa$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = panelDesactivarMfa(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Desactivar MFA propio (rechazado para Administrador, 409 mfa_obligatorio).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelDesactivarMfa$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelDesactivarMfa(params: PanelDesactivarMfa$Params, context?: HttpContext): Promise<void> {
    const resp = this.panelDesactivarMfa$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `panelRegenerarCodigosRecuperacion()` */
  static readonly PanelRegenerarCodigosRecuperacionPath = '/api/v1/panel/auth/mfa/codigos-recuperacion';

  /**
   * Regenerar códigos de recuperación (invalida los anteriores).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `panelRegenerarCodigosRecuperacion()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelRegenerarCodigosRecuperacion$Response(params: PanelRegenerarCodigosRecuperacion$Params, context?: HttpContext): Promise<StrictHttpResponse<CodigosRecuperacion>> {
    const obs = panelRegenerarCodigosRecuperacion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Regenerar códigos de recuperación (invalida los anteriores).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `panelRegenerarCodigosRecuperacion$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  panelRegenerarCodigosRecuperacion(params: PanelRegenerarCodigosRecuperacion$Params, context?: HttpContext): Promise<CodigosRecuperacion> {
    const resp = this.panelRegenerarCodigosRecuperacion$Response(params, context);
    return resp.then((r: StrictHttpResponse<CodigosRecuperacion>): CodigosRecuperacion => r.body);
  }

}
