/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CategoriaGuiaPublica } from '../models/categoria-guia-publica';
import { GuiaDetalle } from '../models/guia-detalle';
import { PaginaCategoriaGuiaIndice } from '../models/pagina-categoria-guia-indice';
import { PaginaGuiaTarjeta } from '../models/pagina-guia-tarjeta';
import { publicoListarCategoriasGuia } from '../fn/publico-guias/publico-listar-categorias-guia';
import { PublicoListarCategoriasGuia$Params } from '../fn/publico-guias/publico-listar-categorias-guia';
import { publicoListarGuias } from '../fn/publico-guias/publico-listar-guias';
import { PublicoListarGuias$Params } from '../fn/publico-guias/publico-listar-guias';
import { publicoObtenerCategoriaGuia } from '../fn/publico-guias/publico-obtener-categoria-guia';
import { PublicoObtenerCategoriaGuia$Params } from '../fn/publico-guias/publico-obtener-categoria-guia';
import { publicoObtenerGuia } from '../fn/publico-guias/publico-obtener-guia';
import { PublicoObtenerGuia$Params } from '../fn/publico-guias/publico-obtener-guia';

@Injectable({ providedIn: 'root' })
export class PublicoGuiasService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicoListarCategoriasGuia()` */
  static readonly PublicoListarCategoriasGuiaPath = '/api/v1/publico/categorias-guia';

  /**
   * Categorías con al menos una guía publicada y sus guías más recientes (hasta 4).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoListarCategoriasGuia()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarCategoriasGuia$Response(params?: PublicoListarCategoriasGuia$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaCategoriaGuiaIndice>> {
    const obs = publicoListarCategoriasGuia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Categorías con al menos una guía publicada y sus guías más recientes (hasta 4).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoListarCategoriasGuia$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarCategoriasGuia(params?: PublicoListarCategoriasGuia$Params, context?: HttpContext): Promise<PaginaCategoriaGuiaIndice> {
    const resp = this.publicoListarCategoriasGuia$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaCategoriaGuiaIndice>): PaginaCategoriaGuiaIndice => r.body);
  }

  /** Path part for operation `publicoObtenerCategoriaGuia()` */
  static readonly PublicoObtenerCategoriaGuiaPath = '/api/v1/publico/categorias-guia/{slug}';

  /**
   * Datos de una categoría (sus guías con GET /guias?categoria=).
   *
   * Una categoría sin guías publicadas responde 404 (SCR-011).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerCategoriaGuia()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerCategoriaGuia$Response(params: PublicoObtenerCategoriaGuia$Params, context?: HttpContext): Promise<StrictHttpResponse<CategoriaGuiaPublica>> {
    const obs = publicoObtenerCategoriaGuia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Datos de una categoría (sus guías con GET /guias?categoria=).
   *
   * Una categoría sin guías publicadas responde 404 (SCR-011).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerCategoriaGuia$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerCategoriaGuia(params: PublicoObtenerCategoriaGuia$Params, context?: HttpContext): Promise<CategoriaGuiaPublica> {
    const resp = this.publicoObtenerCategoriaGuia$Response(params, context);
    return resp.then((r: StrictHttpResponse<CategoriaGuiaPublica>): CategoriaGuiaPublica => r.body);
  }

  /** Path part for operation `publicoListarGuias()` */
  static readonly PublicoListarGuiasPath = '/api/v1/publico/guias';

  /**
   * Guías publicadas por fecha de revisión descendente (24 por página).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoListarGuias()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarGuias$Response(params?: PublicoListarGuias$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaGuiaTarjeta>> {
    const obs = publicoListarGuias(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Guías publicadas por fecha de revisión descendente (24 por página).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoListarGuias$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarGuias(params?: PublicoListarGuias$Params, context?: HttpContext): Promise<PaginaGuiaTarjeta> {
    const resp = this.publicoListarGuias$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaGuiaTarjeta>): PaginaGuiaTarjeta => r.body);
  }

  /** Path part for operation `publicoObtenerGuia()` */
  static readonly PublicoObtenerGuiaPath = '/api/v1/publico/guias/{slug}';

  /**
   * Detalle de guía.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerGuia()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerGuia$Response(params: PublicoObtenerGuia$Params, context?: HttpContext): Promise<StrictHttpResponse<GuiaDetalle>> {
    const obs = publicoObtenerGuia(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Detalle de guía.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerGuia$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerGuia(params: PublicoObtenerGuia$Params, context?: HttpContext): Promise<GuiaDetalle> {
    const resp = this.publicoObtenerGuia$Response(params, context);
    return resp.then((r: StrictHttpResponse<GuiaDetalle>): GuiaDetalle => r.body);
  }

}
