/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaginaTipoAventuraTarjeta } from '../models/pagina-tipo-aventura-tarjeta';
import { publicoListarTiposAventura } from '../fn/publico-tipos/publico-listar-tipos-aventura';
import { PublicoListarTiposAventura$Params } from '../fn/publico-tipos/publico-listar-tipos-aventura';
import { publicoObtenerTipoAventura } from '../fn/publico-tipos/publico-obtener-tipo-aventura';
import { PublicoObtenerTipoAventura$Params } from '../fn/publico-tipos/publico-obtener-tipo-aventura';
import { TipoAventuraDetalle } from '../models/tipo-aventura-detalle';

@Injectable({ providedIn: 'root' })
export class PublicoTiposService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicoListarTiposAventura()` */
  static readonly PublicoListarTiposAventuraPath = '/api/v1/publico/tipos-aventura';

  /**
   * Índice de tipos de aventura publicados.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoListarTiposAventura()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarTiposAventura$Response(params?: PublicoListarTiposAventura$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaTipoAventuraTarjeta>> {
    const obs = publicoListarTiposAventura(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Índice de tipos de aventura publicados.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoListarTiposAventura$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarTiposAventura(params?: PublicoListarTiposAventura$Params, context?: HttpContext): Promise<PaginaTipoAventuraTarjeta> {
    const resp = this.publicoListarTiposAventura$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaTipoAventuraTarjeta>): PaginaTipoAventuraTarjeta => r.body);
  }

  /** Path part for operation `publicoObtenerTipoAventura()` */
  static readonly PublicoObtenerTipoAventuraPath = '/api/v1/publico/tipos-aventura/{slug}';

  /**
   * Detalle de tipo de aventura con checklist.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerTipoAventura()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerTipoAventura$Response(params: PublicoObtenerTipoAventura$Params, context?: HttpContext): Promise<StrictHttpResponse<TipoAventuraDetalle>> {
    const obs = publicoObtenerTipoAventura(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Detalle de tipo de aventura con checklist.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerTipoAventura$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerTipoAventura(params: PublicoObtenerTipoAventura$Params, context?: HttpContext): Promise<TipoAventuraDetalle> {
    const resp = this.publicoObtenerTipoAventura$Response(params, context);
    return resp.then((r: StrictHttpResponse<TipoAventuraDetalle>): TipoAventuraDetalle => r.body);
  }

}
