/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DestinoAleatorio } from '../models/destino-aleatorio';
import { DestinoDetalle } from '../models/destino-detalle';
import { FacetasDestinos } from '../models/facetas-destinos';
import { PaginaDestinoMapa } from '../models/pagina-destino-mapa';
import { PaginaDestinoTarjeta } from '../models/pagina-destino-tarjeta';
import { publicoListarDestinos } from '../fn/publico-destinos/publico-listar-destinos';
import { PublicoListarDestinos$Params } from '../fn/publico-destinos/publico-listar-destinos';
import { publicoListarDestinosMapa } from '../fn/publico-destinos/publico-listar-destinos-mapa';
import { PublicoListarDestinosMapa$Params } from '../fn/publico-destinos/publico-listar-destinos-mapa';
import { publicoObtenerDestino } from '../fn/publico-destinos/publico-obtener-destino';
import { PublicoObtenerDestino$Params } from '../fn/publico-destinos/publico-obtener-destino';
import { publicoObtenerDestinoAleatorio } from '../fn/publico-destinos/publico-obtener-destino-aleatorio';
import { PublicoObtenerDestinoAleatorio$Params } from '../fn/publico-destinos/publico-obtener-destino-aleatorio';
import { publicoObtenerFacetasDestinos } from '../fn/publico-destinos/publico-obtener-facetas-destinos';
import { PublicoObtenerFacetasDestinos$Params } from '../fn/publico-destinos/publico-obtener-facetas-destinos';

@Injectable({ providedIn: 'root' })
export class PublicoDestinosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicoObtenerFacetasDestinos()` */
  static readonly PublicoObtenerFacetasDestinosPath = '/api/v1/publico/facetas/destinos';

  /**
   * Opciones de los filtros de destinos (solo valores con contenido publicado).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerFacetasDestinos()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerFacetasDestinos$Response(params?: PublicoObtenerFacetasDestinos$Params, context?: HttpContext): Promise<StrictHttpResponse<FacetasDestinos>> {
    const obs = publicoObtenerFacetasDestinos(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Opciones de los filtros de destinos (solo valores con contenido publicado).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerFacetasDestinos$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerFacetasDestinos(params?: PublicoObtenerFacetasDestinos$Params, context?: HttpContext): Promise<FacetasDestinos> {
    const resp = this.publicoObtenerFacetasDestinos$Response(params, context);
    return resp.then((r: StrictHttpResponse<FacetasDestinos>): FacetasDestinos => r.body);
  }

  /** Path part for operation `publicoListarDestinos()` */
  static readonly PublicoListarDestinosPath = '/api/v1/publico/destinos';

  /**
   * Listar y filtrar destinos publicados (24 por página).
   *
   * OR dentro de una faceta y AND entre facetas; dificultad como rango; tramos de duración por solapamiento; orden por defecto A-Z según el alfabeto español sin tildes (RULE-019, DEC-AUTO-047). Valores contra dominios cerrados: slug inexistente, rango inválido (dificultad_min > dificultad_max) o parámetro desconocido devuelven 400 `parametro_invalido` (AC-113, THREAT-008). El Frontend descarta los parámetros inválidos antes de llamar (la UI los ignora).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoListarDestinos()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarDestinos$Response(params?: PublicoListarDestinos$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaDestinoTarjeta>> {
    const obs = publicoListarDestinos(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Listar y filtrar destinos publicados (24 por página).
   *
   * OR dentro de una faceta y AND entre facetas; dificultad como rango; tramos de duración por solapamiento; orden por defecto A-Z según el alfabeto español sin tildes (RULE-019, DEC-AUTO-047). Valores contra dominios cerrados: slug inexistente, rango inválido (dificultad_min > dificultad_max) o parámetro desconocido devuelven 400 `parametro_invalido` (AC-113, THREAT-008). El Frontend descarta los parámetros inválidos antes de llamar (la UI los ignora).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoListarDestinos$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarDestinos(params?: PublicoListarDestinos$Params, context?: HttpContext): Promise<PaginaDestinoTarjeta> {
    const resp = this.publicoListarDestinos$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaDestinoTarjeta>): PaginaDestinoTarjeta => r.body);
  }

  /** Path part for operation `publicoListarDestinosMapa()` */
  static readonly PublicoListarDestinosMapaPath = '/api/v1/publico/destinos/mapa';

  /**
   * Lista ligera de destinos con coordenadas (mapa y lista alternativa).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoListarDestinosMapa()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarDestinosMapa$Response(params?: PublicoListarDestinosMapa$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaDestinoMapa>> {
    const obs = publicoListarDestinosMapa(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Lista ligera de destinos con coordenadas (mapa y lista alternativa).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoListarDestinosMapa$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarDestinosMapa(params?: PublicoListarDestinosMapa$Params, context?: HttpContext): Promise<PaginaDestinoMapa> {
    const resp = this.publicoListarDestinosMapa$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaDestinoMapa>): PaginaDestinoMapa => r.body);
  }

  /** Path part for operation `publicoObtenerDestinoAleatorio()` */
  static readonly PublicoObtenerDestinoAleatorioPath = '/api/v1/publico/destinos/aleatorio';

  /**
   * Sorpréndeme (un destino publicado al azar).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerDestinoAleatorio()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerDestinoAleatorio$Response(params?: PublicoObtenerDestinoAleatorio$Params, context?: HttpContext): Promise<StrictHttpResponse<DestinoAleatorio>> {
    const obs = publicoObtenerDestinoAleatorio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Sorpréndeme (un destino publicado al azar).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerDestinoAleatorio$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerDestinoAleatorio(params?: PublicoObtenerDestinoAleatorio$Params, context?: HttpContext): Promise<DestinoAleatorio> {
    const resp = this.publicoObtenerDestinoAleatorio$Response(params, context);
    return resp.then((r: StrictHttpResponse<DestinoAleatorio>): DestinoAleatorio => r.body);
  }

  /** Path part for operation `publicoObtenerDestino()` */
  static readonly PublicoObtenerDestinoPath = '/api/v1/publico/destinos/{slug}';

  /**
   * Ficha de destino por slug.
   *
   * Solo PUBLICADO. Inexistente o borrador nunca publicado: 404. Retirado: 410 con alternativas y sin el cuerpo del contenido (DEC-AUTO-040, DEC-AUTO-113). Los slugs `mapa` y `aleatorio` están reservados (DEC-AUTO-117).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerDestino()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerDestino$Response(params: PublicoObtenerDestino$Params, context?: HttpContext): Promise<StrictHttpResponse<DestinoDetalle>> {
    const obs = publicoObtenerDestino(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Ficha de destino por slug.
   *
   * Solo PUBLICADO. Inexistente o borrador nunca publicado: 404. Retirado: 410 con alternativas y sin el cuerpo del contenido (DEC-AUTO-040, DEC-AUTO-113). Los slugs `mapa` y `aleatorio` están reservados (DEC-AUTO-117).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerDestino$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerDestino(params: PublicoObtenerDestino$Params, context?: HttpContext): Promise<DestinoDetalle> {
    const resp = this.publicoObtenerDestino$Response(params, context);
    return resp.then((r: StrictHttpResponse<DestinoDetalle>): DestinoDetalle => r.body);
  }

}
