/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ItinerarioDetalle } from '../models/itinerario-detalle';
import { PaginaItinerarioTarjeta } from '../models/pagina-itinerario-tarjeta';
import { publicoListarItinerarios } from '../fn/publico-itinerarios/publico-listar-itinerarios';
import { PublicoListarItinerarios$Params } from '../fn/publico-itinerarios/publico-listar-itinerarios';
import { publicoObtenerItinerario } from '../fn/publico-itinerarios/publico-obtener-itinerario';
import { PublicoObtenerItinerario$Params } from '../fn/publico-itinerarios/publico-obtener-itinerario';

@Injectable({ providedIn: 'root' })
export class PublicoItinerariosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicoListarItinerarios()` */
  static readonly PublicoListarItinerariosPath = '/api/v1/publico/itinerarios';

  /**
   * Listar itinerarios publicados (24 por página).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoListarItinerarios()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarItinerarios$Response(params?: PublicoListarItinerarios$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaItinerarioTarjeta>> {
    const obs = publicoListarItinerarios(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Listar itinerarios publicados (24 por página).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoListarItinerarios$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarItinerarios(params?: PublicoListarItinerarios$Params, context?: HttpContext): Promise<PaginaItinerarioTarjeta> {
    const resp = this.publicoListarItinerarios$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaItinerarioTarjeta>): PaginaItinerarioTarjeta => r.body);
  }

  /** Path part for operation `publicoObtenerItinerario()` */
  static readonly PublicoObtenerItinerarioPath = '/api/v1/publico/itinerarios/{slug}';

  /**
   * Detalle de itinerario día a día.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerItinerario()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerItinerario$Response(params: PublicoObtenerItinerario$Params, context?: HttpContext): Promise<StrictHttpResponse<ItinerarioDetalle>> {
    const obs = publicoObtenerItinerario(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Detalle de itinerario día a día.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerItinerario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerItinerario(params: PublicoObtenerItinerario$Params, context?: HttpContext): Promise<ItinerarioDetalle> {
    const resp = this.publicoObtenerItinerario$Response(params, context);
    return resp.then((r: StrictHttpResponse<ItinerarioDetalle>): ItinerarioDetalle => r.body);
  }

}
