/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ColeccionDetalle } from '../models/coleccion-detalle';
import { PaginaColeccionTarjeta } from '../models/pagina-coleccion-tarjeta';
import { publicoListarColecciones } from '../fn/publico-colecciones/publico-listar-colecciones';
import { PublicoListarColecciones$Params } from '../fn/publico-colecciones/publico-listar-colecciones';
import { publicoObtenerColeccion } from '../fn/publico-colecciones/publico-obtener-coleccion';
import { PublicoObtenerColeccion$Params } from '../fn/publico-colecciones/publico-obtener-coleccion';

@Injectable({ providedIn: 'root' })
export class PublicoColeccionesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicoListarColecciones()` */
  static readonly PublicoListarColeccionesPath = '/api/v1/publico/colecciones';

  /**
   * Índice de colecciones publicadas.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoListarColecciones()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarColecciones$Response(params?: PublicoListarColecciones$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaColeccionTarjeta>> {
    const obs = publicoListarColecciones(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Índice de colecciones publicadas.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoListarColecciones$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarColecciones(params?: PublicoListarColecciones$Params, context?: HttpContext): Promise<PaginaColeccionTarjeta> {
    const resp = this.publicoListarColecciones$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaColeccionTarjeta>): PaginaColeccionTarjeta => r.body);
  }

  /** Path part for operation `publicoObtenerColeccion()` */
  static readonly PublicoObtenerColeccionPath = '/api/v1/publico/colecciones/{slug}';

  /**
   * Detalle de colección (solo elementos publicados, RULE-024).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerColeccion()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerColeccion$Response(params: PublicoObtenerColeccion$Params, context?: HttpContext): Promise<StrictHttpResponse<ColeccionDetalle>> {
    const obs = publicoObtenerColeccion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Detalle de colección (solo elementos publicados, RULE-024).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerColeccion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerColeccion(params: PublicoObtenerColeccion$Params, context?: HttpContext): Promise<ColeccionDetalle> {
    const resp = this.publicoObtenerColeccion$Response(params, context);
    return resp.then((r: StrictHttpResponse<ColeccionDetalle>): ColeccionDetalle => r.body);
  }

}
