/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ConfiguracionPublica } from '../models/configuracion-publica';
import { Escalas } from '../models/escalas';
import { Inicio } from '../models/inicio';
import { Meses } from '../models/meses';
import { PaginaEntradaIndice } from '../models/pagina-entrada-indice';
import { PaginaInstitucionalPublica } from '../models/pagina-institucional-publica';
import { publicoListarIndice } from '../fn/publico-general/publico-listar-indice';
import { PublicoListarIndice$Params } from '../fn/publico-general/publico-listar-indice';
import { publicoObtenerConfiguracion } from '../fn/publico-general/publico-obtener-configuracion';
import { PublicoObtenerConfiguracion$Params } from '../fn/publico-general/publico-obtener-configuracion';
import { publicoObtenerEscalas } from '../fn/publico-general/publico-obtener-escalas';
import { PublicoObtenerEscalas$Params } from '../fn/publico-general/publico-obtener-escalas';
import { publicoObtenerInicio } from '../fn/publico-general/publico-obtener-inicio';
import { PublicoObtenerInicio$Params } from '../fn/publico-general/publico-obtener-inicio';
import { publicoObtenerMeses } from '../fn/publico-general/publico-obtener-meses';
import { PublicoObtenerMeses$Params } from '../fn/publico-general/publico-obtener-meses';
import { publicoObtenerPaginaInstitucional } from '../fn/publico-general/publico-obtener-pagina-institucional';
import { PublicoObtenerPaginaInstitucional$Params } from '../fn/publico-general/publico-obtener-pagina-institucional';


/**
 * Inicio, configuración pública, escalas, meses, índice y páginas institucionales.
 */
@Injectable({ providedIn: 'root' })
export class PublicoGeneralService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicoObtenerInicio()` */
  static readonly PublicoObtenerInicioPath = '/api/v1/publico/inicio';

  /**
   * Datos del inicio (destacados con relleno automático).
   *
   * Bloque principal, 6-12 destinos, 3-6 itinerarios, 3-6 guías y todos los tipos publicados. Si los destacados configurados no alcanzan los mínimos, el servidor completa con el contenido publicado de revisión más reciente (RULE-016). En un entorno sin contenido las listas pueden venir vacías.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerInicio()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerInicio$Response(params?: PublicoObtenerInicio$Params, context?: HttpContext): Promise<StrictHttpResponse<Inicio>> {
    const obs = publicoObtenerInicio(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Datos del inicio (destacados con relleno automático).
   *
   * Bloque principal, 6-12 destinos, 3-6 itinerarios, 3-6 guías y todos los tipos publicados. Si los destacados configurados no alcanzan los mínimos, el servidor completa con el contenido publicado de revisión más reciente (RULE-016). En un entorno sin contenido las listas pueden venir vacías.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerInicio$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerInicio(params?: PublicoObtenerInicio$Params, context?: HttpContext): Promise<Inicio> {
    const resp = this.publicoObtenerInicio$Response(params, context);
    return resp.then((r: StrictHttpResponse<Inicio>): Inicio => r.body);
  }

  /** Path part for operation `publicoObtenerConfiguracion()` */
  static readonly PublicoObtenerConfiguracionPath = '/api/v1/publico/configuracion';

  /**
   * Marca, lema, descargo y datos del Responsable del tratamiento.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerConfiguracion()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerConfiguracion$Response(params?: PublicoObtenerConfiguracion$Params, context?: HttpContext): Promise<StrictHttpResponse<ConfiguracionPublica>> {
    const obs = publicoObtenerConfiguracion(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Marca, lema, descargo y datos del Responsable del tratamiento.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerConfiguracion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerConfiguracion(params?: PublicoObtenerConfiguracion$Params, context?: HttpContext): Promise<ConfiguracionPublica> {
    const resp = this.publicoObtenerConfiguracion$Response(params, context);
    return resp.then((r: StrictHttpResponse<ConfiguracionPublica>): ConfiguracionPublica => r.body);
  }

  /** Path part for operation `publicoObtenerEscalas()` */
  static readonly PublicoObtenerEscalasPath = '/api/v1/publico/escalas';

  /**
   * Escalas de dificultad (1-5) y presupuesto (1-4).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerEscalas()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerEscalas$Response(params?: PublicoObtenerEscalas$Params, context?: HttpContext): Promise<StrictHttpResponse<Escalas>> {
    const obs = publicoObtenerEscalas(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Escalas de dificultad (1-5) y presupuesto (1-4).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerEscalas$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerEscalas(params?: PublicoObtenerEscalas$Params, context?: HttpContext): Promise<Escalas> {
    const resp = this.publicoObtenerEscalas$Response(params, context);
    return resp.then((r: StrictHttpResponse<Escalas>): Escalas => r.body);
  }

  /** Path part for operation `publicoObtenerMeses()` */
  static readonly PublicoObtenerMesesPath = '/api/v1/publico/meses';

  /**
   * Doce meses con número de destinos y un destacado por mes.
   *
   * Colección acotada por diseño (exactamente 12 elementos, DEC-AUTO-104). Los destinos de un mes se obtienen con `GET /api/v1/publico/destinos?mes=N` (RULE-011).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerMeses()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerMeses$Response(params?: PublicoObtenerMeses$Params, context?: HttpContext): Promise<StrictHttpResponse<Meses>> {
    const obs = publicoObtenerMeses(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Doce meses con número de destinos y un destacado por mes.
   *
   * Colección acotada por diseño (exactamente 12 elementos, DEC-AUTO-104). Los destinos de un mes se obtienen con `GET /api/v1/publico/destinos?mes=N` (RULE-011).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerMeses$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerMeses(params?: PublicoObtenerMeses$Params, context?: HttpContext): Promise<Meses> {
    const resp = this.publicoObtenerMeses$Response(params, context);
    return resp.then((r: StrictHttpResponse<Meses>): Meses => r.body);
  }

  /** Path part for operation `publicoListarIndice()` */
  static readonly PublicoListarIndicePath = '/api/v1/publico/indice';

  /**
   * Todas las páginas publicadas (mapa del sitio HTML y sitemap.xml).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoListarIndice()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarIndice$Response(params?: PublicoListarIndice$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaEntradaIndice>> {
    const obs = publicoListarIndice(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Todas las páginas publicadas (mapa del sitio HTML y sitemap.xml).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoListarIndice$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarIndice(params?: PublicoListarIndice$Params, context?: HttpContext): Promise<PaginaEntradaIndice> {
    const resp = this.publicoListarIndice$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaEntradaIndice>): PaginaEntradaIndice => r.body);
  }

  /** Path part for operation `publicoObtenerPaginaInstitucional()` */
  static readonly PublicoObtenerPaginaInstitucionalPath = '/api/v1/publico/paginas/{slug}';

  /**
   * Página institucional (Acerca de / Metodología y páginas legales).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoObtenerPaginaInstitucional()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerPaginaInstitucional$Response(params: PublicoObtenerPaginaInstitucional$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaInstitucionalPublica>> {
    const obs = publicoObtenerPaginaInstitucional(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Página institucional (Acerca de / Metodología y páginas legales).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoObtenerPaginaInstitucional$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoObtenerPaginaInstitucional(params: PublicoObtenerPaginaInstitucional$Params, context?: HttpContext): Promise<PaginaInstitucionalPublica> {
    const resp = this.publicoObtenerPaginaInstitucional$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaInstitucionalPublica>): PaginaInstitucionalPublica => r.body);
  }

}
