/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaginaCreditoMedio } from '../models/pagina-credito-medio';
import { PaginaTerminoGlosarioPublico } from '../models/pagina-termino-glosario-publico';
import { publicoListarCreditos } from '../fn/publico-glosario-creditos/publico-listar-creditos';
import { PublicoListarCreditos$Params } from '../fn/publico-glosario-creditos/publico-listar-creditos';
import { publicoListarGlosario } from '../fn/publico-glosario-creditos/publico-listar-glosario';
import { PublicoListarGlosario$Params } from '../fn/publico-glosario-creditos/publico-listar-glosario';

@Injectable({ providedIn: 'root' })
export class PublicoGlosarioCreditosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicoListarGlosario()` */
  static readonly PublicoListarGlosarioPath = '/api/v1/publico/glosario';

  /**
   * Términos publicados en orden alfabético español.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoListarGlosario()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarGlosario$Response(params?: PublicoListarGlosario$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaTerminoGlosarioPublico>> {
    const obs = publicoListarGlosario(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Términos publicados en orden alfabético español.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoListarGlosario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarGlosario(params?: PublicoListarGlosario$Params, context?: HttpContext): Promise<PaginaTerminoGlosarioPublico> {
    const resp = this.publicoListarGlosario$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaTerminoGlosarioPublico>): PaginaTerminoGlosarioPublico => r.body);
  }

  /** Path part for operation `publicoListarCreditos()` */
  static readonly PublicoListarCreditosPath = '/api/v1/publico/creditos';

  /**
   * Créditos de los medios usados en contenido publicado.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicoListarCreditos()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarCreditos$Response(params?: PublicoListarCreditos$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginaCreditoMedio>> {
    const obs = publicoListarCreditos(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Créditos de los medios usados en contenido publicado.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicoListarCreditos$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publicoListarCreditos(params?: PublicoListarCreditos$Params, context?: HttpContext): Promise<PaginaCreditoMedio> {
    const resp = this.publicoListarCreditos$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginaCreditoMedio>): PaginaCreditoMedio => r.body);
  }

}
