/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { EstadoSalud } from '../models/estado-salud';
import { saludLive } from '../fn/salud/salud-live';
import { SaludLive$Params } from '../fn/salud/salud-live';
import { saludReady } from '../fn/salud/salud-ready';
import { SaludReady$Params } from '../fn/salud/salud-ready';


/**
 * Liveness y readiness (FEAT-048).
 */
@Injectable({ providedIn: 'root' })
export class SaludService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saludLive()` */
  static readonly SaludLivePath = '/health/live';

  /**
   * Proceso vivo.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saludLive()` instead.
   *
   * This method doesn't expect any request body.
   */
  saludLive$Response(params?: SaludLive$Params, context?: HttpContext): Promise<StrictHttpResponse<EstadoSalud>> {
    const obs = saludLive(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Proceso vivo.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saludLive$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  saludLive(params?: SaludLive$Params, context?: HttpContext): Promise<EstadoSalud> {
    const resp = this.saludLive$Response(params, context);
    return resp.then((r: StrictHttpResponse<EstadoSalud>): EstadoSalud => r.body);
  }

  /** Path part for operation `saludReady()` */
  static readonly SaludReadyPath = '/health/ready';

  /**
   * Dependencias alcanzables (BD y, si existe, broker).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saludReady()` instead.
   *
   * This method doesn't expect any request body.
   */
  saludReady$Response(params?: SaludReady$Params, context?: HttpContext): Promise<StrictHttpResponse<EstadoSalud>> {
    const obs = saludReady(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Dependencias alcanzables (BD y, si existe, broker).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saludReady$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  saludReady(params?: SaludReady$Params, context?: HttpContext): Promise<EstadoSalud> {
    const resp = this.saludReady$Response(params, context);
    return resp.then((r: StrictHttpResponse<EstadoSalud>): EstadoSalud => r.body);
  }

}
