# Generated by Django 5.2.17 on 2026-09-26 03:57

import django.contrib.postgres.fields
import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # app.f_normalizar (titulo_norm, SEO único) y app.f_sin_duplicados (CHECK de meses).
        ('busqueda', '0001_extensiones_funciones'),
        ('catalogos', '0001_inicial'),
        ('cuentas', '0001_inicial'),
        ('medios', '0001_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('grupo', models.CharField(blank=True, max_length=60, null=True)),
                ('esencial', models.BooleanField(db_default=False, default=False)),
                ('orden', models.SmallIntegerField(db_default=0, default=0)),
            ],
            options={
                'db_table': 'checklist_item',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DESTINO', 'Destino'), ('ITINERARIO', 'Itinerario'), ('GUIA', 'Guía'), ('TIPO', 'Tipo de aventura'), ('COLECCION', 'Colección'), ('TERMINO', 'Término de glosario'), ('PAGINA', 'Página institucional')], max_length=10)),
                ('slug', models.CharField(max_length=120)),
                ('titulo', models.CharField(db_collation='es-x-icu', max_length=150)),
                ('titulo_norm', models.GeneratedField(db_persist=True, expression=models.Func('titulo', function='app.f_normalizar', output_field=models.CharField(max_length=150)), output_field=models.CharField(max_length=150))),
                ('estado_editorial', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('RETIRADO', 'Retirado')], db_default='BORRADOR', default='BORRADOR', max_length=10)),
                ('fecha_ultima_revision', models.DateField(blank=True, null=True)),
                ('seo_titulo', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_descripcion', models.CharField(blank=True, max_length=160, null=True)),
                ('primera_publicacion_en', models.DateTimeField(blank=True, null=True)),
                ('publicado_actualizado_en', models.DateTimeField(blank=True, null=True)),
                ('retirado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_retiro', models.CharField(blank=True, max_length=300, null=True)),
                ('creado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('actualizado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('version', models.IntegerField(db_default=1, default=1)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.cuentastaff')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.cuentastaff')),
                ('portada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medios.medio')),
            ],
            options={
                'db_table': 'contenido',
            },
        ),
        migrations.CreateModel(
            name='DestinoTipoAventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'destino_tipo_aventura',
            },
        ),
        migrations.CreateModel(
            name='DiaItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dia', models.SmallIntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('actividades', models.TextField()),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('desnivel_positivo_m', models.IntegerField(blank=True, null=True)),
                ('desnivel_negativo_m', models.IntegerField(blank=True, null=True)),
                ('alojamiento_orientativo', models.CharField(blank=True, max_length=300, null=True)),
                ('consejos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dia_itinerario',
            },
        ),
        migrations.CreateModel(
            name='GuiaDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'guia_destino',
            },
        ),
        migrations.CreateModel(
            name='GuiaTipoAventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'guia_tipo_aventura',
            },
        ),
        migrations.CreateModel(
            name='ItinerarioTipoAventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'itinerario_tipo_aventura',
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('contenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coleccion', serialize=False, to='contenido.contenido')),
                ('tipo_contenido', models.CharField(db_default='COLECCION', default='COLECCION', editable=False, max_length=10)),
                ('resumen', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coleccion',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('contenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='destino', serialize=False, to='contenido.contenido')),
                ('tipo_contenido', models.CharField(db_default='DESTINO', default='DESTINO', editable=False, max_length=10)),
                ('resumen', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion_experta', models.TextField(blank=True, null=True)),
                ('dificultad', models.SmallIntegerField(blank=True, null=True)),
                ('meses_mejor_epoca', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), db_default=[], default=list, size=None)),
                ('duracion_min_dias', models.SmallIntegerField(blank=True, null=True)),
                ('duracion_max_dias', models.SmallIntegerField(blank=True, null=True)),
                ('nivel_presupuesto', models.SmallIntegerField(blank=True, null=True)),
                ('clima', models.TextField(blank=True, null=True)),
                ('altitud_max_m', models.IntegerField(blank=True, null=True)),
                ('como_llegar', models.TextField(blank=True, null=True)),
                ('seguridad_riesgos', models.TextField(blank=True, null=True)),
                ('sostenibilidad', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'destino',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('contenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guia', serialize=False, to='contenido.contenido')),
                ('tipo_contenido', models.CharField(db_default='GUIA', default='GUIA', editable=False, max_length=10)),
                ('resumen', models.CharField(blank=True, max_length=300, null=True)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('remite_a_metodologia', models.BooleanField(db_default=False, default=False)),
                ('palabras', models.IntegerField(db_default=0, default=0)),
            ],
            options={
                'db_table': 'guia',
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('contenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='itinerario', serialize=False, to='contenido.contenido')),
                ('tipo_contenido', models.CharField(db_default='ITINERARIO', default='ITINERARIO', editable=False, max_length=10)),
                ('resumen', models.CharField(blank=True, max_length=300, null=True)),
                ('duracion_dias', models.SmallIntegerField(blank=True, null=True)),
                ('dificultad', models.SmallIntegerField(blank=True, null=True)),
                ('distancia_total_km', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('desnivel_acumulado_m', models.IntegerField(blank=True, null=True)),
                ('riesgos_seguridad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itinerario',
            },
        ),
        migrations.CreateModel(
            name='PaginaInstitucional',
            fields=[
                ('contenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pagina', serialize=False, to='contenido.contenido')),
                ('tipo_contenido', models.CharField(db_default='PAGINA', default='PAGINA', editable=False, max_length=10)),
                ('clave', models.CharField(choices=[('ACERCA_DE', 'Acerca de'), ('POLITICA_DATOS', 'Política de datos'), ('POLITICA_COOKIES', 'Política de cookies'), ('AVISO_LEGAL', 'Aviso legal')], max_length=20, unique=True)),
                ('cuerpo', models.TextField()),
                ('version_documento', models.CharField(max_length=20)),
                ('vigente_desde', models.DateField()),
            ],
            options={
                'db_table': 'pagina_institucional',
            },
        ),
        migrations.CreateModel(
            name='TerminoGlosario',
            fields=[
                ('contenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='termino_glosario', serialize=False, to='contenido.contenido')),
                ('tipo_contenido', models.CharField(db_default='TERMINO', default='TERMINO', editable=False, max_length=10)),
                ('definicion', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'db_table': 'termino_glosario',
            },
        ),
        migrations.CreateModel(
            name='TipoAventura',
            fields=[
                ('contenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tipo_aventura', serialize=False, to='contenido.contenido')),
                ('tipo_contenido', models.CharField(db_default='TIPO', default='TIPO', editable=False, max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('resumen', models.CharField(blank=True, max_length=300, null=True)),
                ('nivel_exigencia', models.SmallIntegerField(blank=True, null=True)),
                ('orden', models.SmallIntegerField(db_default=0, default=0)),
            ],
            options={
                'db_table': 'tipo_aventura',
            },
        ),
        migrations.CreateModel(
            name='ContenidoMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('DESTINO', 'Destino'), ('ITINERARIO', 'Itinerario'), ('GUIA', 'Guía'), ('TIPO', 'Tipo de aventura'), ('COLECCION', 'Colección'), ('TERMINO', 'Término de glosario'), ('PAGINA', 'Página institucional')], max_length=10)),
                ('orden', models.SmallIntegerField(db_default=0, default=0)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='contenido.contenido')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medios.medio')),
            ],
            options={
                'db_table': 'contenido_medio',
            },
        ),
        migrations.CreateModel(
            name='ContenidoTermino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('DESTINO', 'Destino'), ('ITINERARIO', 'Itinerario'), ('GUIA', 'Guía'), ('TIPO', 'Tipo de aventura'), ('COLECCION', 'Colección'), ('TERMINO', 'Término de glosario'), ('PAGINA', 'Página institucional')], max_length=10)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminos', to='contenido.contenido')),
            ],
            options={
                'db_table': 'contenido_termino',
            },
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('entidad_editora', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('orden', models.SmallIntegerField(db_default=0, default=0)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes', to='contenido.contenido')),
            ],
            options={
                'db_table': 'fuente',
            },
        ),
        migrations.CreateModel(
            name='RelacionContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_tipo', models.CharField(choices=[('DESTINO', 'Destino'), ('ITINERARIO', 'Itinerario'), ('GUIA', 'Guía'), ('TIPO', 'Tipo de aventura'), ('COLECCION', 'Colección'), ('TERMINO', 'Término de glosario'), ('PAGINA', 'Página institucional')], max_length=10)),
                ('relacionado_tipo', models.CharField(choices=[('DESTINO', 'Destino'), ('ITINERARIO', 'Itinerario'), ('GUIA', 'Guía'), ('TIPO', 'Tipo de aventura'), ('COLECCION', 'Colección'), ('TERMINO', 'Término de glosario'), ('PAGINA', 'Página institucional')], max_length=10)),
                ('orden', models.SmallIntegerField(db_default=0, default=0)),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionados', to='contenido.contenido')),
                ('relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionado_desde', to='contenido.contenido')),
            ],
            options={
                'db_table': 'relacion_contenido',
            },
        ),
        migrations.CreateModel(
            name='ElementoColeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('DESTINO', 'Destino'), ('ITINERARIO', 'Itinerario'), ('GUIA', 'Guía'), ('TIPO', 'Tipo de aventura'), ('COLECCION', 'Colección'), ('TERMINO', 'Término de glosario'), ('PAGINA', 'Página institucional')], max_length=10)),
                ('orden', models.SmallIntegerField(db_default=0, default=0)),
                ('nota_editorial', models.CharField(blank=True, max_length=300, null=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_de_coleccion', to='contenido.contenido')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='contenido.coleccion')),
            ],
            options={
                'db_table': 'elemento_coleccion',
            },
        ),
        migrations.AddConstraint(
            model_name='coleccion',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_contenido', 'COLECCION')), name='ck_coleccion_tipo_contenido'),
        ),
        migrations.AddConstraint(
            model_name='coleccion',
            constraint=models.CheckConstraint(condition=models.Q(('descripcion__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('descripcion'), 100000), _connector='OR'), name='ck_coleccion_descripcion_longitud'),
        ),
        migrations.AddField(
            model_name='guiadestino',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenido.destino'),
        ),
        migrations.AddField(
            model_name='destinotipoaventura',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenido.destino'),
        ),
        migrations.AddField(
            model_name='destino',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='catalogos.pais'),
        ),
        migrations.AddField(
            model_name='guiatipoaventura',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenido.guia'),
        ),
        migrations.AddField(
            model_name='guiadestino',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenido.guia'),
        ),
        migrations.AddField(
            model_name='guia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='catalogos.categoriaguia'),
        ),
        migrations.AddField(
            model_name='guia',
            name='destinos',
            field=models.ManyToManyField(related_name='guias', through='contenido.GuiaDestino', to='contenido.destino'),
        ),
        migrations.AddField(
            model_name='itinerariotipoaventura',
            name='itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenido.itinerario'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itinerarios', to='contenido.destino'),
        ),
        migrations.AddField(
            model_name='diaitinerario',
            name='itinerario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='contenido.itinerario'),
        ),
        migrations.AddConstraint(
            model_name='paginainstitucional',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_contenido', 'PAGINA')), name='ck_pagina_institucional_tipo_contenido'),
        ),
        migrations.AddConstraint(
            model_name='paginainstitucional',
            constraint=models.CheckConstraint(condition=models.Q(('clave__in', ['ACERCA_DE', 'POLITICA_DATOS', 'POLITICA_COOKIES', 'AVISO_LEGAL'])), name='ck_pagina_institucional_clave'),
        ),
        migrations.AddConstraint(
            model_name='paginainstitucional',
            constraint=models.CheckConstraint(condition=models.Q(('cuerpo__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('cuerpo'), 100000), _connector='OR'), name='ck_pagina_institucional_cuerpo_longitud'),
        ),
        migrations.AddConstraint(
            model_name='terminoglosario',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_contenido', 'TERMINO')), name='ck_termino_glosario_tipo_contenido'),
        ),
        migrations.AddField(
            model_name='contenidotermino',
            name='termino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='contenido.terminoglosario'),
        ),
        migrations.AddConstraint(
            model_name='tipoaventura',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_contenido', 'TIPO')), name='ck_tipo_aventura_tipo_contenido'),
        ),
        migrations.AddConstraint(
            model_name='tipoaventura',
            constraint=models.CheckConstraint(condition=models.Q(('descripcion__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('descripcion'), 100000), _connector='OR'), name='ck_tipo_aventura_descripcion_longitud'),
        ),
        migrations.AddConstraint(
            model_name='tipoaventura',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_exigencia__isnull', True), models.Q(('nivel_exigencia__gte', 1), ('nivel_exigencia__lte', 5)), _connector='OR'), name='ck_tipo_aventura_nivel_exigencia'),
        ),
        migrations.AddField(
            model_name='itinerariotipoaventura',
            name='tipo_aventura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenido.tipoaventura'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='tipos_aventura',
            field=models.ManyToManyField(related_name='itinerarios', through='contenido.ItinerarioTipoAventura', to='contenido.tipoaventura'),
        ),
        migrations.AddField(
            model_name='guiatipoaventura',
            name='tipo_aventura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenido.tipoaventura'),
        ),
        migrations.AddField(
            model_name='guia',
            name='tipos_aventura',
            field=models.ManyToManyField(related_name='guias', through='contenido.GuiaTipoAventura', to='contenido.tipoaventura'),
        ),
        migrations.AddField(
            model_name='destinotipoaventura',
            name='tipo_aventura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenido.tipoaventura'),
        ),
        migrations.AddField(
            model_name='destino',
            name='tipo_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinos_principales', to='contenido.tipoaventura'),
        ),
        migrations.AddField(
            model_name='destino',
            name='tipos_aventura',
            field=models.ManyToManyField(related_name='destinos', through='contenido.DestinoTipoAventura', to='contenido.tipoaventura'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='tipo_aventura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='contenido.tipoaventura'),
        ),
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(condition=models.Q(('estado_editorial', 'PUBLICADO')), fields=['tipo', 'titulo'], name='ix_contenido_pub_titulo'),
        ),
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(models.F('tipo'), models.OrderBy(models.F('fecha_ultima_revision'), descending=True), condition=models.Q(('estado_editorial', 'PUBLICADO')), name='ix_contenido_pub_revision'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['DESTINO', 'ITINERARIO', 'GUIA', 'TIPO', 'COLECCION', 'TERMINO', 'PAGINA'])), name='ck_contenido_tipo'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]+(-[a-z0-9]+)*$')), name='ck_contenido_slug'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(('estado_editorial__in', ['BORRADOR', 'PUBLICADO', 'RETIRADO'])), name='ck_contenido_estado_editorial'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ck_contenido_version'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.UniqueConstraint(fields=('tipo', 'slug'), name='uq_contenido_tipo_slug'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.UniqueConstraint(fields=('tipo', 'titulo_norm'), name='uq_contenido_tipo_titulo_norm'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.UniqueConstraint(fields=('id', 'tipo'), name='uq_contenido_id_tipo'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.UniqueConstraint(models.Func('seo_descripcion', function='app.f_normalizar', output_field=models.CharField(max_length=150)), condition=models.Q(('estado_editorial', 'PUBLICADO'), ('seo_descripcion__isnull', False)), name='uq_contenido_seo_publicado'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_editorial', 'PUBLICADO'), _negated=True), models.Q(('fecha_ultima_revision__isnull', False), ('primera_publicacion_en__isnull', False), ('publicado_actualizado_en__isnull', False)), _connector='OR'), name='ck_contenido_publicado_fechas'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_editorial', 'PUBLICADO'), _negated=True), ('tipo', 'TERMINO'), ('seo_descripcion__isnull', False), _connector='OR'), name='ck_contenido_publicado_seo'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_editorial', 'PUBLICADO'), _negated=True), ('tipo__in', ['TERMINO', 'PAGINA']), ('portada__isnull', False), _connector='OR'), name='ck_contenido_publicado_portada'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_editorial', 'RETIRADO'), _negated=True), models.Q(('motivo_retiro__isnull', False), ('primera_publicacion_en__isnull', False), ('retirado_en__isnull', False)), _connector='OR'), name='ck_contenido_retirado'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'PAGINA'), _negated=True), models.Q(('estado_editorial', 'RETIRADO'), _negated=True), _connector='OR'), name='ck_contenido_pagina_no_retirable'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo__in', ['TERMINO', 'PAGINA']), _negated=True), ('portada__isnull', True), _connector='OR'), name='ck_contenido_sin_portada'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'TERMINO'), _negated=True), models.Q(('seo_descripcion__isnull', True), ('seo_titulo__isnull', True)), _connector='OR'), name='ck_contenido_termino_sin_seo'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(condition=models.Q(('publicado_actualizado_en__isnull', True), ('primera_publicacion_en__lte', models.F('publicado_actualizado_en')), _connector='OR'), name='ck_contenido_orden_publicacion'),
        ),
        migrations.AddConstraint(
            model_name='contenidomedio',
            constraint=models.UniqueConstraint(fields=('contenido', 'medio'), name='uq_contenido_medio'),
        ),
        migrations.AddConstraint(
            model_name='contenidomedio',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_contenido__in', ['DESTINO', 'ITINERARIO', 'GUIA', 'TIPO', 'COLECCION'])), name='ck_contenido_medio_tipo_contenido'),
        ),
        migrations.AddConstraint(
            model_name='fuente',
            constraint=models.CheckConstraint(condition=models.Q(('url__isnull', True), ('url__regex', '^(https?://|/)'), _connector='OR'), name='ck_fuente_url'),
        ),
        migrations.AddConstraint(
            model_name='relacioncontenido',
            constraint=models.UniqueConstraint(fields=('origen', 'relacionado'), name='uq_relacion_contenido'),
        ),
        migrations.AddConstraint(
            model_name='relacioncontenido',
            constraint=models.CheckConstraint(condition=models.Q(('origen', models.F('relacionado')), _negated=True), name='ck_relacion_contenido_distintos'),
        ),
        migrations.AddConstraint(
            model_name='relacioncontenido',
            constraint=models.CheckConstraint(condition=models.Q(('origen_tipo__in', ['DESTINO', 'ITINERARIO', 'GUIA', 'TIPO', 'COLECCION'])), name='ck_relacion_contenido_origen_tipo'),
        ),
        migrations.AddConstraint(
            model_name='relacioncontenido',
            constraint=models.CheckConstraint(condition=models.Q(('relacionado_tipo__in', ['DESTINO', 'ITINERARIO', 'GUIA', 'TIPO', 'COLECCION'])), name='ck_relacion_contenido_relacionado_tipo'),
        ),
        migrations.AddConstraint(
            model_name='elementocoleccion',
            constraint=models.UniqueConstraint(fields=('coleccion', 'contenido'), name='uq_elemento_coleccion'),
        ),
        migrations.AddConstraint(
            model_name='elementocoleccion',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_contenido__in', ['DESTINO', 'ITINERARIO'])), name='ck_elemento_coleccion_tipo_contenido'),
        ),
        migrations.AddConstraint(
            model_name='guiadestino',
            constraint=models.UniqueConstraint(fields=('guia', 'destino'), name='uq_guia_destino'),
        ),
        migrations.AddConstraint(
            model_name='diaitinerario',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('itinerario', 'numero_dia'), name='uq_dia_itinerario_numero'),
        ),
        migrations.AddConstraint(
            model_name='diaitinerario',
            constraint=models.CheckConstraint(condition=models.Q(('numero_dia__isnull', True), models.Q(('numero_dia__gte', 1), ('numero_dia__lte', 60)), _connector='OR'), name='ck_dia_itinerario_numero_dia'),
        ),
        migrations.AddConstraint(
            model_name='diaitinerario',
            constraint=models.CheckConstraint(condition=models.Q(('actividades__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('actividades'), 100000), _connector='OR'), name='ck_dia_itinerario_actividades_longitud'),
        ),
        migrations.AddConstraint(
            model_name='diaitinerario',
            constraint=models.CheckConstraint(condition=models.Q(('consejos__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('consejos'), 100000), _connector='OR'), name='ck_dia_itinerario_consejos_longitud'),
        ),
        migrations.AddConstraint(
            model_name='diaitinerario',
            constraint=models.CheckConstraint(condition=models.Q(('distancia_km__isnull', True), ('distancia_km__gte', 0), _connector='OR'), name='ck_dia_itinerario_distancia_km'),
        ),
        migrations.AddConstraint(
            model_name='diaitinerario',
            constraint=models.CheckConstraint(condition=models.Q(('desnivel_positivo_m__isnull', True), ('desnivel_positivo_m__gte', 0), _connector='OR'), name='ck_dia_itinerario_desnivel_positivo_m'),
        ),
        migrations.AddConstraint(
            model_name='diaitinerario',
            constraint=models.CheckConstraint(condition=models.Q(('desnivel_negativo_m__isnull', True), ('desnivel_negativo_m__gte', 0), _connector='OR'), name='ck_dia_itinerario_desnivel_negativo_m'),
        ),
        migrations.AddConstraint(
            model_name='contenidotermino',
            constraint=models.UniqueConstraint(fields=('contenido', 'termino'), name='uq_contenido_termino'),
        ),
        migrations.AddConstraint(
            model_name='contenidotermino',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_contenido__in', ['DESTINO', 'ITINERARIO', 'GUIA', 'TIPO'])), name='ck_contenido_termino_tipo_contenido'),
        ),
        migrations.AddConstraint(
            model_name='itinerariotipoaventura',
            constraint=models.UniqueConstraint(fields=('itinerario', 'tipo_aventura'), name='uq_itinerario_tipo_aventura'),
        ),
        migrations.AddConstraint(
            model_name='itinerario',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_contenido', 'ITINERARIO')), name='ck_itinerario_tipo_contenido'),
        ),
        migrations.AddConstraint(
            model_name='itinerario',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_dias__isnull', True), models.Q(('duracion_dias__gte', 1), ('duracion_dias__lte', 60)), _connector='OR'), name='ck_itinerario_duracion_dias'),
        ),
        migrations.AddConstraint(
            model_name='itinerario',
            constraint=models.CheckConstraint(condition=models.Q(('dificultad__isnull', True), models.Q(('dificultad__gte', 1), ('dificultad__lte', 5)), _connector='OR'), name='ck_itinerario_dificultad'),
        ),
        migrations.AddConstraint(
            model_name='itinerario',
            constraint=models.CheckConstraint(condition=models.Q(('distancia_total_km__isnull', True), ('distancia_total_km__gte', 0), _connector='OR'), name='ck_itinerario_distancia_total_km'),
        ),
        migrations.AddConstraint(
            model_name='itinerario',
            constraint=models.CheckConstraint(condition=models.Q(('desnivel_acumulado_m__isnull', True), ('desnivel_acumulado_m__gte', 0), _connector='OR'), name='ck_itinerario_desnivel_acumulado_m'),
        ),
        migrations.AddConstraint(
            model_name='itinerario',
            constraint=models.CheckConstraint(condition=models.Q(('riesgos_seguridad__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('riesgos_seguridad'), 100000), _connector='OR'), name='ck_itinerario_riesgos_seguridad_longitud'),
        ),
        migrations.AddConstraint(
            model_name='guiatipoaventura',
            constraint=models.UniqueConstraint(fields=('guia', 'tipo_aventura'), name='uq_guia_tipo_aventura'),
        ),
        migrations.AddConstraint(
            model_name='guia',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_contenido', 'GUIA')), name='ck_guia_tipo_contenido'),
        ),
        migrations.AddConstraint(
            model_name='guia',
            constraint=models.CheckConstraint(condition=models.Q(('cuerpo__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('cuerpo'), 100000), _connector='OR'), name='ck_guia_cuerpo_longitud'),
        ),
        migrations.AddConstraint(
            model_name='guia',
            constraint=models.CheckConstraint(condition=models.Q(('palabras__gte', 0)), name='ck_guia_palabras'),
        ),
        migrations.AddConstraint(
            model_name='destinotipoaventura',
            constraint=models.UniqueConstraint(fields=('destino', 'tipo_aventura'), name='uq_destino_tipo_aventura'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_contenido', 'DESTINO')), name='ck_destino_tipo_contenido'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('descripcion_experta__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('descripcion_experta'), 100000), _connector='OR'), name='ck_destino_descripcion_experta_longitud'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('clima__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('clima'), 100000), _connector='OR'), name='ck_destino_clima_longitud'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('como_llegar__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('como_llegar'), 100000), _connector='OR'), name='ck_destino_como_llegar_longitud'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('seguridad_riesgos__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('seguridad_riesgos'), 100000), _connector='OR'), name='ck_destino_seguridad_riesgos_longitud'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('sostenibilidad__isnull', True), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('sostenibilidad'), 100000), _connector='OR'), name='ck_destino_sostenibilidad_longitud'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('dificultad__isnull', True), models.Q(('dificultad__gte', 1), ('dificultad__lte', 5)), _connector='OR'), name='ck_destino_dificultad'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_min_dias__isnull', True), models.Q(('duracion_min_dias__gte', 1), ('duracion_min_dias__lte', 90)), _connector='OR'), name='ck_destino_duracion_min_dias'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_max_dias__isnull', True), models.Q(('duracion_max_dias__gte', 1), ('duracion_max_dias__lte', 90)), _connector='OR'), name='ck_destino_duracion_max_dias'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_presupuesto__isnull', True), models.Q(('nivel_presupuesto__gte', 1), ('nivel_presupuesto__lte', 4)), _connector='OR'), name='ck_destino_nivel_presupuesto'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('altitud_max_m__isnull', True), models.Q(('altitud_max_m__gte', -500), ('altitud_max_m__lte', 9000)), _connector='OR'), name='ck_destino_altitud_max_m'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__isnull', True), models.Q(('latitud__gte', -90), ('latitud__lte', 90)), _connector='OR'), name='ck_destino_latitud'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__isnull', True), models.Q(('longitud__gte', -180), ('longitud__lte', 180)), _connector='OR'), name='ck_destino_longitud'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('meses_mejor_epoca__contained_by', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]), models.Func(models.F('meses_mejor_epoca'), function='app.f_sin_duplicados', output_field=models.BooleanField())), name='ck_destino_meses_mejor_epoca'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_min_dias__isnull', True), ('duracion_max_dias__isnull', True), ('duracion_min_dias__lte', models.F('duracion_max_dias')), _connector='OR'), name='ck_destino_duracion'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitud__isnull', True), ('longitud__isnull', True)), models.Q(('latitud__isnull', False), ('longitud__isnull', False)), _connector='OR'), name='ck_destino_coordenadas'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('tipo_aventura', 'texto'), name='uq_checklist_item'),
        ),
    ]
