# Generated by Django 5.2.17 on 2026-09-27 18:10 (makemigrations --empty + RunSQL)

# CHG-DB-002 (DB_HANDOFF v1.2, plan n=17, DEC-AUTO-203): no se borra directamente la fila de
# subtipo 1:1 de un contenido publicado alguna vez ni la de una página institucional (dejaría el
# supertipo huérfano). El borrado de borradores nunca publicados (FEAT-038) sigue permitido: el
# Collector de Django borra el subtipo con el padre aún en BORRADOR y, en la cascada SQL
# ON DELETE CASCADE, el padre ya no es visible. app_rw conserva DELETE en los subtipos.
# Patrón expand, reversible sin pérdida de datos.
from django.db import migrations

SUBTIPOS = (
    "tipo_aventura",
    "destino",
    "itinerario",
    "guia",
    "coleccion",
    "termino_glosario",
    "pagina_institucional",
)

FN_SUBTIPO_GUARDA_BORRADO = """
CREATE FUNCTION app.fn_subtipo_guarda_borrado() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, app, pg_temp
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM app.contenido c
              WHERE c.id = OLD.contenido_id
                AND (c.primera_publicacion_en IS NOT NULL OR c.tipo = 'PAGINA')) THEN
    RAISE EXCEPTION 'No se borra el subtipo de un contenido publicado alguna vez o de una página (contenido %)', OLD.contenido_id
      USING ERRCODE = 'restrict_violation', CONSTRAINT = 'trg_subtipo_guarda_borrado';
  END IF;
  RETURN OLD;
END
$$;
"""

TRIGGERS = "\n".join(
    f"CREATE TRIGGER trg_subtipo_guarda_borrado BEFORE DELETE ON app.{tabla} "
    "FOR EACH ROW EXECUTE FUNCTION app.fn_subtipo_guarda_borrado();"
    for tabla in SUBTIPOS
)

REVERSO_TRIGGERS = "\n".join(
    f"DROP TRIGGER trg_subtipo_guarda_borrado ON app.{tabla};" for tabla in SUBTIPOS
)


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_integridad_sql'),
    ]

    operations = [
        migrations.RunSQL(
            FN_SUBTIPO_GUARDA_BORRADO,
            reverse_sql="DROP FUNCTION app.fn_subtipo_guarda_borrado();",
        ),
        migrations.RunSQL(TRIGGERS, reverse_sql=REVERSO_TRIGGERS),
    ]
