/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItinerarioDetalle } from '../../models/itinerario-detalle';
import { Slug } from '../../models/slug';

export interface PublicoObtenerItinerario$Params {
  slug: Slug;
}

export function publicoObtenerItinerario(http: HttpClient, rootUrl: string, params: PublicoObtenerItinerario$Params, context?: HttpContext): Observable<StrictHttpResponse<ItinerarioDetalle>> {
  const rb = new RequestBuilder(rootUrl, publicoObtenerItinerario.PATH, 'get');
  if (params) {
    rb.path('slug', params.slug, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItinerarioDetalle>;
    })
  );
}

publicoObtenerItinerario.PATH = '/api/v1/publico/itinerarios/{slug}';
