/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginaItinerarioTarjeta } from '../../models/pagina-itinerario-tarjeta';
import { Slug } from '../../models/slug';

export interface PublicoListarItinerarios$Params {

/**
 * Slug del destino (itinerarios de un destino).
 */
  destino?: Slug;
  orden?: 'titulo' | 'duracion_asc' | 'duracion_desc';

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function publicoListarItinerarios(http: HttpClient, rootUrl: string, params?: PublicoListarItinerarios$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaItinerarioTarjeta>> {
  const rb = new RequestBuilder(rootUrl, publicoListarItinerarios.PATH, 'get');
  if (params) {
    rb.query('destino', params.destino, {});
    rb.query('orden', params.orden, {});
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaItinerarioTarjeta>;
    })
  );
}

publicoListarItinerarios.PATH = '/api/v1/publico/itinerarios';
