/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginaGuiaTarjeta } from '../../models/pagina-guia-tarjeta';
import { Slug } from '../../models/slug';

export interface PublicoListarGuias$Params {
  categoria?: Slug;

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function publicoListarGuias(http: HttpClient, rootUrl: string, params?: PublicoListarGuias$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaGuiaTarjeta>> {
  const rb = new RequestBuilder(rootUrl, publicoListarGuias.PATH, 'get');
  if (params) {
    rb.query('categoria', params.categoria, {});
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaGuiaTarjeta>;
    })
  );
}

publicoListarGuias.PATH = '/api/v1/publico/guias';
