/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoriaGuiaPublica } from '../../models/categoria-guia-publica';
import { Slug } from '../../models/slug';

export interface PublicoObtenerCategoriaGuia$Params {
  slug: Slug;
}

export function publicoObtenerCategoriaGuia(http: HttpClient, rootUrl: string, params: PublicoObtenerCategoriaGuia$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoriaGuiaPublica>> {
  const rb = new RequestBuilder(rootUrl, publicoObtenerCategoriaGuia.PATH, 'get');
  if (params) {
    rb.path('slug', params.slug, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoriaGuiaPublica>;
    })
  );
}

publicoObtenerCategoriaGuia.PATH = '/api/v1/publico/categorias-guia/{slug}';
