# Generated by Django 5.2.17 on 2026-09-26 03:57

import apps.auditoria.campos
import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_inicial'),
        ('cuentas', '0001_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocurrido_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('actor_etiqueta', models.CharField(max_length=60)),
                ('accion', models.CharField(choices=[('LOGIN_OK', 'Login Ok'), ('LOGIN_FALLIDO', 'Login Fallido'), ('BLOQUEO', 'Bloqueo'), ('LOGOUT', 'Logout'), ('AUTORIZACION_ACEPTADA', 'Autorizacion Aceptada'), ('CAMBIO_CREDENCIAL', 'Cambio Credencial'), ('MFA_ACTIVAR', 'Mfa Activar'), ('MFA_DESACTIVAR', 'Mfa Desactivar'), ('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('PUBLICAR', 'Publicar'), ('ACTUALIZAR_PUBLICACION', 'Actualizar Publicacion'), ('RETIRAR', 'Retirar'), ('REACTIVAR', 'Reactivar'), ('ELIMINAR_BORRADOR', 'Eliminar Borrador'), ('RESTAURAR_REVISION', 'Restaurar Revision'), ('SUBIR_MEDIO', 'Subir Medio'), ('EDITAR_MEDIO', 'Editar Medio'), ('RETIRAR_MEDIO', 'Retirar Medio'), ('CONFIG_INICIO', 'Config Inicio'), ('CONFIG_SITIO', 'Config Sitio'), ('TAXONOMIA', 'Taxonomia'), ('CUENTA_CREAR', 'Cuenta Crear'), ('CUENTA_ROL', 'Cuenta Rol'), ('CUENTA_RESTABLECER', 'Cuenta Restablecer'), ('CUENTA_DESACTIVAR', 'Cuenta Desactivar'), ('CUENTA_REACTIVAR', 'Cuenta Reactivar'), ('CUENTA_ANONIMIZAR', 'Cuenta Anonimizar')], max_length=30)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('FALLO', 'Fallo')], max_length=5)),
                ('tipo_entidad', models.CharField(blank=True, max_length=20, null=True)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('entidad_titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('campos_cambiados', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, null=True, size=None)),
                ('ip_truncada', apps.auditoria.campos.CampoCidr(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.cuentastaff')),
            ],
            options={
                'db_table': 'evento_auditoria',
                'indexes': [models.Index(models.OrderBy(models.F('ocurrido_en'), descending=True), name='ix_evento_auditoria_ocurrido'), models.Index(models.F('actor'), models.OrderBy(models.F('ocurrido_en'), descending=True), name='ix_evento_auditoria_actor')],
                'constraints': [models.CheckConstraint(condition=models.Q(('accion__in', ['LOGIN_OK', 'LOGIN_FALLIDO', 'BLOQUEO', 'LOGOUT', 'AUTORIZACION_ACEPTADA', 'CAMBIO_CREDENCIAL', 'MFA_ACTIVAR', 'MFA_DESACTIVAR', 'CREAR', 'EDITAR', 'PUBLICAR', 'ACTUALIZAR_PUBLICACION', 'RETIRAR', 'REACTIVAR', 'ELIMINAR_BORRADOR', 'RESTAURAR_REVISION', 'SUBIR_MEDIO', 'EDITAR_MEDIO', 'RETIRAR_MEDIO', 'CONFIG_INICIO', 'CONFIG_SITIO', 'TAXONOMIA', 'CUENTA_CREAR', 'CUENTA_ROL', 'CUENTA_RESTABLECER', 'CUENTA_DESACTIVAR', 'CUENTA_REACTIVAR', 'CUENTA_ANONIMIZAR'])), name='ck_evento_auditoria_accion'), models.CheckConstraint(condition=models.Q(('resultado__in', ['EXITO', 'FALLO'])), name='ck_evento_auditoria_resultado'), models.CheckConstraint(condition=models.Q(('ip_truncada__isnull', True), models.Q(django.db.models.lookups.Exact(models.Func(models.F('ip_truncada'), function='family', output_field=models.IntegerField()), 4), django.db.models.lookups.Exact(models.Func(models.F('ip_truncada'), function='masklen', output_field=models.IntegerField()), 24)), models.Q(django.db.models.lookups.Exact(models.Func(models.F('ip_truncada'), function='family', output_field=models.IntegerField()), 6), django.db.models.lookups.Exact(models.Func(models.F('ip_truncada'), function='masklen', output_field=models.IntegerField()), 48)), _connector='OR'), name='ck_evento_auditoria_ip_mascara'), models.CheckConstraint(condition=models.Q(('ip_truncada__isnull', True), ('accion__in', ['LOGIN_OK', 'LOGIN_FALLIDO', 'BLOQUEO', 'LOGOUT']), _connector='OR'), name='ck_evento_auditoria_ip_accion')],
            },
        ),
        migrations.CreateModel(
            name='RevisionContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('DESTINO', 'Destino'), ('ITINERARIO', 'Itinerario'), ('GUIA', 'Guía'), ('TIPO', 'Tipo de aventura'), ('COLECCION', 'Colección'), ('TERMINO', 'Término de glosario'), ('PAGINA', 'Página institucional')], max_length=10)),
                ('numero_revision', models.IntegerField()),
                ('motivo', models.CharField(choices=[('PUBLICACION', 'Publicación'), ('ACTUALIZACION', 'Actualización'), ('RETIRO', 'Retiro'), ('RESTAURACION', 'Restauración')], max_length=14)),
                ('instantanea', models.JSONField()),
                ('creado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones', to='contenido.contenido')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.cuentastaff')),
            ],
            options={
                'db_table': 'revision_contenido',
                'constraints': [models.UniqueConstraint(fields=('contenido', 'numero_revision'), name='uq_revision_contenido_numero'), models.CheckConstraint(condition=models.Q(('numero_revision__gte', 1)), name='ck_revision_contenido_numero'), models.CheckConstraint(condition=models.Q(('motivo__in', ['PUBLICACION', 'ACTUALIZACION', 'RETIRO', 'RESTAURACION'])), name='ck_revision_contenido_motivo')],
            },
        ),
        # FK compuesta de la revisión (ADR-DB-002 §3, DATA-026): ON DELETE RESTRICT, de modo que
        # un contenido con revisiones (publicado alguna vez) no puede borrarse.
        migrations.RunSQL(
            "ALTER TABLE app.revision_contenido ADD CONSTRAINT fk_revision_contenido_contenido_tipo "
            "FOREIGN KEY (contenido_id, tipo_contenido) REFERENCES app.contenido (id, tipo) "
            "ON DELETE RESTRICT;",
            reverse_sql="ALTER TABLE app.revision_contenido DROP CONSTRAINT fk_revision_contenido_contenido_tipo;",
        ),
    ]
