# Generated by Django 5.2.17 on 2026-09-26 05:18 (makemigrations --empty + RunSQL)

# CHG-DB-002 (DB_HANDOFF v1.2, OBS-QA003-05): endurecimiento de la auditoría.
# (1) Las funciones SECURITY DEFINER fijan pg_temp al FINAL del search_path, para que un objeto
#     temporal del llamante no pueda suplantar a uno de pg_catalog o app.
# (2) revision_contenido es inmutable también para el propietario (trigger BEFORE UPDATE OR
#     DELETE), además del REVOKE UPDATE, DELETE a app_rw de la migración 0002.
# Patrón expand, reversible (el reverso vuelve a la situación de DB_HANDOFF v1.1).
from django.db import migrations

SEARCH_PATH_SEGURO = """
ALTER FUNCTION app.fn_auditoria_purgar() SET search_path = pg_catalog, app, pg_temp;
ALTER FUNCTION app.fn_auditoria_seudonimizar(bigint) SET search_path = pg_catalog, app, pg_temp;
"""

REVERSO_SEARCH_PATH_SEGURO = """
ALTER FUNCTION app.fn_auditoria_purgar() SET search_path = pg_catalog, app;
ALTER FUNCTION app.fn_auditoria_seudonimizar(bigint) SET search_path = pg_catalog, app;
"""

TRG_REVISION_INMUTABLE = """
CREATE FUNCTION app.fn_revision_inmutable() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, app, pg_temp
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Las revisiones de contenido no se borran (id %)', OLD.id
      USING ERRCODE = 'restrict_violation', CONSTRAINT = 'trg_revision_inmutable';
  END IF;
  RAISE EXCEPTION 'Las revisiones de contenido son inmutables (id %)', OLD.id
    USING ERRCODE = 'check_violation', CONSTRAINT = 'trg_revision_inmutable';
END
$$;
CREATE TRIGGER trg_revision_inmutable
  BEFORE UPDATE OR DELETE ON app.revision_contenido
  FOR EACH ROW EXECUTE FUNCTION app.fn_revision_inmutable();
"""

REVERSO_TRG_REVISION_INMUTABLE = """
DROP TRIGGER trg_revision_inmutable ON app.revision_contenido;
DROP FUNCTION app.fn_revision_inmutable();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_inmutabilidad'),
    ]

    operations = [
        migrations.RunSQL(SEARCH_PATH_SEGURO, reverse_sql=REVERSO_SEARCH_PATH_SEGURO),
        migrations.RunSQL(TRG_REVISION_INMUTABLE, reverse_sql=REVERSO_TRG_REVISION_INMUTABLE),
    ]
