# Generated by Django 5.2.17 on 2026-09-26 03:57

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

# Defensa en profundidad de RULE-015/AC-108: al confirmar, debe quedar al menos una cuenta
# ADMINISTRADOR no desactivada ni anonimizada. Solo se evalúa cuando la fila modificada ERA un
# administrador operativo (WHEN), que es el único caso en que puede "dejar de quedar" uno.
# La regla estricta (>= 1 ACTIVA, no auto-degradarse) es del servicio de cuentas (TKT-004).
TRG_CUENTA_ADMIN_MINIMO = """
CREATE FUNCTION app.fn_cuenta_admin_minimo() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, app
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM app.cuenta_staff
     WHERE rol = 'ADMINISTRADOR'
       AND estado IN ('PENDIENTE_ACTIVACION', 'ACTIVA', 'BLOQUEADA_TEMPORAL')
  ) THEN
    RAISE EXCEPTION 'Debe quedar al menos una cuenta ADMINISTRADOR operativa'
      USING ERRCODE = 'check_violation', CONSTRAINT = 'trg_cuenta_admin_minimo';
  END IF;
  RETURN NULL;
END
$$;
CREATE CONSTRAINT TRIGGER trg_cuenta_admin_minimo
  AFTER UPDATE OF rol, estado ON app.cuenta_staff
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  WHEN (OLD.rol = 'ADMINISTRADOR'
        AND OLD.estado IN ('PENDIENTE_ACTIVACION', 'ACTIVA', 'BLOQUEADA_TEMPORAL'))
  EXECUTE FUNCTION app.fn_cuenta_admin_minimo();
"""

REVERSO_TRG_CUENTA_ADMIN_MINIMO = """
DROP TRIGGER trg_cuenta_admin_minimo ON app.cuenta_staff;
DROP FUNCTION app.fn_cuenta_admin_minimo();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('usuario', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('nombre_visible', models.CharField(blank=True, max_length=100, null=True)),
                ('rol', models.CharField(choices=[('EDITOR', 'Editor'), ('ADMINISTRADOR', 'Administrador')], max_length=13)),
                ('estado', models.CharField(choices=[('PENDIENTE_ACTIVACION', 'Pendiente de activación'), ('ACTIVA', 'Activa'), ('BLOQUEADA_TEMPORAL', 'Bloqueada temporalmente'), ('DESACTIVADA', 'Desactivada'), ('ANONIMIZADA', 'Anonimizada')], db_default='PENDIENTE_ACTIVACION', default='PENDIENTE_ACTIVACION', max_length=20)),
                ('debe_cambiar_credencial', models.BooleanField(db_default=True, default=True)),
                ('mfa_activo', models.BooleanField(db_default=False, default=False)),
                ('secreto_mfa', models.BinaryField(blank=True, null=True)),
                ('intentos_fallidos', models.SmallIntegerField(db_default=0, default=0)),
                ('bloqueos_consecutivos', models.SmallIntegerField(db_default=0, default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_acceso_en', null=True)),
                ('autorizacion_otorgada_en', models.DateTimeField(blank=True, null=True)),
                ('autorizacion_version_politica', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('desactivado_en', models.DateTimeField(blank=True, null=True)),
                ('anonimizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'cuenta del staff',
                'verbose_name_plural': 'cuentas del staff',
                'db_table': 'cuenta_staff',
                'constraints': [models.CheckConstraint(condition=models.Q(('usuario__isnull', True), ('usuario__regex', '^[a-z0-9._-]{1,40}$'), _connector='OR'), name='ck_cuenta_staff_usuario_patron'), models.CheckConstraint(condition=models.Q(('rol__in', ['EDITOR', 'ADMINISTRADOR'])), name='ck_cuenta_staff_rol'), models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE_ACTIVACION', 'ACTIVA', 'BLOQUEADA_TEMPORAL', 'DESACTIVADA', 'ANONIMIZADA'])), name='ck_cuenta_staff_estado'), models.CheckConstraint(condition=models.Q(('intentos_fallidos__gte', 0)), name='ck_cuenta_staff_intentos'), models.CheckConstraint(condition=models.Q(('bloqueos_consecutivos__gte', 0)), name='ck_cuenta_staff_bloqueos'), models.CheckConstraint(condition=models.Q(('estado', 'ANONIMIZADA'), models.Q(('nombre_visible__isnull', False), ('usuario__isnull', False)), _connector='OR'), name='ck_cuenta_staff_identidad'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'ANONIMIZADA'), _negated=True), models.Q(('anonimizado_en__isnull', False), ('last_login__isnull', True), ('mfa_activo', False), ('nombre_visible__isnull', True), ('password__startswith', '!'), ('secreto_mfa__isnull', True), ('usuario__isnull', True)), _connector='OR'), name='ck_cuenta_staff_anonimizada'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'ACTIVA'), _negated=True), models.Q(('autorizacion_otorgada_en__isnull', False), ('autorizacion_version_politica__isnull', False)), _connector='OR'), name='ck_cuenta_staff_activa_autorizada'), models.CheckConstraint(condition=models.Q(models.Q(('estado__in', ['DESACTIVADA', 'ANONIMIZADA']), _negated=True), ('desactivado_en__isnull', False), _connector='OR'), name='ck_cuenta_staff_desactivada'), models.CheckConstraint(condition=models.Q(('mfa_activo', False), ('secreto_mfa__isnull', False), _connector='OR'), name='ck_cuenta_staff_mfa')],
            },
        ),
        migrations.CreateModel(
            name='SesionPanel',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('autenticado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='cuentas.cuentastaff')),
            ],
            options={
                'verbose_name': 'sesión del panel',
                'verbose_name_plural': 'sesiones del panel',
                'db_table': 'sesion_panel',
            },
        ),
        migrations.CreateModel(
            name='CuentaCodigoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_codigo', models.CharField(max_length=128)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacion', to='cuentas.cuentastaff')),
            ],
            options={
                'db_table': 'cuenta_codigo_recuperacion',
                'constraints': [models.UniqueConstraint(fields=('cuenta', 'hash_codigo'), name='uq_cuenta_codigo_recuperacion')],
            },
        ),
        # DB_HANDOFF cuenta_staff: constraint trigger trg_cuenta_admin_minimo (RULE-015, AC-108).
        migrations.RunSQL(TRG_CUENTA_ADMIN_MINIMO, reverse_sql=REVERSO_TRG_CUENTA_ADMIN_MINIMO),
    ]
