# Generated by Django 5.2.17 on 2026-09-26 05:18 (makemigrations --empty + RunSQL)

# CHG-DB-002 (DB_HANDOFF v1.2, OBS-QA003-01, DEC-AUTO-190): las cuentas del staff nunca se borran
# físicamente; se desactivan y se anonimizan (ADR-DB-004 §2). Defensa en profundidad:
# (1) trigger BEFORE DELETE que rechaza cualquier borrado (también del propietario);
# (2) app_rw pierde DELETE y TRUNCATE sobre cuenta_staff.
# Patrón expand, reversible (el reverso vuelve a la situación de DB_HANDOFF v1.1).
from django.db import migrations

TRG_CUENTA_SIN_BORRADO = """
CREATE FUNCTION app.fn_cuenta_sin_borrado() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, app, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION 'Las cuentas del staff no se borran físicamente: se desactivan y se anonimizan (id %)', OLD.id
    USING ERRCODE = 'restrict_violation', CONSTRAINT = 'trg_cuenta_sin_borrado';
END
$$;
CREATE TRIGGER trg_cuenta_sin_borrado
  BEFORE DELETE ON app.cuenta_staff
  FOR EACH ROW EXECUTE FUNCTION app.fn_cuenta_sin_borrado();
"""

REVERSO_TRG_CUENTA_SIN_BORRADO = """
DROP TRIGGER trg_cuenta_sin_borrado ON app.cuenta_staff;
DROP FUNCTION app.fn_cuenta_sin_borrado();
"""

PRIVILEGIOS = "REVOKE DELETE, TRUNCATE ON app.cuenta_staff FROM app_rw;"

REVERSO_PRIVILEGIOS = "GRANT DELETE ON app.cuenta_staff TO app_rw;"


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_inicial'),
    ]

    operations = [
        migrations.RunSQL(TRG_CUENTA_SIN_BORRADO, reverse_sql=REVERSO_TRG_CUENTA_SIN_BORRADO),
        migrations.RunSQL(PRIVILEGIOS, reverse_sql=REVERSO_PRIVILEGIOS),
    ]
