/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DestinoAleatorio } from '../../models/destino-aleatorio';

export interface PublicoObtenerDestinoAleatorio$Params {
}

export function publicoObtenerDestinoAleatorio(http: HttpClient, rootUrl: string, params?: PublicoObtenerDestinoAleatorio$Params, context?: HttpContext): Observable<StrictHttpResponse<DestinoAleatorio>> {
  const rb = new RequestBuilder(rootUrl, publicoObtenerDestinoAleatorio.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DestinoAleatorio>;
    })
  );
}

publicoObtenerDestinoAleatorio.PATH = '/api/v1/publico/destinos/aleatorio';
