/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FacetasDestinos } from '../../models/facetas-destinos';

export interface PublicoObtenerFacetasDestinos$Params {
}

export function publicoObtenerFacetasDestinos(http: HttpClient, rootUrl: string, params?: PublicoObtenerFacetasDestinos$Params, context?: HttpContext): Observable<StrictHttpResponse<FacetasDestinos>> {
  const rb = new RequestBuilder(rootUrl, publicoObtenerFacetasDestinos.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FacetasDestinos>;
    })
  );
}

publicoObtenerFacetasDestinos.PATH = '/api/v1/publico/facetas/destinos';
