/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Inicio } from '../../models/inicio';

export interface PublicoObtenerInicio$Params {
}

export function publicoObtenerInicio(http: HttpClient, rootUrl: string, params?: PublicoObtenerInicio$Params, context?: HttpContext): Observable<StrictHttpResponse<Inicio>> {
  const rb = new RequestBuilder(rootUrl, publicoObtenerInicio.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Inicio>;
    })
  );
}

publicoObtenerInicio.PATH = '/api/v1/publico/inicio';
