/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Escalas } from '../../models/escalas';

export interface PublicoObtenerEscalas$Params {
}

export function publicoObtenerEscalas(http: HttpClient, rootUrl: string, params?: PublicoObtenerEscalas$Params, context?: HttpContext): Observable<StrictHttpResponse<Escalas>> {
  const rb = new RequestBuilder(rootUrl, publicoObtenerEscalas.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Escalas>;
    })
  );
}

publicoObtenerEscalas.PATH = '/api/v1/publico/escalas';
