/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginaCreditoMedio } from '../../models/pagina-credito-medio';

export interface PublicoListarCreditos$Params {

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function publicoListarCreditos(http: HttpClient, rootUrl: string, params?: PublicoListarCreditos$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaCreditoMedio>> {
  const rb = new RequestBuilder(rootUrl, publicoListarCreditos.PATH, 'get');
  if (params) {
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaCreditoMedio>;
    })
  );
}

publicoListarCreditos.PATH = '/api/v1/publico/creditos';
