/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { PaginaInstitucionalActualizacion } from '../../models/pagina-institucional-actualizacion';
import { PaginaInstitucionalPanel } from '../../models/pagina-institucional-panel';

export interface PanelActualizarPaginaInstitucional$Params {
  id: Id;
      body: PaginaInstitucionalActualizacion
}

export function panelActualizarPaginaInstitucional(http: HttpClient, rootUrl: string, params: PanelActualizarPaginaInstitucional$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaInstitucionalPanel>> {
  const rb = new RequestBuilder(rootUrl, panelActualizarPaginaInstitucional.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaInstitucionalPanel>;
    })
  );
}

panelActualizarPaginaInstitucional.PATH = '/api/v1/panel/contenidos/paginas/{id}';
