/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { PaginaInstitucionalPanel } from '../../models/pagina-institucional-panel';

export interface PanelObtenerPaginaInstitucional$Params {
  id: Id;
}

export function panelObtenerPaginaInstitucional(http: HttpClient, rootUrl: string, params: PanelObtenerPaginaInstitucional$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaInstitucionalPanel>> {
  const rb = new RequestBuilder(rootUrl, panelObtenerPaginaInstitucional.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaInstitucionalPanel>;
    })
  );
}

panelObtenerPaginaInstitucional.PATH = '/api/v1/panel/contenidos/paginas/{id}';
