/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { TipoAventuraPanel } from '../../models/tipo-aventura-panel';

export interface PanelObtenerTipoAventura$Params {
  id: Id;
}

export function panelObtenerTipoAventura(http: HttpClient, rootUrl: string, params: PanelObtenerTipoAventura$Params, context?: HttpContext): Observable<StrictHttpResponse<TipoAventuraPanel>> {
  const rb = new RequestBuilder(rootUrl, panelObtenerTipoAventura.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TipoAventuraPanel>;
    })
  );
}

panelObtenerTipoAventura.PATH = '/api/v1/panel/contenidos/tipos-aventura/{id}';
