/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstadoEditorial } from '../../models/estado-editorial';
import { PaginaContenidoResumen } from '../../models/pagina-contenido-resumen';

export interface PanelListarTiposAventura$Params {
  estado?: EstadoEditorial;

/**
 * Filtro de texto del panel (título, alt, crédito según el recurso).
 */
  q?: string;

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function panelListarTiposAventura(http: HttpClient, rootUrl: string, params?: PanelListarTiposAventura$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaContenidoResumen>> {
  const rb = new RequestBuilder(rootUrl, panelListarTiposAventura.PATH, 'get');
  if (params) {
    rb.query('estado', params.estado, {});
    rb.query('q', params.q, {});
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaContenidoResumen>;
    })
  );
}

panelListarTiposAventura.PATH = '/api/v1/panel/contenidos/tipos-aventura';
