/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GuiaPanel } from '../../models/guia-panel';
import { Id } from '../../models/id';

export interface PanelObtenerGuia$Params {
  id: Id;
}

export function panelObtenerGuia(http: HttpClient, rootUrl: string, params: PanelObtenerGuia$Params, context?: HttpContext): Observable<StrictHttpResponse<GuiaPanel>> {
  const rb = new RequestBuilder(rootUrl, panelObtenerGuia.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GuiaPanel>;
    })
  );
}

panelObtenerGuia.PATH = '/api/v1/panel/contenidos/guias/{id}';
