/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GuiaEntrada } from '../../models/guia-entrada';
import { GuiaPanel } from '../../models/guia-panel';

export interface PanelCrearGuia$Params {

/**
 * UUID opcional (DEC-AUTO-107, CHG-API-001). Ámbito: (cuenta, clave), único en TODAS las operaciones del panel (DB_HANDOFF v1.1, UNIQUE(cuenta_id, clave)); cada petición debe usar una clave nueva. Solo se guardan respuestas 2xx confirmadas, durante 24 h. Repetir la misma clave en la misma operación con la misma huella (operación + parámetros de ruta + cuerpo canónico) devuelve el código y el cuerpo originales sin repetir el efecto (ALT-017). Misma clave con otra operación u otra huella → 422 idempotencia_conflicto. Si hay una petición concurrente con la misma clave aún en curso y la espera supera 3 s → 409 idempotencia_en_curso con Retry-After (reintentable con la misma clave). Excepción: panelCrearCuenta no persiste su respuesta (AC-106, la contraseña temporal nunca se guarda); repetirla con una clave ya completada → 409 idempotencia_respuesta_no_reproducible con Location de la cuenta creada (DEC-AUTO-129). Si la operación falla (4xx/5xx) no se guarda nada y el reintento con la misma clave la ejecuta de nuevo.
 */
  'Idempotency-Key'?: string;
      body: GuiaEntrada
}

export function panelCrearGuia(http: HttpClient, rootUrl: string, params: PanelCrearGuia$Params, context?: HttpContext): Observable<StrictHttpResponse<GuiaPanel>> {
  const rb = new RequestBuilder(rootUrl, panelCrearGuia.PATH, 'post');
  if (params) {
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GuiaPanel>;
    })
  );
}

panelCrearGuia.PATH = '/api/v1/panel/contenidos/guias';
