/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { ItinerarioActualizacion } from '../../models/itinerario-actualizacion';
import { ItinerarioPanel } from '../../models/itinerario-panel';

export interface PanelActualizarItinerario$Params {
  id: Id;
      body: ItinerarioActualizacion
}

export function panelActualizarItinerario(http: HttpClient, rootUrl: string, params: PanelActualizarItinerario$Params, context?: HttpContext): Observable<StrictHttpResponse<ItinerarioPanel>> {
  const rb = new RequestBuilder(rootUrl, panelActualizarItinerario.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItinerarioPanel>;
    })
  );
}

panelActualizarItinerario.PATH = '/api/v1/panel/contenidos/itinerarios/{id}';
