/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { TipoAventuraActualizacion } from '../../models/tipo-aventura-actualizacion';
import { TipoAventuraPanel } from '../../models/tipo-aventura-panel';

export interface PanelActualizarTipoAventura$Params {
  id: Id;
      body: TipoAventuraActualizacion
}

export function panelActualizarTipoAventura(http: HttpClient, rootUrl: string, params: PanelActualizarTipoAventura$Params, context?: HttpContext): Observable<StrictHttpResponse<TipoAventuraPanel>> {
  const rb = new RequestBuilder(rootUrl, panelActualizarTipoAventura.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TipoAventuraPanel>;
    })
  );
}

panelActualizarTipoAventura.PATH = '/api/v1/panel/contenidos/tipos-aventura/{id}';
