/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DestinoActualizacion } from '../../models/destino-actualizacion';
import { DestinoGuardado } from '../../models/destino-guardado';
import { Id } from '../../models/id';

export interface PanelActualizarDestino$Params {
  id: Id;
      body: DestinoActualizacion
}

export function panelActualizarDestino(http: HttpClient, rootUrl: string, params: PanelActualizarDestino$Params, context?: HttpContext): Observable<StrictHttpResponse<DestinoGuardado>> {
  const rb = new RequestBuilder(rootUrl, panelActualizarDestino.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DestinoGuardado>;
    })
  );
}

panelActualizarDestino.PATH = '/api/v1/panel/contenidos/destinos/{id}';
