/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { TerminoGlosarioPanel } from '../../models/termino-glosario-panel';

export interface PanelObtenerTerminoGlosario$Params {
  id: Id;
}

export function panelObtenerTerminoGlosario(http: HttpClient, rootUrl: string, params: PanelObtenerTerminoGlosario$Params, context?: HttpContext): Observable<StrictHttpResponse<TerminoGlosarioPanel>> {
  const rb = new RequestBuilder(rootUrl, panelObtenerTerminoGlosario.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TerminoGlosarioPanel>;
    })
  );
}

panelObtenerTerminoGlosario.PATH = '/api/v1/panel/contenidos/glosario/{id}';
