/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';

export interface PanelEliminarItinerario$Params {
  id: Id;

/**
 * Versión conocida por el cliente (bloqueo optimista, DEC-AUTO-050).
 */
  version: number;
}

export function panelEliminarItinerario(http: HttpClient, rootUrl: string, params: PanelEliminarItinerario$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, panelEliminarItinerario.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('version', params.version, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

panelEliminarItinerario.PATH = '/api/v1/panel/contenidos/itinerarios/{id}';
