/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DestinoVistaPrevia } from '../../models/destino-vista-previa';
import { VistaPrevia } from '../../models/vista-previa';

export interface PanelVistaPreviaDestino$Params {
      body: DestinoVistaPrevia
}

export function panelVistaPreviaDestino(http: HttpClient, rootUrl: string, params: PanelVistaPreviaDestino$Params, context?: HttpContext): Observable<StrictHttpResponse<VistaPrevia>> {
  const rb = new RequestBuilder(rootUrl, panelVistaPreviaDestino.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VistaPrevia>;
    })
  );
}

panelVistaPreviaDestino.PATH = '/api/v1/panel/contenidos/destinos/vista-previa';
