# Generated by Django 5.2.17 on 2026-09-26 03:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busqueda', '0001_extensiones_funciones'),
        ('contenido', '0001_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenido', models.CharField(choices=[('DESTINO', 'Destino'), ('ITINERARIO', 'Itinerario'), ('GUIA', 'Guía'), ('TIPO', 'Tipo de aventura'), ('COLECCION', 'Colección'), ('TERMINO', 'Término de glosario'), ('PAGINA', 'Página institucional')], max_length=10)),
                ('slug', models.CharField(max_length=120)),
                ('titulo', models.CharField(max_length=150)),
                ('titulo_norm', models.CharField(max_length=150)),
                ('resumen', models.CharField(blank=True, max_length=300, null=True)),
                ('pais_nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('documento', django.contrib.postgres.search.SearchVectorField()),
                ('actualizado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('contenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento_busqueda', to='contenido.contenido')),
            ],
            options={
                'db_table': 'busqueda_documento',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['documento'], name='ix_busqueda_documento_fts'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('titulo_norm'), name='gin_trgm_ops'), name='ix_busqueda_titulo_trgm')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo_contenido__in', ['DESTINO', 'ITINERARIO', 'GUIA', 'TIPO'])), name='ck_busqueda_documento_tipo_contenido')],
            },
        ),
        # FK compuesta (ADR-DB-002 §3): el documento es del tipo de su contenido.
        migrations.RunSQL(
            "ALTER TABLE app.busqueda_documento ADD CONSTRAINT fk_busqueda_documento_contenido_tipo "
            "FOREIGN KEY (contenido_id, tipo_contenido) REFERENCES app.contenido (id, tipo) "
            "ON DELETE CASCADE;",
            reverse_sql="ALTER TABLE app.busqueda_documento DROP CONSTRAINT fk_busqueda_documento_contenido_tipo;",
        ),
    ]
