/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { PaginaRevisionResumen } from '../../models/pagina-revision-resumen';
import { TipoContenidoRuta } from '../../models/tipo-contenido-ruta';

export interface PanelListarRevisiones$Params {
  tipo: TipoContenidoRuta;
  id: Id;

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function panelListarRevisiones(http: HttpClient, rootUrl: string, params: PanelListarRevisiones$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaRevisionResumen>> {
  const rb = new RequestBuilder(rootUrl, panelListarRevisiones.PATH, 'get');
  if (params) {
    rb.path('tipo', params.tipo, {});
    rb.path('id', params.id, {});
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaRevisionResumen>;
    })
  );
}

panelListarRevisiones.PATH = '/api/v1/panel/contenidos/{tipo}/{id}/revisiones';
