/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { ImpactoRetiro } from '../../models/impacto-retiro';
import { TipoContenidoRuta } from '../../models/tipo-contenido-ruta';

export interface PanelObtenerImpactoRetiro$Params {
  tipo: TipoContenidoRuta;
  id: Id;
}

export function panelObtenerImpactoRetiro(http: HttpClient, rootUrl: string, params: PanelObtenerImpactoRetiro$Params, context?: HttpContext): Observable<StrictHttpResponse<ImpactoRetiro>> {
  const rb = new RequestBuilder(rootUrl, panelObtenerImpactoRetiro.PATH, 'get');
  if (params) {
    rb.path('tipo', params.tipo, {});
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImpactoRetiro>;
    })
  );
}

panelObtenerImpactoRetiro.PATH = '/api/v1/panel/contenidos/{tipo}/{id}/impacto-retiro';
