/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginaResultadoBusqueda } from '../../models/pagina-resultado-busqueda';

export interface PublicoBuscarPorGrupo$Params {
  grupo: 'destinos' | 'itinerarios' | 'guias' | 'tipos';

/**
 * Texto de búsqueda (2..100 caracteres tras recortar espacios).
 */
  q: string;

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function publicoBuscarPorGrupo(http: HttpClient, rootUrl: string, params: PublicoBuscarPorGrupo$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaResultadoBusqueda>> {
  const rb = new RequestBuilder(rootUrl, publicoBuscarPorGrupo.PATH, 'get');
  if (params) {
    rb.path('grupo', params.grupo, {});
    rb.query('q', params.q, {});
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaResultadoBusqueda>;
    })
  );
}

publicoBuscarPorGrupo.PATH = '/api/v1/publico/busqueda/{grupo}';
