/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BusquedaAgrupada } from '../../models/busqueda-agrupada';

export interface PublicoBuscar$Params {

/**
 * Texto de búsqueda (2..100 caracteres tras recortar espacios).
 */
  q: string;
}

export function publicoBuscar(http: HttpClient, rootUrl: string, params: PublicoBuscar$Params, context?: HttpContext): Observable<StrictHttpResponse<BusquedaAgrupada>> {
  const rb = new RequestBuilder(rootUrl, publicoBuscar.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BusquedaAgrupada>;
    })
  );
}

publicoBuscar.PATH = '/api/v1/publico/busqueda';
