/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccionAuditoria } from '../../models/accion-auditoria';
import { Id } from '../../models/id';
import { PaginaEventoAuditoria } from '../../models/pagina-evento-auditoria';

export interface PanelListarAuditoria$Params {
  desde?: string;
  hasta?: string;
  actor_id?: Id;
  accion?: AccionAuditoria;
  tipo_entidad?: string;
  resultado?: 'EXITO' | 'FALLO';

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function panelListarAuditoria(http: HttpClient, rootUrl: string, params?: PanelListarAuditoria$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaEventoAuditoria>> {
  const rb = new RequestBuilder(rootUrl, panelListarAuditoria.PATH, 'get');
  if (params) {
    rb.query('desde', params.desde, {});
    rb.query('hasta', params.hasta, {});
    rb.query('actor_id', params.actor_id, {});
    rb.query('accion', params.accion, {});
    rb.query('tipo_entidad', params.tipo_entidad, {});
    rb.query('resultado', params.resultado, {});
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaEventoAuditoria>;
    })
  );
}

panelListarAuditoria.PATH = '/api/v1/panel/auditoria';
