/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginaCategoriaGuiaPanel } from '../../models/pagina-categoria-guia-panel';

export interface PanelListarCategoriasGuia$Params {

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function panelListarCategoriasGuia(http: HttpClient, rootUrl: string, params?: PanelListarCategoriasGuia$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaCategoriaGuiaPanel>> {
  const rb = new RequestBuilder(rootUrl, panelListarCategoriasGuia.PATH, 'get');
  if (params) {
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaCategoriaGuiaPanel>;
    })
  );
}

panelListarCategoriasGuia.PATH = '/api/v1/panel/taxonomias/categorias-guia';
