/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfigInicioEntrada } from '../../models/config-inicio-entrada';
import { ConfigInicioPanel } from '../../models/config-inicio-panel';

export interface PanelActualizarConfigInicio$Params {
      body: ConfigInicioEntrada
}

export function panelActualizarConfigInicio(http: HttpClient, rootUrl: string, params: PanelActualizarConfigInicio$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfigInicioPanel>> {
  const rb = new RequestBuilder(rootUrl, panelActualizarConfigInicio.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfigInicioPanel>;
    })
  );
}

panelActualizarConfigInicio.PATH = '/api/v1/panel/inicio';
