/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfiguracionSitio } from '../../models/configuracion-sitio';
import { ConfiguracionSitioEntrada } from '../../models/configuracion-sitio-entrada';

export interface PanelActualizarConfiguracionSitio$Params {
      body: ConfiguracionSitioEntrada
}

export function panelActualizarConfiguracionSitio(http: HttpClient, rootUrl: string, params: PanelActualizarConfiguracionSitio$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfiguracionSitio>> {
  const rb = new RequestBuilder(rootUrl, panelActualizarConfiguracionSitio.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfiguracionSitio>;
    })
  );
}

panelActualizarConfiguracionSitio.PATH = '/api/v1/panel/configuracion';
