/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { Pais } from '../../models/pais';

export interface PanelObtenerPais$Params {
  id: Id;
}

export function panelObtenerPais(http: HttpClient, rootUrl: string, params: PanelObtenerPais$Params, context?: HttpContext): Observable<StrictHttpResponse<Pais>> {
  const rb = new RequestBuilder(rootUrl, panelObtenerPais.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Pais>;
    })
  );
}

panelObtenerPais.PATH = '/api/v1/panel/taxonomias/paises/{id}';
