/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoriaGuiaEntrada } from '../../models/categoria-guia-entrada';
import { CategoriaGuiaPanel } from '../../models/categoria-guia-panel';

export interface PanelCrearCategoriaGuia$Params {
      body: CategoriaGuiaEntrada
}

export function panelCrearCategoriaGuia(http: HttpClient, rootUrl: string, params: PanelCrearCategoriaGuia$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoriaGuiaPanel>> {
  const rb = new RequestBuilder(rootUrl, panelCrearCategoriaGuia.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoriaGuiaPanel>;
    })
  );
}

panelCrearCategoriaGuia.PATH = '/api/v1/panel/taxonomias/categorias-guia';
