/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pais } from '../../models/pais';
import { PaisEntrada } from '../../models/pais-entrada';

export interface PanelCrearPais$Params {
      body: PaisEntrada
}

export function panelCrearPais(http: HttpClient, rootUrl: string, params: PanelCrearPais$Params, context?: HttpContext): Observable<StrictHttpResponse<Pais>> {
  const rb = new RequestBuilder(rootUrl, panelCrearPais.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Pais>;
    })
  );
}

panelCrearPais.PATH = '/api/v1/panel/taxonomias/paises';
