/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Licencia } from '../../models/licencia';
import { LicenciaEntrada } from '../../models/licencia-entrada';

export interface PanelCrearLicencia$Params {
      body: LicenciaEntrada
}

export function panelCrearLicencia(http: HttpClient, rootUrl: string, params: PanelCrearLicencia$Params, context?: HttpContext): Observable<StrictHttpResponse<Licencia>> {
  const rb = new RequestBuilder(rootUrl, panelCrearLicencia.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Licencia>;
    })
  );
}

panelCrearLicencia.PATH = '/api/v1/panel/taxonomias/licencias';
