/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { Licencia } from '../../models/licencia';
import { LicenciaEntrada } from '../../models/licencia-entrada';

export interface PanelActualizarLicencia$Params {
  id: Id;
      body: LicenciaEntrada
}

export function panelActualizarLicencia(http: HttpClient, rootUrl: string, params: PanelActualizarLicencia$Params, context?: HttpContext): Observable<StrictHttpResponse<Licencia>> {
  const rb = new RequestBuilder(rootUrl, panelActualizarLicencia.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Licencia>;
    })
  );
}

panelActualizarLicencia.PATH = '/api/v1/panel/taxonomias/licencias/{id}';
