/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfiguracionSitio } from '../../models/configuracion-sitio';

export interface PanelObtenerConfiguracionSitio$Params {
}

export function panelObtenerConfiguracionSitio(http: HttpClient, rootUrl: string, params?: PanelObtenerConfiguracionSitio$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfiguracionSitio>> {
  const rb = new RequestBuilder(rootUrl, panelObtenerConfiguracionSitio.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfiguracionSitio>;
    })
  );
}

panelObtenerConfiguracionSitio.PATH = '/api/v1/panel/configuracion';
