/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoriaGuiaPanel } from '../../models/categoria-guia-panel';
import { Id } from '../../models/id';

export interface PanelObtenerCategoriaGuia$Params {
  id: Id;
}

export function panelObtenerCategoriaGuia(http: HttpClient, rootUrl: string, params: PanelObtenerCategoriaGuia$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoriaGuiaPanel>> {
  const rb = new RequestBuilder(rootUrl, panelObtenerCategoriaGuia.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoriaGuiaPanel>;
    })
  );
}

panelObtenerCategoriaGuia.PATH = '/api/v1/panel/taxonomias/categorias-guia/{id}';
