/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { PaginaPais } from '../../models/pagina-pais';

export interface PanelListarPaises$Params {
  region_id?: Id;

/**
 * Número de página (base 1). Fuera de rango → 404 pagina_fuera_de_rango.
 */
  pagina?: number;
}

export function panelListarPaises(http: HttpClient, rootUrl: string, params?: PanelListarPaises$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginaPais>> {
  const rb = new RequestBuilder(rootUrl, panelListarPaises.PATH, 'get');
  if (params) {
    rb.query('region_id', params.region_id, {});
    rb.query('pagina', params.pagina, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginaPais>;
    })
  );
}

panelListarPaises.PATH = '/api/v1/panel/taxonomias/paises';
