/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Id } from '../../models/id';
import { Licencia } from '../../models/licencia';

export interface PanelObtenerLicencia$Params {
  id: Id;
}

export function panelObtenerLicencia(http: HttpClient, rootUrl: string, params: PanelObtenerLicencia$Params, context?: HttpContext): Observable<StrictHttpResponse<Licencia>> {
  const rb = new RequestBuilder(rootUrl, panelObtenerLicencia.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Licencia>;
    })
  );
}

panelObtenerLicencia.PATH = '/api/v1/panel/taxonomias/licencias/{id}';
