# Generated by Django 5.2.17 on 2026-09-26 03:57

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models

# [SUPUESTO] Texto provisional del descargo (RULE-010): el Administrador lo sustituye desde la
# configuración del sitio (FEAT-047). Los datos del Responsable quedan vacíos (GAP-004).
DESCARGO_PROVISIONAL = (
    "La información de este sitio es orientativa y se revisa periódicamente, pero las "
    "condiciones del terreno, el clima, la normativa y la seguridad cambian. Antes de viajar, "
    "consulta fuentes oficiales actualizadas, valora tu preparación y contrata guías o seguros "
    "cuando la actividad lo requiera. Brújula Salvaje no se responsabiliza de las decisiones "
    "tomadas a partir de estos contenidos."
)


def sembrar_config_sitio(apps, schema_editor):
    ConfigSitio = apps.get_model("inicio", "ConfigSitio")
    ConfigSitio.objects.get_or_create(
        id=1,
        defaults={"nombre_marca": "Brújula Salvaje", "texto_descargo": DESCARGO_PROVISIONAL},
    )


def retirar_config_sitio(apps, schema_editor):
    ConfigSitio = apps.get_model("inicio", "ConfigSitio")
    ConfigSitio.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_inicial'),
        ('cuentas', '0001_inicial'),
        ('medios', '0001_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInicio',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('hero_titular', models.CharField(max_length=80)),
                ('hero_subtitulo', models.CharField(max_length=160)),
                ('actualizado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.cuentastaff')),
                ('hero_medio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medios.medio')),
            ],
            options={
                'db_table': 'config_inicio',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ck_config_inicio_singleton')],
            },
        ),
        migrations.CreateModel(
            name='ConfigSitio',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(db_default='Brújula Salvaje', default='Brújula Salvaje', max_length=60)),
                ('lema', models.CharField(blank=True, max_length=120, null=True)),
                ('texto_descargo', models.TextField()),
                ('responsable_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('responsable_identificacion', models.CharField(blank=True, max_length=40, null=True)),
                ('responsable_domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('responsable_canal_atencion', models.CharField(blank=True, max_length=200, null=True)),
                ('actualizado_en', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuentas.cuentastaff')),
            ],
            options={
                'db_table': 'config_sitio',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ck_config_sitio_singleton'), models.CheckConstraint(condition=models.Q(django.db.models.lookups.GreaterThanOrEqual(django.db.models.functions.text.Length('texto_descargo'), 1), django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('texto_descargo'), 100000)), name='ck_config_sitio_texto_descargo')],
            },
        ),
        migrations.CreateModel(
            name='DestacadoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('DESTINOS', 'Destinos'), ('ITINERARIOS', 'Itinerarios'), ('GUIAS', 'Guías')], max_length=12)),
                ('tipo_contenido', models.CharField(choices=[('DESTINO', 'Destino'), ('ITINERARIO', 'Itinerario'), ('GUIA', 'Guía'), ('TIPO', 'Tipo de aventura'), ('COLECCION', 'Colección'), ('TERMINO', 'Término de glosario'), ('PAGINA', 'Página institucional')], max_length=10)),
                ('orden', models.SmallIntegerField(db_default=0, default=0)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destacados', to='contenido.contenido')),
            ],
            options={
                'db_table': 'destacado_inicio',
                'constraints': [models.UniqueConstraint(fields=('seccion', 'contenido'), name='uq_destacado_inicio'), models.CheckConstraint(condition=models.Q(models.Q(('seccion', 'DESTINOS'), ('tipo_contenido', 'DESTINO')), models.Q(('seccion', 'ITINERARIOS'), ('tipo_contenido', 'ITINERARIO')), models.Q(('seccion', 'GUIAS'), ('tipo_contenido', 'GUIA')), _connector='OR'), name='ck_destacado_inicio_seccion_tipo')],
            },
        ),
        # FK compuesta: el contenido destacado es del tipo declarado (ADR-DB-002 §3, DATA-022).
        migrations.RunSQL(
            "ALTER TABLE app.destacado_inicio ADD CONSTRAINT fk_destacado_inicio_contenido_tipo "
            "FOREIGN KEY (contenido_id, tipo_contenido) REFERENCES app.contenido (id, tipo) "
            "ON DELETE CASCADE;",
            reverse_sql="ALTER TABLE app.destacado_inicio DROP CONSTRAINT fk_destacado_inicio_contenido_tipo;",
        ),
        # Singleton config_sitio con descargo provisional y Responsable vacío (GAP-004).
        migrations.RunPython(sembrar_config_sitio, reverse_code=retirar_config_sitio),
    ]
