# Generated by Django 5.2.17 on 2026-09-27 18:10 (makemigrations --empty + RunSQL)

# CHG-DB-002 (DB_HANDOFF v1.2, plan n=19, DEC-AUTO-204): los singletons de configuración se
# editan, no se borran. Solo REVOKE a app_rw (destacado_inicio conserva DELETE: su edición
# reemplaza filas). Sin trigger: el reverse_code de inicio.0001 borra el singleton con
# app_migrator. Patrón expand, reversible sin pérdida de datos.
from django.db import migrations

TABLAS = "app.config_inicio, app.config_sitio"


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_inicial'),
    ]

    operations = [
        migrations.RunSQL(
            f"REVOKE DELETE, TRUNCATE ON {TABLAS} FROM app_rw;",
            reverse_sql=f"GRANT DELETE ON {TABLAS} TO app_rw;",
        ),
    ]
