/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstadoSalud } from '../../models/estado-salud';

export interface SaludLive$Params {
}

export function saludLive(http: HttpClient, rootUrl: string, params?: SaludLive$Params, context?: HttpContext): Observable<StrictHttpResponse<EstadoSalud>> {
  const rb = new RequestBuilder(rootUrl, saludLive.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EstadoSalud>;
    })
  );
}

saludLive.PATH = '/health/live';
